### ISSUE TITLE
pornhub会一直转圈圈

### ISSUE THREAD

**Issue by lloyd18** [xxxily/h5player#1]
如题如题
![微信截图_20190415164204](https://user-images.githubusercontent.com/10294460/56119344-8ad1fd80-5f9e-11e9-93d0-5f22a5383b62.png)

**Comment by xxxily** [comment]
测试正常，可能是你的网络速度问题吧，你可以更新最新版本的插件试试，或者提供一下浏览器版本信息，我看下

**Comment by lloyd18** [comment]
> 测试正常，可能是你的网络速度问题吧，你可以更新最新版本的插件试试，或者提供一下浏览器版本信息，我看下

网络没问题，关了插件就不会。用的是360极速浏览器最新版 chrome内核69

**Comment by xxxily** [comment]
看了下，旧版本在360下确实会出现菊花，升级新版就好了。

**Comment by lloyd18** [comment]
> 看了下，旧版本在360下确实会出现菊花，升级新版就好了。

可是我用的就是修订版啊
