### ISSUE TITLE
自动跳转上回播放时间，（第一次访问并没有看过）

### ISSUE THREAD

**Issue by anyfeels** [xxxily/h5player#10]
自动跳转上回播放时间，（第一次访问之前并没有看过）自动跳转到视频结尾后跳转至第二集，重复以上一直循环。以下https://www.nfmovies.com/video/?39670-0-0.html

**Comment by xxxily** [comment]
> 自动跳转上回播放时间，（第一次访问之前并没有看过）自动跳转到视频结尾后跳转至第二集，重复以上一直循环。以下https://www.nfmovies.com/video/?39670-0-0.html

因为是判断播放地址导致的，它的视频播放地址一致，则认为是同一个视频，这个我后续看下能不能优化

**Comment by anyfeels** [comment]
是否应该考虑手动恢复上次播放进度而非自动。



------------------ 原始邮件 ------------------
发件人: "xxxily"<notifications@github.com>; 
发送时间: 2019年10月14日(星期一) 上午9:37
收件人: "xxxily/h5player"<h5player@noreply.github.com>; 
抄送: "Any4eel &#xB2;&#xBA;&#xB9;9&#x1F1E8;&#x1F1F3;"<4664241@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xxxily/h5player] 自动跳转上回播放时间，（第一次访问并没有看过） (#10)



 
自动跳转上回播放时间，（第一次访问之前并没有看过）自动跳转到视频结尾后跳转至第二集，重复以上一直循环。以下https://www.nfmovies.com/video/?39670-0-0.html
  
因为是判断播放地址导致的，它的视频播放地址一致，则认为是同一个视频，这个我后续看下能不能优化

**Comment by xxxily** [comment]
> 自动跳转上回播放时间，（第一次访问之前并没有看过）自动跳转到视频结尾后跳转至第二集，重复以上一直循环。以下https://www.nfmovies.com/video/?39670-0-0.html

手动太麻烦了，不过后续如果出了设置面板的话，可以考虑增加一个选项，让用户自行决定自动还是手动恢复播放进度

**Comment by anyfeels** [comment]
增加可选设置是个不错的选择，毕竟需要适应不同的使用环境。




------------------ 原始邮件 ------------------
发件人: "xxxily"<notifications@github.com>; 
发送时间: 2019年10月15日(星期二) 下午2:18
收件人: "xxxily/h5player"<h5player@noreply.github.com>; 
抄送: "Any4eel &#xB2;&#xBA;&#xB9;9&#x1F1E8;&#x1F1F3;"<4664241@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xxxily/h5player] 自动跳转上回播放时间，（第一次访问并没有看过） (#10)



 
自动跳转上回播放时间，（第一次访问之前并没有看过）自动跳转到视频结尾后跳转至第二集，重复以上一直循环。以下https://www.nfmovies.com/video/?39670-0-0.html
  
手动太麻烦了，不过后续如果出了设置面板的话，可以考虑增加一个选项，让用户自行决定自动还是手动恢复播放进度

**Comment by xxxily** [comment]
> 增加可选设置是个不错的选择，毕竟需要适应不同的使用环境。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "xxxily"<notifications@github.com>; 发送时间: 2019年10月15日(星期二) 下午2:18 收件人: "xxxily/h5player"<h5player@noreply.github.com>; 抄送: "Any4eel &#xB2;&#xBA;&#xB9;9&#x1F1E8;&#x1F1F3;"<4664241@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [xxxily/h5player] 自动跳转上回播放时间，（第一次访问并没有看过） (#10) 自动跳转上回播放时间，（第一次访问之前并没有看过）自动跳转到视频结尾后跳转至第二集，重复以上一直循环。以下https://www.nfmovies.com/video/?39670-0-0.html 手动太麻烦了，不过后续如果出了设置面板的话，可以考虑增加一个选项，让用户自行决定自动还是手动恢复播放进度 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已增加shift+r控制自动恢复播放进度功能，目前只能全局控制，后续会继续优化此功能
