### ISSUE TITLE
建议添加一个小的快捷键提示列表

### ISSUE THREAD

**Issue by MOYUtianming** [xxxily/h5player#100]
# 建议作者添加一个小的快捷键提示列表
1. 我是从GreasyFork 的推广看到这个脚本的，说实话，它给了我很多惊喜，主要包括快捷缩放、快捷调速，快捷跳秒。
2. **但是它的快捷键太多了(有40个)，对初学者很不友好，很多时候我需要退出全屏查表来学习它的功能，这与快捷键的设置初衷似乎不合**。如果可以的话，希望作者可以给出一个即时的tip列表，使用一个快捷键组合呼出，然后让初学者通过search的方法逐渐熟悉这个插件的各个功能群，否则的话，说实话，学习成本很高。
3. 在这一方面，我推荐类似vsCode的Ctrl + P的命令行呼出设计，然后各个功能组有统一的前缀(例如调速的功能组可以统一使用Speed前缀，然后后面的分支名用 *-* 隔开，如Speed-Lower)，同时后面括号里给出相应的快捷键说明，方便记忆。
5. 或者，也可以使用一个类似Xmind的可选显示常驻快捷键列表的方法来实现，在全屏时以半透明的方式展示。
4. **当然，如果作者你有实际困难，没有时间或者精力做出这个功能，我也觉得这个插件已经很好了，十分感谢你的付出。**

**Comment by rsyqvthv** [comment]
不能同意更多

+ 在这个面板上为每个快捷键加入关闭按钮.

**Comment by boyliuxiaopeng** [comment]
希望如此，不然记不住快捷键~

**Comment by xxxily** [comment]
插件的菜单上有相关入口
