### ISSUE TITLE
Youtube 按键冲突问题.

### ISSUE THREAD

**Issue by Senrt** [xxxily/h5player#101]
Youtube 本身自带的 J/后退 K/暂停 L/前进 非常好用, 另外 F/全屏 这些用习惯了离不开, 比使用空格键和方向键操作好很多. 这些被占用的快捷键如果可以设定开启或关闭某些快捷键就很好了.   : )

**Comment by sc10221** [comment]
对对对！Youtube本身的快捷键就很好用，插件和youtube的字幕开关键冲突。，C键（速度调整，yooutube自带的速度调整快捷键是shift+>，挺好用的）。如果可以根据具体网站启用和禁用个别快捷键的话就这个插件就上天了！
