### ISSUE TITLE
mac上Command键没有处理，导致和系统按键冲突，已测试解决，请作者验证后更新下

### ISSUE THREAD

**Issue by vincentOliu** [xxxily/h5player#11]
首先，谢谢作者提供的脚本，在mac上使用，command键一直不响应，然后自己修复了下，使用了挺长时间，没发现有什么问题（其实是好久没更新脚本），更新脚本后，需要再次修改，所以希望作者测试下，合并下代码，处理下mac下Command响应的问题，谢谢

处理方式，以测试，增加event.altKey的处理：
1.
if (event.shiftKey && !event.ctrlKey && !event.altKey ) {
        // 网页全屏

增加 metaKey 处理

if (event.shiftKey && !event.ctrlKey && !event.altKey && !event.metaKey) {
        // 网页全屏

2.
// 防止其它无关组合键冲突
      if (event.altKey || event.ctrlKey || event.shiftKey) return

增加 metaKey 处理

// 防止其它无关组合键冲突
      if (event.altKey || event.ctrlKey || event.shiftKey || event.metaKey) return

3. 
/* 当前触发的组合键 */
        const combineKey = [];
        if (event.ctrlKey) {
          combineKey.push('ctrl');
        }
        if (event.shiftKey) {
          combineKey.push('shift');
        }
        if (event.altKey) {
          combineKey.push('alt');
        }
        combineKey.push(key);

增加 metaKey 处理

/* 当前触发的组合键 */
        const combineKey = [];
        if (event.ctrlKey) {
          combineKey.push('ctrl');
        }
        if (event.shiftKey) {
          combineKey.push('shift');
        }
        if (event.altKey) {
          combineKey.push('alt');
        }
        if (event.metaKey) {
          combineKey.push('command');
        }
        combineKey.push(key);

**Comment by xxxily** [comment]
手头上没有mac book，无法进行测试，代码已更新，如果还有什么问题欢迎反馈
