### ISSUE TITLE
请问百度网盘在线播放已经不支持了吗？

### ISSUE THREAD

**Issue by YwSama** [xxxily/h5player#117]
我使用的是Chrome+油猴，在B站中测试了下是可以使用的，但在百度网盘在线播放的界面并未有反应。

**Comment by tab619** [comment]
我也是！但是好像换个浏览器就又可以，可能是谷歌浏览器最新更新的原因？求解决

**Comment by tab619** [comment]
百度网盘在线失效，然后其他网站用的时候好像也有延迟

**Comment by doyoudo** [comment]
百度网盘默认使用的flash,只需要设置禁用flash,也就是使用HTML5来播放.倍速播放的插件支持所有h5视频

**Comment by tab619** [comment]
> 百度网盘默认使用的flash,只需要设置禁用flash,也就是使用HTML5来播放.倍速播放的插件支持所有h5视频

谢谢您的解答，好像禁用谷歌浏览器禁用flash也还是不可以哎？Safari可以用

**Comment by YwSama** [comment]
> 百度网盘默认使用的flash,只需要设置禁用flash,也就是使用HTML5来播放.倍速播放的插件支持所有h5视频

我今天用了一下，未禁用Flash也可以了

**Comment by YwSama** [comment]
> > 百度网盘默认使用的flash,只需要设置禁用flash,也就是使用HTML5来播放.倍速播放的插件支持所有h5视频
> 
> 谢谢您的解答，好像禁用谷歌浏览器禁用flash也还是不可以哎？Safari可以用

今天用了一下，又可以了，之前的老版本以及该项目我都有安装。

**Comment by tab619** [comment]
> > > 百度网盘默认使用的flash,只需要设置禁用flash,也就是使用HTML5来播放.倍速播放的插件支持所有h5视频
> > 
> > 
> > 谢谢您的解答，好像禁用谷歌浏览器禁用flash也还是不可以哎？Safari可以用
> 
> 今天用了一下，又可以了，之前的老版本以及该项目我都有安装。

谢谢您！感动！我的也又可以了，谢谢您！谢谢您开发的软件，给我学习网课视频帮助超级大！

**Comment by YwSama** [comment]
> > > > 百度网盘默认使用的flash,只需要设置禁用flash,也就是使用HTML5来播放.倍速播放的插件支持所有h5视频
> > > 
> > > 
> > > 谢谢您的解答，好像禁用谷歌浏览器禁用flash也还是不可以哎？Safari可以用
> > 
> > 
> > 今天用了一下，又可以了，之前的老版本以及该项目我都有安装。
> 
> 谢谢您！感动！我的也又可以了，谢谢您！谢谢您开发的软件，给我学习网课视频帮助超级大！

不是啊..我也只是使用者..感谢开发大佬

**Comment by tab619** [comment]
> > > > > 百度网盘默认使用的flash,只需要设置禁用flash,也就是使用HTML5来播放.倍速播放的插件支持所有h5视频
> > > > 
> > > > 
> > > > 谢谢您的解答，好像禁用谷歌浏览器禁用flash也还是不可以哎？Safari可以用
> > > 
> > > 
> > > 今天用了一下，又可以了，之前的老版本以及该项目我都有安装。
> > 
> > 
> > 谢谢您！感动！我的也又可以了，谢谢您！谢谢您开发的软件，给我学习网课视频帮助超级大！
> 
> 不是啊..我也只是使用者..感谢开发大佬

害，那也非常感谢你的维护啦！
