### ISSUE TITLE
开启脚本会导致Youtube音频异常

### ISSUE THREAD

**Issue by Mizzooo** [xxxily/h5player#118]
开启脚本后视频中的音乐和音效有明显的齿音 一点回响 关闭脚本后恢复正常
示例视频 https://www.youtube.com/watch?v=MpPrN5oShK8

// @version      3.3.0
Windows 1909
Chrome 最新版

**Comment by gqqnbig** [comment]
我听不出来区别。。可能你要具体说下几分几秒。
