### ISSUE TITLE
在b站和一个样式冲突的问题

### ISSUE THREAD

**Issue by waldens** [xxxily/h5player#12]
不知这个issue是否冒昧，因为和外部工具冲突，本不属于这个脚本自身的问题，也不能奢求作者阅读外部代码去排查。但我自己能力有限，实在找不出是哪里冲突了，故请求帮助：

问题如下：
• 单独使用这个样式 [视频网站简化（bilibili/优酷/腾讯/斗鱼/爱奇艺） | Userstyles.org](https://userstyles.org/styles/138386/bilibili)，一切正常
• 单独使用脚本“HTML5视频播放器增强脚本”，也一切正常
• 但是，这俩凑一起在bilibili网站使用，就会出现如下动图所示的“播放窗口会在网页上消失”的问题

目前只有bilibili网站上发现，不知道是两者哪里冲突了呢？在不阉割各自功能的情况下，怎样解决呢？（修改那个样式的代码也可以）

动图在如下环境测试和录制：
• win7x64
• 百分浏览器版本 4.0.9.112（正式版本） （64 位） (portable) (Chromium 74.0.3729.169)
• HTML5视频播放器增强脚本 v3.0.5
• Tampermonkey 4.8.41

简单的重现步骤：
1. 安装最新版的Tampermonkey和Stylus
2. 安装本脚本 和 [这个样式](https://userstyles.org/styles/138386/bilibili)
3. 打开网页：https://www.bilibili.com/video/av60072760/ 查看即可

动图(直接嵌入会被替换成githubusercontent的地址加载不出来)：https://s1.boluo.link/imgs/2019/10/fd836a2f7cac00b2.gif

**Comment by xxxily** [comment]
> 不知这个issue是否冒昧，因为和外部工具冲突，本不属于这个脚本自身的问题，也不能奢求作者阅读外部代码去排查。但我自己能力有限，实在找不出是哪里冲突了，故请求帮助：
> 
> 问题如下：
> • 单独使用这个样式 [视频网站简化（bilibili/优酷/腾讯/斗鱼/爱奇艺） | Userstyles.org](https://userstyles.org/styles/138386/bilibili)，一切正常
> • 单独使用脚本“HTML5视频播放器增强脚本”，也一切正常
> • 但是，这俩凑一起在bilibili网站使用，就会出现如下动图所示的“播放窗口会在网页上消失”的问题
> 
> 目前只有bilibili网站上发现，不知道是两者哪里冲突了呢？在不阉割各自功能的情况下，怎样解决呢？（修改那个样式的代码也可以）
> 
> 动图在如下环境测试和录制：
> • win7x64
> • 百分浏览器版本 4.0.9.112（正式版本） （64 位） (portable) (Chromium 74.0.3729.169)
> • HTML5视频播放器增强脚本 v3.0.5
> • Tampermonkey 4.8.41
> 
> 简单的重现步骤：
> 
> 1. 安装最新版的Tampermonkey和Stylus
> 2. 安装本脚本 和 [这个样式](https://userstyles.org/styles/138386/bilibili)
> 3. 打开网页：https://www.bilibili.com/video/av60072760/ 查看即可
> 
> 动图(直接嵌入会被替换成githubusercontent的地址加载不出来)：https://s1.boluo.link/imgs/2019/10/fd836a2f7cac00b2.gif

这个是提示样式要进行动态计算和增加相对位置样式导致的，我后面看下怎么优化下这个地方

**Comment by xxxily** [comment]
> 不知这个issue是否冒昧，因为和外部工具冲突，本不属于这个脚本自身的问题，也不能奢求作者阅读外部代码去排查。但我自己能力有限，实在找不出是哪里冲突了，故请求帮助：
> 
> 问题如下：
> • 单独使用这个样式 [视频网站简化（bilibili/优酷/腾讯/斗鱼/爱奇艺） | Userstyles.org](https://userstyles.org/styles/138386/bilibili)，一切正常
> • 单独使用脚本“HTML5视频播放器增强脚本”，也一切正常
> • 但是，这俩凑一起在bilibili网站使用，就会出现如下动图所示的“播放窗口会在网页上消失”的问题
> 
> 目前只有bilibili网站上发现，不知道是两者哪里冲突了呢？在不阉割各自功能的情况下，怎样解决呢？（修改那个样式的代码也可以）
> 
> 动图在如下环境测试和录制：
> • win7x64
> • 百分浏览器版本 4.0.9.112（正式版本） （64 位） (portable) (Chromium 74.0.3729.169)
> • HTML5视频播放器增强脚本 v3.0.5
> • Tampermonkey 4.8.41
> 
> 简单的重现步骤：
> 
> 1. 安装最新版的Tampermonkey和Stylus
> 2. 安装本脚本 和 [这个样式](https://userstyles.org/styles/138386/bilibili)
> 3. 打开网页：https://www.bilibili.com/video/av60072760/ 查看即可
> 
> 动图(直接嵌入会被替换成githubusercontent的地址加载不出来)：https://s1.boluo.link/imgs/2019/10/fd836a2f7cac00b2.gif

已进行优化处理 请更新到：3.1.0 测试下试试

**Comment by waldens** [comment]
已测试，一切正常，谢谢谢谢！<img alt="ghe-emoji" title=":_onion_head_admire2:" src="https://cloud.githubusercontent.com/assets/136959/13371069/eae4c870-dce2-11e5-817c-a7019c5ac22b.gif">
