### ISSUE TITLE
Firefox浏览器无法使用

### ISSUE THREAD

**Issue by suwenshun** [xxxily/h5player#120]
在B站测试了多次，刷新了好多次，脚本还是不能使用。脚本也重新安装了，问题还是没有解决。在Chrome浏览器中可以使用，我经常使用Firefox浏览器，希望能够提供这个问题的解决方法。我使用的Firefox浏览器版本是79.0（最新版），64位。

**Comment by xxxily** [comment]
经测试是正常的
