### ISSUE TITLE
为了一劳永逸解决快捷键等冲突，是否可以开放自定义快捷键和可选网站功能？

### ISSUE THREAD

**Issue by MY1L** [xxxily/h5player#122]
我发现许多人都在报这个问题，我也是遇到才来的。本脚本与流行浏览器视频变速插件 https://github.com/igrigorik/videospeed （一键快捷键，不需组合键很方便）有大量快捷键冲突，比如截屏同时会减速（videospeed会同时侦听小写和大写）。也许可以直接改脚本，但下次更新就又改回去了。

还有目前脚本比较暴力在所有网站上生效，所以遇到冲突概率也必然大增。我想设为只在个别网站生效（比如b站有个很好用的脚本含逐帧截屏，是按钮形式，比本脚本组合快捷键方便），撤销原始匹配修改了用户匹配（包含网站域名和包含的外部iframe域名），但脚本就失效了。所以想了解用户匹配还需要添加哪些。

**Comment by xxxily** [comment]
已支持自定义：https://h5player.anzz.top/home/customConfiguration.html
