### ISSUE TITLE
快捷键帮助建议

### ISSUE THREAD

**Issue by MC-dusk** [xxxily/h5player#124]
建议：

- 加入一个用于查看快捷键列表的快捷键，类似知乎的“shift+/”。

- 加入前进后退1s，比如“alt+←”

- 加入更高的倍速播放快捷键，比如0.5x、4x，可以用alt修饰键

- 加入视频下载

**Comment by MC-dusk** [comment]
今天发现似乎企鹅电竞的适配有些问题，比如按enter回车全屏就看不到弹幕了

**Comment by xxxily** [comment]
已有类似的快捷键和选项

**Comment by MC-dusk** [comment]
😭
