### ISSUE TITLE
加速功能失效需要重启

### ISSUE THREAD

**Issue by Beta-y** [xxxily/h5player#125]
最近几天打开网页播放视频的时候发现倍速失效了，需要关闭插件，关闭油猴，再杀掉浏览器重启插件才行，不知道什么问题。
目前只测试了百度网盘视频和B站，都出现了这种情况

**Comment by yinxiu1996** [comment]
我也经历过，我当时只要右键油猴→管理扩展程序→关闭再开启，就可以了，不用重启浏览器。你下次碰到了试试。
