### ISSUE TITLE
学堂在线新版无法调节速度，音量等

### ISSUE THREAD

**Issue by ZengShuyuan** [xxxily/h5player#131]
[学堂在线新版](https://next.xuetangx.com/)
开始停止，网页全屏，全屏，前进后退等功能没问题，但是音量调节，速度调节，非常混乱，比如连续点↑会：20，30，30，30，40，30
老版课程这个插件用起来很顺利，没有影响。

感谢开发者，这个插件真的巨巨巨巨实用！

**Comment by xxxily** [comment]
> [学堂在线新版](https://next.xuetangx.com/)
> 开始停止，网页全屏，全屏，前进后退等功能没问题，但是音量调节，速度调节，非常混乱，比如连续点↑会：20，30，30，30，40，30
> 老版课程这个插件用起来很顺利，没有影响。
> 
> 感谢开发者，这个插件真的巨巨巨巨实用！

确实是有这样的问题，不太好解决，后续看下怎么优化吧
