### ISSUE TITLE
哔哩哔哩直播会黑屏

### ISSUE THREAD

**Issue by 2213238386** [xxxily/h5player#133]
9.3发现哔哩哔哩直播会黑屏

**Comment by xxxily** [comment]
> 9.3发现哔哩哔哩直播会黑屏

最新版本已尝试解决B站直播黑屏问题，可更新下试试

**Comment by 2213238386** [comment]
ok了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xxxily"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 晚上11:03
收件人: "xxxily/h5player"<h5player@noreply.github.com&gt;; 
抄送: "满天星✨"<2213238386@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xxxily/h5player] 哔哩哔哩直播会黑屏 (#133)





  
9.3发现哔哩哔哩直播会黑屏
  
最新版本已尝试解决B站直播黑屏问题，可更新下试试
