### ISSUE TITLE
请问排除了某视频网站，如何重新添加回来，文档找不到说明

### ISSUE THREAD

**Issue by lyjhyjyes** [xxxily/h5player#135]
https://www.zhenbuka.com/vodplay/72754-1-25/
应该能上传图片吧

(https://user-images.githubusercontent.com/57164542/92332059-7e77a480-f0ad-11ea-9c3b-0ff59aa14b31.png)

**Comment by xxxily** [comment]
> https://www.zhenbuka.com/vodplay/72754-1-25/
> 应该能上传图片吧
> 
> (https://user-images.githubusercontent.com/57164542/92332059-7e77a480-f0ad-11ea-9c3b-0ff59aa14b31.png)

不是按那个移除按钮就可以了吗？如果不行就试试Ctrl+space 禁用/启用 该播放插件
