### ISSUE TITLE
Html5不能正常运行

### ISSUE THREAD

**Issue by wangzongxu99** [xxxily/h5player#14]
My volitmonkey's Html5视频播放器增强器不能正常运行，其他的脚本可以正常使用。并且Greasy Fork中的账号我登陆不上去，修改账号密码时，后台不能发到我的邮箱，导致我不能修改密码，也不能登录。

**Comment by xxxily** [comment]
> My volitmonkey's Html5视频播放器增强器不能正常运行，其他的脚本可以正常使用。并且Greasy Fork中的账号我登陆不上去，修改账号密码时，后台不能发到我的邮箱，导致我不能修改密码，也不能登录。

并没出现你描述得情况，请描述清楚你使用的软件版本，浏览器版本之类的信息

**Comment by wangzongxu99** [comment]
> 并没出现你描述得情况，请描述清楚你使用的软件版本，浏览器版本之类的信息

  #@我用的是火狐浏览器70.0（64位），暴力猴v2.11.2，

**Comment by wangzongxu99** [comment]
> 
> 
> > My volitmonkey's Html5视频播放器增强器不能正常运行，其他的脚本可以正常使用。并且Greasy Fork中的账号我登陆不上去，修改账号密码时，后台不能发到我的邮箱，导致我不能修改密码，也不能登录。
> 
> 并没出现你描述得情况，请描述清楚你使用的软件版本，浏览器版本之类的信息

我说的是看腾讯视频之类的网站不出现快进的按钮，之前有的，我重新装了一下，发现还不行

**Comment by xxxily** [comment]
> > > My volitmonkey's Html5视频播放器增强器不能正常运行，其他的脚本可以正常使用。并且Greasy Fork中的账号我登陆不上去，修改账号密码时，后台不能发到我的邮箱，导致我不能修改密码，也不能登录。
> > 
> > 
> > 并没出现你描述得情况，请描述清楚你使用的软件版本，浏览器版本之类的信息
> 
> 我说的是看腾讯视频之类的网站不出现快进的按钮，之前有的，我重新装了一下，发现还不行

我用火狐68测试了，倍数播放正常啊，默认消息提示已经移到了视频的右上角，不再在视频中间显示。

**Comment by wangzongxu99** [comment]
emmmm我的火狐70版本和360浏览器好像都不行呢

**Comment by wangzongxu99** [comment]
> 
> 
> > > > My volitmonkey's Html5视频播放器增强器不能正常运行，其他的脚本可以正常使用。并且Greasy Fork中的账号我登陆不上去，修改账号密码时，后台不能发到我的邮箱，导致我不能修改密码，也不能登录。
> > > 
> > > 
> > > 并没出现你描述得情况，请描述清楚你使用的软件版本，浏览器版本之类的信息
> > 
> > 
> > 我说的是看腾讯视频之类的网站不出现快进的按钮，之前有的，我重新装了一下，发现还不行
> 
> 我用火狐68测试了，倍数播放正常啊，默认消息提示已经移到了视频的右上角，不再在视频中间显示。
emmmm我的火狐70版本和360浏览器好像都不行呢
