### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by KevinLance** [xxxily/h5player#143]
1. **问题描述**

希望可以写一个按钮或者快捷键用来打开快捷键设置列表，快捷键太多记不住，在列表显示快捷键是否冲突（仅仅是一个小建议，如果没时间的话，已经很好啦）
2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

谷歌浏览器     85.0.4183.121（正式版本） （64 位）
4. **其他附注信息**

无

**Comment by xxxily** [comment]
已增加到插件选项里
