### ISSUE TITLE
B站(bilibili)视频倍速播放时，使用左右键前进后退时，会重置播放速度到1倍速[BUG]

### ISSUE THREAD

**Issue by unicorn1009** [xxxily/h5player#144]
1. **问题描述**
B站视频使用倍速播放时，按->按键，会直接变回1倍速

2. **出现上述问题的地址**
https://www.bilibili.com/

3. **你使用的浏览器与浏览器版本信息**
MacOs版Edge浏览器 85.0.564.8 (官方内部版本) Dev (64 位)

4. **其他附注信息**

**Comment by xxxily** [comment]
已修复
