### ISSUE TITLE
[BUG] Uncaught (in promise) TypeError: window.GM_getTab is not a function

### ISSUE THREAD

**Issue by Komari-Koshigaya** [xxxily/h5player#145]
1. **问题描述**
控制台 报错 Uncaught (in promise) TypeError: window.GM_getTab is not a function

2. **出现上述问题的地址**
任何网站

3. **你使用的浏览器与浏览器版本信息**
谷歌内核 78.0.3904.108

4. **其他附注信息**
无

**Comment by Retia-Adolf** [comment]
Firefox Nightly 84.0a1 (2020-11-08) (64-bit), ViolentMonkey 2.12.7 同样报错

**Comment by lonelykid** [comment]
https://github.com/xxxily/h5player/issues/67
GM_getTab is exclusive to tampermonkey

**Comment by JAGulin** [comment]
The request to add GM_getTab was rejected by VM. https://github.com/violentmonkey/violentmonkey/issues/1120
