### ISSUE TITLE
[BUG]ac.qq.com腾讯漫画受影响了，正常左右快捷键被影响

### ISSUE THREAD

**Issue by dunkeng** [xxxily/h5player#146]
1. **问题描述**

ac.qq.com腾讯漫画，正常情况下，左右键是上下章切换，这个是漫画，不是视频，不需要用到脚本

2. **出现上述问题的地址**

ac.qq.com

3. **你使用的浏览器与浏览器版本信息**

chrome 85.0.4183.121

4. **其他附注信息**

建议增加白名单功能，默认一些常用网站就好，不需要全部匹配
我觉得“网页限制解除（改）”的白名单很实用
https://greasyfork.org/zh-CN/users/106222-qxin-i

**Comment by xxxily** [comment]
已支持自定义，见：https://h5player.anzz.top/home/customConfiguration.html
