### ISSUE TITLE
netflix issue

### ISSUE THREAD

**Issue by sypgfg** [xxxily/h5player#147]
在看netflix的时候如果开启这个脚本，按暂停后重新播放或者快进之类的会出现M7375错误。根据官方解释是由于插件导致的，我自己troubleshoot后发现是由于这个脚本导致的，希望能修复！

**Comment by whyjxz14** [comment]
打开就M7375现在

**Comment by naier1860** [comment]
是的，建议还是取消netflix吧，倍速nf自带了，每次看都要禁用下插件，要不然M7375报错

**Comment by xxxily** [comment]
已取消
