### ISSUE TITLE
在哔哩哔哩登录状态下，首页动态，刷到一个视频，退出后弹到首页最顶部，好崩溃

### ISSUE THREAD

**Issue by lyjhyjyes** [xxxily/h5player#15]

**Comment by lyjhyjyes** [comment]
有文字动态和视频动态，视频动态没有点进去，仅仅是点了全屏快捷键，esc退出。结果弹到动态顶部，又要重新下拉继续看

**Comment by xxxily** [comment]
> 有文字动态和视频动态，视频动态没有点进去，仅仅是点了全屏快捷键，esc退出。结果弹到动态顶部，又要重新下拉继续看

自己配一条自定义规则就可以了：
't.bilibili.com': {
    fullScreen: 'button[name="fullscreen-button"]'
}

下个版本会加上这条规则
