### ISSUE TITLE
希望可以快进掉广告

### ISSUE THREAD

**Issue by ArsenicX** [xxxily/h5player#156]
在看爱奇艺等平台的时候，总是要等几十秒的广告，希望可以支持把广告也加速
类似于这个脚本：[计时器掌控者](https://greasyfork.org/zh-CN/scripts/372673-%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85-%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87-%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8)，直接加速广告也算是变相的曲线救国去广告了

如果同时装了两个脚本，就是会导致加速冲突，我还要手忙脚乱地关掉一个脚本，用另一个改速度
希望大佬可以支持加速广告，感谢！！

**Comment by xxxily** [comment]
已支持

**Comment by ArsenicX** [comment]
> 已支持

dalao，我在爱奇艺上试了一下，还是不行呀。
我把其他拓展和脚本都关了，脚本也重装了，广告依旧是一秒一秒的倒数
