### ISSUE TITLE
B站←键后退, 外挂字幕不同步

### ISSUE THREAD

**Issue by VermilionStarUniverse** [xxxily/h5player#157]
1. **问题描述**
B站, 播放带外挂字幕的视频时, ←键进度后退时, 外挂字幕不一起回退, 而是停在回退前的时刻.

2. **出现上述问题的地址**
https://www.bilibili.com/video/BV1Qv411t7ZL

3. **浏览器与版本信息**
Edge Version 87.0.664.41 (64-Bit) & Chrome Version 86.0.4240.198 (64-Bit)

**Comment by RollerMoon** [comment]
不止是外挂字幕不回退，弹幕也不会回退。
因为插件只是针对HTML5视频的
 @VermilionStarUniverse

**Comment by Iuyitim** [comment]
> 不止是外挂字幕不回退，弹幕也不会回退。
> 因为插件只是针对HTML5视频的
> @VermilionStarUniverse

但油管的外挂字幕就可以随左方向键后退，不知为何

**Comment by qiansen1386** [comment]
> @Iuyitim 但油管的外挂字幕就可以随左方向键后退，不知为何
B站的时间轴同步可能有他自己的实现方式，如果B站的弹幕和字幕都绑定视频时间轴，对视频的操作可以连锁反应到弹幕和字幕上就没有问题，但是如果是B站播放器自己有个内部时间轴，视频弹幕字幕都围绕那个时间轴，那咱就抓瞎

**Comment by xxxily** [comment]
> > @Iuyitim 但油管的外挂字幕就可以随左方向键后退，不知为何
> 
> B站的时间轴同步可能有他自己的实现方式，如果B站的弹幕和字幕都绑定视频时间轴，对视频的操作可以连锁反应到弹幕和字幕上就没有问题，但是如果是B站播放器自己有个内部时间轴，视频弹幕字幕都围绕那个时间轴，那咱就抓瞎

不是能正常同步吗？难道是我操作不一样？
