### ISSUE TITLE
[BUG]B站网页全屏快捷键失效

### ISSUE THREAD

**Issue by szheng0212** [xxxily/h5player#158]
1. **问题描述**
B站网页全屏快捷键失效

2. **出现上述问题的地址**
b站视频

3. **你使用的浏览器与浏览器版本信息**
谷歌最新版本

4. **其他附注信息**

**Comment by qiansen1386** [comment]
你是指`f`键跟下一帧功能冲突么？但是你不觉得回车全屏更符合直觉么？好多播放器都是默认这么设置的啊。
