### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by 235337218** [xxxily/h5player#162]
https://appd872nnyh9503.pc.xiaoe-tech.com/bought
在这个网站上，按space键暂停不了视频

**Comment by 235337218** [comment]
但是关掉脚本，视频可以暂停。开启脚本的快捷键space键的暂停，会让视频在暂停和播放之间来回跳动

**Comment by singularity2000** [comment]
你这个网址点进去是一片空白啊

**Comment by 235337218** [comment]
https://appd872nnyh9503.pc.xiaoe-tech.com/index 这个网址试一试&nbsp;


go
yzdgdhd@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "singularity2000"<notifications@github.com&gt;; 
发送时间: 2021年2月8日(星期一) 晚上10:24
收件人: "xxxily/h5player";
抄送: "Author";
主题: Re: [xxxily/h5player] 小bug (#162)





 
你这个网址点进去是一片空白啊
 
&mdash;
