### ISSUE TITLE
腾讯体育直播，快捷键全屏，只能画中画，非真正全屏

### ISSUE THREAD

**Issue by lyjhyjyes** [xxxily/h5player#17]
https://sports.qq.com/kbsweb/game.htm?mid=100000:54431691

**Comment by xxxily** [comment]
> https://sports.qq.com/kbsweb/game.htm?mid=100000:54431691

直播暂时没测试到，回放正常，不过倍速快捷键不支持，下个版本会增加腾讯体育的回放倍速功能
