### ISSUE TITLE
影响了自带调速记忆，暂停再播放会恢复播放速度，测试了b站和优酷都这样，建议能共存[BUG]

### ISSUE THREAD

**Issue by hs20073** [xxxily/h5player#172]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by xxxily** [comment]
最新版支持调速共存，但要自己手动开启，共存后其实更多问题，相当于有两套逻辑可以影响调速，所以通常会非常混乱，请按需开启
