### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tmboom** [xxxily/h5player#176]
1. **问题描述**
小建议
一个是跳转片头功能，在脚本头部注释出一下，=好后面写下默认跳转到几分钟 规定格式，主流网站都有跳转片头，但是解析网站是没用跳转片头的功能的，不知道能不能实现，

第二个是可否可以给一个地方，自由填入网站头，来保存默认播放倍速，因为这个脚本无法记忆解析视频的网页配置，还有给一个默认倍速的设置填入口

2. **出现上述问题的地址**
这种解析 就没有办法记忆倍速 http://17kyun.com/api.php?url=视频地址 

3. **你使用的浏览器与浏览器版本信息**
 360极速浏览器 版本号：13.0.2196.0 

4. **其他附注信息**

**Comment by xxxily** [comment]
第二个功能最新版已实现
