### ISSUE TITLE
[BUG]建议还是取消netflix吧，倍速nf自带了，每次看都要禁用下插件，要不然M7375报错

### ISSUE THREAD

**Issue by naier1860** [xxxily/h5player#179]
建议还是取消netflix吧，倍速nf自带了，每次看都要禁用下插件，要不然M7375报错

**Comment by traceyoukkkk** [comment]
加一

**Comment by StudentTang** [comment]
直接插件（浏览器图标）——html5增强——排除XXXX（网站）不行吗

**Comment by joeytwiddle** [comment]
Unfortunately, I also getting the M7375 error, whenever we pause and unpause Netflix, or rewind/forwardwind/seek.

However it is fine if we just watch the stream from beginning to end without any interruption.

Using Google Chrome on Linux

I use this plugin to change the speed to 1.1 or 1.2 (Netflix 1.25 is too big of a jump), and also to increase the brightness.
