### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by KungWanyi** [xxxily/h5player#184]
建议增加视频清晰度调整功能，比如正常情况下视频清晰度不够，增加清晰度调整功能后，可以通过插件增强视频清晰度。

**Comment by xxxily** [comment]
> 建议增加视频清晰度调整功能，比如正常情况下视频清晰度不够，增加清晰度调整功能后，可以通过插件增强视频清晰度。

对画质增强方面没研究，暂时没法实现
