### ISSUE TITLE
百度网盘网页版好像不支持倍速播放

### ISSUE THREAD

**Issue by cong-shao1** [xxxily/h5player#185]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by China-Qingshao** [comment]
javascript:videojs.getPlayers("video-player").html5player.tech_.setPlaybackRate(2)
把上述这个作为书签存为网页，想2倍速就点书签一下；后面（2）随便改（10)就是指10倍速

**Comment by xxxily** [comment]
已修复
