### ISSUE TITLE
YouTube全屏或宽屏倍速播放时，下滑评论区高概率卡画面

### ISSUE THREAD

**Issue by TsXcd** [xxxily/h5player#186]
复现步骤：
1开启倍速如2倍播放，打开新的YouTube视频页，开始播放后全屏
2此时滑动鼠标下滑到评论区，多次下滑查看后确保视频一直保持播放，
3返回顶部查看视频，发现画面卡住，但音频和进度条不受影响，
4卡住的画面如果此时拖动进度条前进或后退一点即可恢复

**Comment by xxxily** [comment]
没重现到该现象，另外新版的chrome，进入后台播放后再回来确实容易出现画面黑屏现象，但这和插件无关
