### ISSUE TITLE
百度网盘上倍速不能用

### ISSUE THREAD

**Issue by JabraYJ** [xxxily/h5player#187]

**Comment by China-Qingshao** [comment]
javascript:videojs.getPlayers("video-player").html5player.tech_.setPlaybackRate(2)
把上述这个作为书签存为网页，想2倍速就点书签一下

**Comment by China-Qingshao** [comment]
后面（2）随便改（10)就是指10倍速

**Comment by China-Qingshao** [comment]
javascript:videojs.getPlayers("video-player").html5player.tech_.setPlaybackRate(2)
把上述这个作为书签存为网页，想2倍速就点书签一下

**Comment by xxxily** [comment]
已修复
