### ISSUE TITLE
[错误]在西瓜视频的全屏播放问题

### ISSUE THREAD

**Issue by AK47buibuibui** [xxxily/h5player#190]
1. **问题描述**

在西瓜视频不管是按【回车】还是按【回车】加【另一个键】效果都是变成【网页全屏】而不是【全屏】
还要最上面第一个插件我在b站和西瓜用的也有点区别，禁用了在b站用不了，但是在西瓜禁用不了，最上面第二个快捷键我搞了半天在两个网站都还是没有效果，希望作者能给我说下是怎么用的

2. **出现上述问题的地址**

https://www.ixigua.com/6737585215457198605?logTag=0hY_IOFo-4w1EY5bcJ_Bo

3. **你使用的浏览器与浏览器版本信息**

Microsoft Edge 是最新版本版本 88.0.705.63 官方内部版本 64 位

4. **其他附注信息**

能不能再加一个像b站那样的关灯的东西，就是除了视频别的地方变成黑的，这个加不加其实都行，其实网站太多你可以在几个热门的特色网站弄一些特色的功能以及快捷键，比如关弹幕啥的

**Comment by likaijie-droid** [comment]
噢噢

**Comment by xxxily** [comment]
已修复，下个版本即可正常
