### ISSUE TITLE
斗鱼虎牙直播旋转相关的问题

### ISSUE THREAD

**Issue by AK47buibuibui** [xxxily/h5player#191]
1. **问题描述**

虎牙旋转后黑屏，旋转360°后复原。斗鱼旋转后视频变到右下角，切不能复原，只能刷新网页，如果这个功能用不了的话建议禁用这个功能，再在左上角出个文字提示

2. **出现上述问题的地址**

斗鱼虎牙直播

3. **你使用的浏览器与浏览器版本信息**

MicrosoftEdge是最新版本88.0.705.63官方内部版本64位

4. **其他附注信息**

**Comment by wakk121** [comment]
虎牙平台录播不能正常播放是静止画面
