### ISSUE TITLE
[BUG]腾讯课堂按左右快进会重置到视频初始位置

### ISSUE THREAD

**Issue by AcerFeng** [xxxily/h5player#192]
1. **问题描述**
腾讯课堂按左右快进会重置到视频初始位置

2. **出现上述问题的地址**
ke.qq.com

3. **你使用的浏览器与浏览器版本信息**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"

4. **其他附注信息**

**Comment by xxxily** [comment]
已优化
