### ISSUE TITLE
[功能建议]：全量加载视频

### ISSUE THREAD

**Issue by Cdners** [xxxily/h5player#193]
1. 问题描述
> 部分网站 m3u8 或者 mp4 视频加载速度较慢, 如果能全量加载的话, 快进后退观看起来会更友好

2. 出现上述问题的地址
> 所有网站

3. 你使用的浏览器与浏览器版本信息
> Edge

4.其他附注信息

**Comment by xxxily** [comment]
暂时做不到，如果有实现方案的话，可提供参考下，我加进去
