### ISSUE TITLE
增加一个回调，以便在init之前允许自定义

### ISSUE THREAD

**Issue by gqqnbig** [xxxily/h5player#194]
经常有issue提到要禁用快捷键或者对某些网站进行自定义，这里提供一种方法。我看到脚本有这样的代码

```
  TCC = h5PlayerTccInit(h5Player);

  try {
    /* 初始化全局所需的相关方法 */
    h5Player.init(true);
```

我觉得可以增加一句

```
if(window.h5Player.preInit)
  window.h5Player.preInit(TCC 或者 taskConf);
```

这样用户可以自行添加另一个userscript，使用自定义逻辑修改taskConf，达到对某些网站禁用某些快捷键的目的。

**Comment by gqqnbig** [comment]
我其实有另一个问题，不知道是否应该新建issue。就是n播放下一个视频，很容易误按。按空格会不小心按到n（或者cvbm）。

我很少用下一个视频的功能，想禁用。

**Comment by xxxily** [comment]
已支持自定义，见：https://h5player.anzz.top/home/customConfiguration.html
