### ISSUE TITLE
请问排除的网站应该写在哪里？

### ISSUE THREAD

**Issue by Cleverambo** [xxxily/h5player#195]
1. **问题描述** 
我尝试添加了代码但是没有效果
<img width="777" alt="image" src="https://user-images.githubusercontent.com/36615067/109094402-d9cd4a00-7754-11eb-9a5f-517461a77a7a.png">

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**
macOS Safari 14.0.3

4. **其他附注信息**

**Comment by MUNIZCX** [comment]
可以去设置里面排除网站
[chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=5ff55e99-7ae8-46b4-a126-21a1a181fe16+settings](url)

**Comment by singularity2000** [comment]
不建议更改脚本，因为难度高，不可靠，而且一旦升级你辛辛苦苦做的修改可能就没了。正解是在油猴中设置，本人亲测有效。用油猴打开此脚本，然后点击设置，截图中打红框的是我做出的修改，但与你的需求正好反过来：让此脚本只在没有倍速功能的简陋视频网站上生效。
![image](https://user-images.githubusercontent.com/61232355/109415011-28971000-79f1-11eb-8679-9b5d9768fba8.png)

**Comment by Cleverambo** [comment]
非常感谢

**Comment by Cleverambo** [comment]
> 不建议更改脚本，因为难度高、不可靠，而且一旦升级你辛辛苦苦做的修改可能就没了。正解是在油猴中设置，本人亲测有效。用油猴打开此脚本，然后点击设置，截图中打红框的是我做出的修改，但与你的需求正好反过来：我让此脚本只在没有倍速功能的简陋视频网站上生效。
> ![image](https://user-images.githubusercontent.com/61232355/109415011-28971000-79f1-11eb-8679-9b5d9768fba8.png)
> 语法格式参见https://developer.chrome.com/docs/extensions/mv2/match_patterns/

非常感谢
