### ISSUE TITLE
[BUG]b站直播加载脚本后会导致直播加载出现问题

### ISSUE THREAD

**Issue by norper** [xxxily/h5player#196]
1. **问题描述**
一般情况下,在直播暂停一段时间后继续观看直播的话,会出现突然后台加载后直播直接跳转到当前转播的画面的情况
加载该脚本后出现了这种情况,在并未使用倍速功能的情况下,出现了播放一段时间后,画面跟不上转播实时画面然后突然跳转到实时画面的情况

2. **出现上述问题的地址**
https://live.bilibili.com/6?spm_id_from=333.851.b_7265706f7274466972737431.1

3. **你使用的浏览器与浏览器版本信息**
 Google Chrome 版本 77.0.3865.35
4. **其他附注信息**

**Comment by xxxily** [comment]
没发现此类情况
