### ISSUE TITLE
[BUG]在巴哈姆特动漫疯使用后只有声音没有画面

### ISSUE THREAD

**Issue by Tian-Zun** [xxxily/h5player#197]
1. **问题描述**
在巴哈姆特动漫疯使用后只有声音没有画面

2. **出现上述问题的地址**
https://ani.gamer.com.tw/

3. **你使用的浏览器与浏览器版本信息**
Google Chrome 目前是最新版本
版本 88.0.4324.190 (正式版本) (64 位元)

4. **其他附注信息**

**Comment by Herrror** [comment]
同
