### ISSUE TITLE
lol官网直播窗口会变很小

### ISSUE THREAD

**Issue by tangssymm** [xxxily/h5player#2]
https://lpl.qq.com/es/msi/2019/
如图：
![TIM截图20190512145349](https://user-images.githubusercontent.com/18440461/57578814-c8ef0e00-74c5-11e9-9aa8-f261f2359922.png)

**Comment by xxxily** [comment]
是按了某个快捷键之后就变小了吗？还是一进去就变小？现在没直播了，进去看不到你这种现象。

**Comment by tangssymm** [comment]
> 是按了某个快捷键之后就变小了吗？还是一进去就变小？现在没直播了，进去看不到你这种现象。

进去之后就会这样，当时油猴只有这一个脚本，关闭之后就正常。
