### ISSUE TITLE
[BUG]bilibili标签页崩溃

### ISSUE THREAD

**Issue by BaiBuCYBGT** [xxxily/h5player#200]
1. **问题描述**
bilibili标签页崩溃，多刷新几次可以正常使用，但是再打开同站会标签页崩溃

2. **出现上述问题的地址**
https://www.bilibili.com/

3. **你使用的浏览器与浏览器版本信息**
火狐86.0.1x64

4. **其他附注信息**
前几天还能正常使用的，今天打开b站就崩溃了，关闭脚本就正常

**Comment by dangxit** [comment]
> 
> 
>     1. **问题描述**
>        bilibili标签页崩溃，多刷新几次可以正常使用，但是再打开同站会标签页崩溃
> 
>     2. **出现上述问题的地址**
>        https://www.bilibili.com/
> 
>     3. **你使用的浏览器与浏览器版本信息**
>        火狐86.0.1x64
> 
>     4. **其他附注信息**
>        前几天还能正常使用的，今天打开b站就崩溃了，关闭脚本就正常

同上，我的firefox86.0.0x64也出现了问题。在bilibili.com全站都会崩溃，包括专栏，番剧等。但是在live.bilibili.com 或 manga.bilibili.com 就不会出现问题

**Comment by Dynamith** [comment]
我也一样，大佬求抽时间修复一下

**Comment by JER-ry** [comment]
同出现此问题
Firefox 86.0.1x64
ViolentMonkey v2.12.11

**Comment by AxisLin199** [comment]
同样是火狐浏览器在b站的标签页崩溃。

**Comment by Clancyli** [comment]
同崩溃

**Comment by xxxily** [comment]
> 1. **问题描述**
>    bilibili标签页崩溃，多刷新几次可以正常使用，但是再打开同站会标签页崩溃
> 2. **出现上述问题的地址**
>    https://www.bilibili.com/
> 3. **你使用的浏览器与浏览器版本信息**
>    火狐86.0.1x64
> 4. **其他附注信息**
>    前几天还能正常使用的，今天打开b站就崩溃了，关闭脚本就正常

最新版已经修复该问题

**Comment by nowfeeltherain** [comment]
> 不登录好像不会崩溃, 登陆后必崩溃

同！我上论坛时也会这样！不登录的时候没事，登录之后就会出现标签页崩溃！！！求怎么解决啊！我用的是tor浏览器
