### ISSUE TITLE
[BUG]B站倍速显示bug，希望大佬修复下，用了很久这个一直没修复

### ISSUE THREAD

**Issue by icareyou1** [xxxily/h5player#202]
1. **问题描述**
 B站播放视频时，同一个视频下如果视频集数多，自动播放下一集后，再调倍速，左上角倍速的数字标签不显示，倍速效果还是有的希望能够修复一下 

2. **出现上述问题的地址**
 B站

3. **你使用的浏览器与浏览器版本信息**
 chrome 版本 89.0.4389.82（正式版本） （64 位）

4. **其他附注信息**
这个插件很赞，一直都是用这个，因为学习时不时调倍速，希望能修复，感谢大佬

**Comment by xxxily** [comment]
已修复，感谢反馈
