### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shanyan-wcx** [xxxily/h5player#209]
1. **问题描述**
网飞上开启脚本拖动进度条或暂停再播放会报7375错误。

2. **出现上述问题的地址**
https://www.netflix.com

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge
版本 89.0.774.63 (官方内部版本) (64 位)

4. **其他附注信息**

**Comment by xxxily** [comment]
建议在netflix上禁用该插件
