### ISSUE TITLE
键位设置目前是参考Potplayer的吗？ 能否参考VLC会好一些？

### ISSUE THREAD

**Issue by scutxd** [xxxily/h5player#21]
键位设置其实见仁见智的，所以想和你讨论讨论。
我看了PotPlayer和VLC的键位设置，我觉得VLC似乎会更通用一些，所以能否改成VLC的键位设置。
我自己在代码中修改了。

**Comment by xxxily** [comment]
> 键位设置其实见仁见智的，所以想和你讨论讨论。
> 我看了PotPlayer和VLC的键位设置，我觉得VLC似乎会更通用一些，所以能否改成VLC的键位设置。
> 我自己在代码中修改了。

习惯性问题，后面有时间再出个界面配置自定义快捷键即可
