### ISSUE TITLE
图标资源更新失败

### ISSUE THREAD

**Issue by boxie123** [xxxily/h5player#212]
1. **问题描述**
icon后的网址需魔法上网，否则提示资源更新失败。

2. **出现上述问题的地址**
https://raw.githubusercontent.com/xxxily/h5player/master/logo.png

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge 89.0.774.68

4. **其他附注信息**
~~我就来水个issue~~，但是每天启动浏览器弹出来个“资源更新失败”的提示确实挺烦的。

**Comment by xxxily** [comment]
稍后替换
