### ISSUE TITLE
[BUG] 哔哩哔哩切p后不显示提示，但功能正常，刷新后恢复

### ISSUE THREAD

**Issue by ESWZY** [xxxily/h5player#216]
1. **问题描述**
哔哩哔哩打开视频，开始时正常，在右边选集里切p后，不显示操作提示，但功能正常。刷新网页后恢复。

正常状态：

![zc](https://user-images.githubusercontent.com/32200887/113838061-04cda380-97c1-11eb-9fc5-722403d43fe3.jpg)

出问题状态：

![bzc](https://user-images.githubusercontent.com/32200887/113838249-2c247080-97c1-11eb-9232-2c41539b85b6.jpg)

2. **出现上述问题的地址**
分p的视频，如： https://www.bilibili.com/video/BV1At4113724

3. **你使用的浏览器与浏览器版本信息**
Google Chrome 89.0.4389.114 （当下最新版）

**Comment by Naitux** [comment]
还有点评论里回复没反应的BUG

**Comment by qiansen1386** [comment]
#227 有关

**Comment by xxxily** [comment]
该问题尽量在本周内修复

**Comment by ESWZY** [comment]
> 该问题尽量在本周内修复

好耶

**Comment by xxxily** [comment]
> > 该问题尽量在本周内修复
> 
> 好耶

已更新脚本

**Comment by Naitux** [comment]
点评论没反应的BUG已经没有了，大概是和b站更新了无限滚动评论有关系
