### ISSUE TITLE
油管快键键冲突

### ISSUE THREAD

**Issue by Sunsh4j** [xxxily/h5player#217]
在油管，按键c控制字幕开关，与脚本的加速0.1冲突，希望可以改进一下

**Comment by aur3l14no** [comment]
顺便，油管的速度调节是用 `>` 和 `<` 来完成的...

可能让作者改快捷键会比较难办 though...

**Comment by Senrt** [comment]
和油管自带的快捷键大量冲突,包括 F(全屏), J(后退) K(暂停) L(前进), 如何禁用和原生快捷键冲突的插件快捷键?

**Comment by bubbleboy11** [comment]
f键大多数平台都是全屏，想改不会改

**Comment by xxxily** [comment]
建议通过自定义配置解决：https://h5player.anzz.top/home/customConfiguration.html
