### ISSUE TITLE
腾讯课堂，播放进度控制bug

### ISSUE THREAD

**Issue by seanhepps** [xxxily/h5player#218]
谷歌浏览器，ke.qq.com播放，如果焦点聚焦在播放器，那么如果通过键盘左右两个按键调整播放进度就会导致视频从头开始播放。

**Comment by xxxily** [comment]
> 谷歌浏览器，ke.qq.com播放，如果焦点聚焦在播放器，那么如果通过键盘左右两个按键调整播放进度就会导致视频从头开始播放。

最好提供个具体的url地址，我测试部分免费的视频教程播放正常

**Comment by seanhepps** [comment]
https://ke.qq.com/course/343836?taid=11415507677036316
我找了很多连接，都是这么一个问题，在加速播放情况下，不能使用左右键进行快进，不然还是会使得视频从头开始播放。
谷歌和火狐浏览器都有这样的问题，我用的是mac版本的浏览器。
