### ISSUE TITLE
[BUG]百度云盘倍速炸了，无效了

### ISSUE THREAD

**Issue by PeakGymnast** [xxxily/h5player#223]
1. **问题描述**
百度云盘倍速炸了，无效了
2. **出现上述问题的地址**
http://pan.baidu.com
3. **你使用的浏览器与浏览器版本信息**
Edge浏览器
4. **其他附注信息**

**Comment by cong-shao1** [comment]
确实，我也是

**Comment by tangli159** [comment]
百度网盘倍速现在好像只能VIP才可使用了，[点这个](https://greasyfork.org/zh-CN/scripts/406241-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E5%80%8D%E9%80%9F%E6%92%AD%E6%94%BE)目前还能用，适配了直接群组看视频。我前天联系过链接里的脚本作者，他说`非VIP的播放器缺少属性导致无法更改倍速,需要更高级的前端开发人员寻找方法`，所以目前只能VIP通过这个脚本网页倍速了。非VIP我没有找到方法，找到的可以分享一下

**Comment by kristin0512** [comment]
火狐浏览器其实可以倍速，就是没插件用着方便

**Comment by tangli159** [comment]
> 火狐浏览器其实可以倍速，就是没插件用着方便

展开说说

**Comment by kristin0512** [comment]
> > 火狐浏览器其实可以倍速，就是没插件用着方便
> 
> 展开说说

就直接对着视频右键就有调速度的

**Comment by zycbuyao996** [comment]
恢复了

**Comment by xxxily** [comment]
百度盘问题已修复
