### ISSUE TITLE
脚本和bilibili的cc字幕不太兼容的问题

### ISSUE THREAD

**Issue by Leof715** [xxxily/h5player#224]
1. **问题描述**

bilibili视频的cc字幕不能和脚本正常兼容，在调节时间轴的时候会出现问题
比如在01：10的时点上使用左方向键回退5秒到01：05，但是字幕会停留在01：10的状态，而不是01：05的状态，直到视频正常播放，再次到01：10时，字幕播放才会恢复正常。使用右方向键快进或点击时间轴跳转均没有此问题
2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

Google Chorme 89.0.4389.128
4. **其他附注信息**

**Comment by Realzhazha** [comment]
同问题

**Comment by qiansen1386** [comment]
#157
