### ISSUE TITLE
[BUG] b站视频 突然无效

### ISSUE THREAD

**Issue by yueguangjifeng** [xxxily/h5player#227]
b站视频突然无效
1. **问题描述**
bilibili视频无效,快捷键不起作用

2. **出现上述问题的地址**
所有b站视频均无效

3. **你使用的浏览器与浏览器版本信息**
Google Chrome 90.0.4430.93 (Official Build) (64-bit) (cohort: Stable)

4. **其他附注信息**
其他视频网站也突然无效了, 不知是何缘故

**Comment by qiansen1386** [comment]
经测试，最新版本火狐一切如常。经测试，是 Violentmonkey 的问题。换用 Tempermonkey 问题解决。

**Comment by xxxily** [comment]
> GM_getTab

我这边试了正常，有可复现的地址吗？

**Comment by xxxily** [comment]
> 插件本身会有反馈，只是功能都失效。观察chrome的console发现以下错误
> 
> ```
> HTML5 video player enhanced script.user.js:1475 Uncaught (in promise) TypeError: window.GM_getTab is not a function
> ```
> 
> 怀疑是浏览器的问题，但 YouTube 一切如常。怀疑是B站更新，但貌似有别人反馈百度云等平台也有这个问题。目前只能盲猜Chrome 90可能有问题，我换去火狐再测试一下
我这边试了正常，有可复现的地址吗？

**Comment by xxxily** [comment]
> 插件本身会有反馈，只是功能都失效。观察chrome的console发现以下错误
> 
> ```
> HTML5 video player enhanced script.user.js:1475 Uncaught (in promise) TypeError: window.GM_getTab is not a function
> ```
> 
> 怀疑是浏览器的问题，但 YouTube 一切如常。怀疑是B站更新，但貌似有别人反馈百度云等平台也有这个问题。目前只能盲猜Chrome 90可能有问题，我换去火狐再测试一下

我这边试了正常，有可复现的地址吗？

**Comment by qiansen1386** [comment]
我这边又测试好像也好了？那close吧，可能油猴那边修复了？

我之前怀疑跟多开视频tab有关，如果我发现可稳定复现的方式会再来反馈。也可能只是油猴的小bug。

**Comment by qiansen1386** [comment]
又失效了

**Comment by XavOeYi** [comment]
我也发现这个问题。Microsoft Edge
版本 90.0.818.62 (官方内部版本) (64 位)

**Comment by XavOeYi** [comment]
b站在画中画功能中，可以使用加速

**Comment by qiansen1386** [comment]
打开了Tempermonkey的调试记录
Cannot read property '_addEventListener' of undefined
```
userscript.html?name=HTML5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8%E5%A2%9E%E5%BC%BA%E8%84%9A%E6%9C%AC.user.js&id=173d15e2-7553-4fd1-bd06-cd24e37362b1:2669 Uncaught TypeError: Cannot read property '_addEventListener' of undefined
    at EVENT.addEventListener (userscript.html?name=HTML5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8%E5%A2%9E%E5%BC%BA%E8%84%9A%E6%9C%AC.user.js&id=173d15e2-7553-4fd1-bd06-cd24e37362b1:2669)
    at Object.<anonymous> (nc-loader-0.8.1.min.js:2)
    at r (nc-loader-0.8.1.min.js:2)
    at Object.<anonymous> (nc-loader-0.8.1.min.js:2)
    at r (nc-loader-0.8.1.min.js:2)
    at Object.<anonymous> (nc-loader-0.8.1.min.js:2)
    at r (nc-loader-0.8.1.min.js:2)
    at Object.<anonymous> (nc-loader-0.8.1.min.js:2)
    at r (nc-loader-0.8.1.min.js:2)
    at Object.<anonymous> (nc-loader-0.8.1.min.js:2)
```

打开 SourceMap 之后发现

```javascript
    /**
     * 使用了Symbol之后，某些页面下会和 raven-js发生冲突，所以必须进行 try catch
     * TODO 如何解决该问题待研究，测试页面：https://xueqiu.com/S/SZ300498
     */
    try {
      /**
       * 对监听函数进行代理
       * 为了降低对性能的影响，此处只对特定的标签的事件进行代理
       */
      const listenerSymbol = Symbol.for(listener);
      let listenerProxy = null;
      if (config.proxyAll || proxyNodeType.includes(t.nodeName)) {
        try {
          listenerProxy = new Proxy(listener, {
            apply (target, ctx, args) {
              // const event = args[0]
              // console.log(event.type, event, target)

              /* 让外部通过 _listenerProxyApplyHandler_ 控制事件的执行 */
              if (t._listenerProxyApplyHandler_ instanceof Function) {
                const handlerResult = t._listenerProxyApplyHandler_(target, ctx, args, arg);
                if (handlerResult !== undefined) {
                  return handlerResult
                }
              }

              return target.apply(ctx, args)
            }
          });

          /* 挂载listenerProxy到自身，方便快速查找 */
          listener[listenerSymbol] = listenerProxy;

          /* 使用listenerProxy替代本来应该进行侦听的listener */
          arg[1] = listenerProxy;
        } catch (e) {
          // console.error('listenerProxy error:', e)
        }
      }
      t._addEventListener.apply(t, arg);
      t._listeners = t._listeners || {};
      t._listeners[type] = t._listeners[type] || [];
      const listenerObj = {
        target: t,
        type,
        listener,
        listenerProxy,
        options: arg[2],
        addTime: new Date().getTime()
      };
      t._listeners[type].push(listenerObj);

      /* 挂载到全局对象用于观测调试 */
      if (config.debug) {
        window._listenerList_[type] = window._listenerList_[type] || [];
        window._listenerList_[type].push(listenerObj);
      }
    } catch (e) {
      t._addEventListener.apply(t, arg); // <---------------------这一句出错
      // console.error(e)
    }
  };
```

**Comment by qiansen1386** [comment]
报错的 e 是
```
Cannot read property 'nodeName' of undefined
```
报错地点是这里：这里的`t`目前是`undefined`
```
if (config.proxyAll || proxyNodeType.includes(t.nodeName)) {
```
一开始的
```
 // hack addEventListener
EVENT.addEventListener = function() {
    const t = this; // <----- 这里的 this 是 undefined
    const arg = arguments;
    const type = arg[0];
    const listener = arg[1];

    if (!listener) {
        return false
    }
```

**Comment by qiansen1386** [comment]
我的环境环境

Item | Version
-- | --
Google Chrome | 90.0.4430.212&nbsp;(Official Build)&nbsp;(64-bit)&nbsp;(cohort: Stable)
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Windows&nbsp;10 OS Version 2009 (Build 19042.985)
JavaScript | V8&nbsp;9.0.257.29
User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
Extension | Tampermonkey 4.13
h5player | 3.3.2



我打开了很多视频分析，发现如果一个视频有分p，那么就没问题，一切功能正常。如果一个视频没有分P就不行。会不会是两种页面下，html 的结构有差异？

比如：
- https://www.bilibili.com/video/BV1ot411y7mU - 生效
- https://www.bilibili.com/video/BV1SW411r7j8 - 无效

同理，如果先把视频加入稍后观看，然后使用稍后观看功能看视频，功能就正常，这算是个 workaround 吧

**Comment by xxxily** [comment]
> 我的环境
> 
> Item	Version
> Google Chrome	90.0.4430.212 (Official Build) (64-bit) (cohort: Stable)
> Revision	e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
> OS	Windows 10 OS Version 2009 (Build 19042.985)
> JavaScript	V8 9.0.257.29
> User agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
> Extension	Tampermonkey 4.13
> h5player	3.3.2
> 我打开了很多视频分析，发现如果一个视频有分p，那么就没问题，一切功能正常。如果一个视频没有分P就不行。会不会是两种页面下，html 的结构有差异？
> 
> 比如：
> 
> * https://www.bilibili.com/video/BV1ot411y7mU - 生效
> * https://www.bilibili.com/video/BV1SW411r7j8 - 无效
> 
> 同理，如果先把视频加入稍后观看，然后使用稍后观看功能看视频，功能就正常，这算是个 workaround 吧
> 
> 不过，切P之后功能会失效，在此情境下刷新可以解决

我测试了倍速正常啊，只是弹幕的倍速不正常和倍速提示没显示出来，后续优化下

**Comment by qiansen1386** [comment]
真的很奇怪诶，我这重启之后也好了，但我觉得等下可能又会崩，只是复现原因还是没有抓住。我已经把所有的 tampermonkey 的 log 都打开了。
如果后续有问题的话应该能给你更好的反馈。万分感谢。

**Comment by xxxily** [comment]
> 真的很奇怪诶，我这重启之后也好了，但我觉得等下可能又会崩，只是复现原因还是没有抓住。我已经把所有的 tampermonkey 的 log 都打开了。
> 如果后续有问题的话应该能给你更好的反馈。万分感谢。

切换视频可以正常提示倍速了，我close issues先，欢迎有问题再反馈，或重开issues
