### ISSUE TITLE
[BUG]手机dandanzan.cc手势无效

### ISSUE THREAD

**Issue by liuxiawei** [xxxily/h5player#228]
1. **问题描述**
手机dandanzan.cc手势无效，使用的video标签，但是手势失效，双击视频上方任然可以全屏，但是其他手势失效

2. **出现上述问题的地址**
dandanzan.cc

3. **你使用的浏览器与浏览器版本信息**
iceraven（Firefox Nightly）

4. **其他附注信息**
鄙人认为可以考虑使用悬浮工具栏代替手势，手势有诸多不便

**Comment by xxxily** [comment]
该插件并不支持手势功能
