### ISSUE TITLE
[BUG] pornhub 30 sex f.forward does not working.

### ISSUE THREAD

**Issue by seriousgigi** [xxxily/h5player#229]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by qiansen1386** [comment]
Could you elaborate a bit what is not working, and how to reproduce? forward 1 frame?

Also which browser version are you using?

**Comment by seriousgigi** [comment]
sorry i wasnt using this browser for a time and didnt see your message. it
is "ctrl + right arrow" shortcut that not working in pornhub. when you do
this video jumps like 10 minutes at once. i am using opera.

东方孤思子 Paris·QianSen ***@***.***>, 19 May 2021 Çar, 14:32
tarihinde şunu yazdı:

**Comment by qiansen1386** [comment]
It's kinda funny that I have to watch some porn to check your issue, LOL. `ctrl+right key` is working on my side, no problem. 
Were you using incognito window, have you enabled tampormonkey/violentmonkey in incognito windows

**Comment by seriousgigi** [comment]
:D no, normal window.

东方孤思子 Paris·QianSen ***@***.***>, 29 May 2021 Cmt, 15:17
tarihinde şunu yazdı:

**Comment by qiansen1386** [comment]
It works for me.
