### ISSUE TITLE
音量可以设置为 5% 一跳吗

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [xxxily/h5player#23]
Ctrl 或 Shift 修饰后为1%

**Comment by freeleefly** [comment]
进到脚本 
`t.setVolume(0.01)`改成`t.setVolume(0.05)`
就可以了，自己动手。
不过更新以后，应该又会恢复回去，自己再改过。

**Comment by xxxily** [comment]
> 进到脚本
> `t.setVolume(0.01)`改成`t.setVolume(0.05)`
> 就可以了，自己动手。
> 不过更新以后，应该又会恢复回去，自己再改过。

1%确实不太合理，下个版本会增加音量步长幅度

**Comment by LakeishaKowalczyk** [comment]
@xxxily 
谢谢，顺便反馈两个相关小 BUG

直接改成 t.setVolume(0.05) 的话，有时候跳转会是 4%
bili 下调音量至静音后，再上调音量会无效，需要手动取消静音状态
调整音量时，自带的音量条不会伸缩，在刷新或播放下一个视频的时候，不能继承音量调整

不知道放在这里合不合适，要不要新开 issues

**Comment by Vstory** [comment]
> 1%确实不太合理，下个版本会增加音量步长幅度



每次调节就是10%，和手机上的音量分级一样，太难受了。
我只要它大一点点而已，就很难。
希望能自定义音量的每次调节分级，我个人喜欢1%的往上加，控制起来更加精准。
