### ISSUE TITLE
建议增加快捷键设置页面, 有选择的启用部分快捷键

### ISSUE THREAD

**Issue by letterk** [xxxily/h5player#231]
有些不常用, 容易误操作的快捷键想屏蔽掉

**Comment by aur3l14no** [comment]
你可以把相应的代码注释掉.... 作为临时解决方案

**Comment by onionycs** [comment]
> 

怎么注释？

**Comment by xxxily** [comment]
目前该问题已解决，如果还有问题，建议通过自定义配置解决：https://h5player.anzz.top/home/customConfiguration.html
