### ISSUE TITLE
[BUG] 在netflix中打开脚本会导致netflix播放中断

### ISSUE THREAD

**Issue by xiaotianxt** [xxxily/h5player#234]
1. **问题描述**

在netflix中使用您播放增强模板会导致netflix报错，错误码M7375，描述称“因为浏览器扩展导致”

![错误页面](https://user-images.githubusercontent.com/17041194/117797465-a5145d80-b282-11eb-9c5c-67dde995c9b5.png)

![错误详情介绍](https://user-images.githubusercontent.com/17041194/117797610-c9703a00-b282-11eb-9524-46ae024b6dad.png)

2. **出现上述问题的地址**
任意一个netflix播放链接，如[此链接](https://www.netflix.com/watch/70236428?trackId=200257859)

3. **你使用的浏览器与浏览器版本信息**
Google Chrome 90.0.4430.93, MacOS BigSur 11.3.1 (20E241), Macbook Air M1 chip

4. **其他附注信息**

**Comment by dxzy** [comment]
快進、退後、上(下)一帧大概都會觸發這個問題，

雖然我試著修改一下，諸如 

更改快进快退步长 skipStep 為10 沒有改善；

t.skipStep * 2 沒有改善，照下一幀的方式取消甚至不能前進後退依然會跳錯誤，

但不使用這些功能的話似乎能正常運作。

**Comment by sakumakenshin** [comment]
同样的问题，关闭插件正常播放

**Comment by axelburks** [comment]
目前仍有这个问题😭

**Comment by xxxily** [comment]
暂时已优化，不过没开netflix会员，没法测试是否优化成功

**Comment by axelburks** [comment]
测试了下还是有问题。。

**Comment by aunight** [comment]
到現在還是有問題
