### ISSUE TITLE
bilibili视频、以及其他视频，发现脚本对带有前进后退按键的鼠标，对它的前进后退键无效

### ISSUE THREAD

**Issue by lyjhyjyes** [xxxily/h5player#237]
1. <bilibili视频、以及其他视频，发现脚本对带有前进后退按键的鼠标，对它的前进后退键无效
我下载了视频，用potplayer播放却可以用快进后退键>

2. <https://www.bilibili.com/video/av19975155>

3. <chrome 90以及脚本，https://greasyfork.org/zh-CN/scripts/381682
版本3.3.1创建日期2019-04-11  11:17:41最近更新2020-09-03  23:01:45>

**Comment by qiansen1386** [comment]
倍速键也失效了，但是插件本身会有反馈，只是倍率不发生变化。观察chrome的console发现以下错误
```
HTML5 video player enhanced script.user.js:1475 Uncaught (in promise) TypeError: window.GM_getTab is not a function
```

**Comment by xxxily** [comment]
> 1. <bilibili视频、以及其他视频，发现脚本对带有前进后退按键的鼠标，对它的前进后退键无效
>    我下载了视频，用potplayer播放却可以用快进后退键>
> 2. https://www.bilibili.com/video/av19975155
> 3. <chrome 90以及脚本，https://greasyfork.org/zh-CN/scripts/381682
>    版本3.3.1创建日期2019-04-11  11:17:41最近更新2020-09-03  23:01:45>

自测正常，你更新最新版本再试下看看

**Comment by lyjhyjyes** [comment]
你理解错了。键盘左右键能快进，鼠标快进后退键无效，而我用potplayer播放器播放本地视频能用鼠标前进后退键。不太清楚两者的差别在哪

xxxily ***@***.***> 于2021年5月20日周四 下午2:37写道：

**Comment by qiansen1386** [comment]
@lyjhyjyes 确实感觉修复了。我测试了 Tampermonkey 4.12+Chrome 90.0.4430.212

目前可以用，前进后退加速倍速都有效。console 里 GM_tabs 不是函数的报错也没有了，你再试试。

**Comment by qiansen1386** [comment]
@xxxily 又失效了，但这次连报错也没有了。按键有反应但不起作用。
实现方式可能是这样，你先打开几个bilibili tab然后把浏览器关掉，再恢复？有什么办法调试么？

**Comment by lyjhyjyes** [comment]
我是win10 chrome 90.0.4430.85（正式版本） （64 位），油猴4.13，并不能鼠标前进后退键生效

东方孤思子 Paris·QianSen ***@***.***> 于2021年5月21日周五 下午9:30写道：
