### ISSUE TITLE
[BUG]百度网盘倍速功能普通用户无法使用

### ISSUE THREAD

**Issue by tangli159** [xxxily/h5player#238]
1. **问题描述**

看到大大已经修复了之前的倍速问题，但是现在只有VIP账号能够倍速，非VIP账号按快捷键无任何反应。
2. **出现上述问题的地址**

pan.baidu.com
3. **你使用的浏览器与浏览器版本信息**

百分浏览器 版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)
4. **其他附注信息**

**Comment by xxxily** [comment]
感谢反馈，将尽快将跟进修复

**Comment by xxxily** [comment]
问题已修复，但要注意：视频没进入播放前不要进行调速操作，否则会触发百度脚本的死循环，目前没法修复该问题，后续有时间再优化
