### ISSUE TITLE
关于倍速播放和网页全屏的一点小建议

### ISSUE THREAD

**Issue by FengTang2333** [xxxily/h5player#24]
您好!我是您开发的油猴插件的新用户,特别喜欢你们的插件!使用一段时间以后发现有些可以改进的地方,希望能够采纳!🙂
1)希望倍速播放能新增"0.25""0.75""1.25""1.75"这四个倍速
2)我曾经用过一个油猴插件叫"网页全屏",启用后在播放器外侧会有一个"网页全屏"和一个"画中画"的按钮,全屏和画中画以后会出现一个"还原"按钮,点击即可恢复.这个插件十分好用,但是和你们的插件不兼容😂.希望你的插件也可以做出这三个按钮,这样我就可以抛弃那个插件了🙂
最后,感谢您抽出宝贵时间阅读这份建议,希望使用你们插件的用户越来越多,谢谢 !)

**Comment by FengTang2333** [comment]
对了,就是还希望设置"ESC"键退出全屏,网页全屏和画中画🙂

**Comment by xxxily** [comment]
> 对了,就是还希望设置"ESC"键退出全屏,网页全屏和画中画🙂

后续会看情况逐步优化，感谢你的建议

**Comment by zhezh** [comment]
> > 对了,就是还希望设置"ESC"键退出全屏,网页全屏和画中画🙂
> 
> 后续会看情况逐步优化，感谢你的建议

附议, 一次10%的播放速度调节有点大了, 希望可以以5%的间隔进行调节.
我手动改了脚本中的 0.1 为 0.05, 但是似乎并没有用
```
/* 利用sessionStorage下的playbackRate进行设置 */
        if (window.sessionStorage.playbackRate && /(c|x|z|1|2|3|4)/.test(key)) {
          const curSpeed = Number(window.sessionStorage.playbackRate);
          const perSpeed = curSpeed - 0.05 >= 0 ? curSpeed - 0.05 : 0.1;
          const nextSpeed = curSpeed + 0.05 <= 4 ? curSpeed + 0.05 : 4;
          let targetSpeed = curSpeed;
```
