### ISSUE TITLE
希望可以适配中国大学MOOC

### ISSUE THREAD

**Issue by hywo-x** [xxxily/h5player#240]
目测这个也是用h5的，但是没有仔细研究过代码。

之前偶尔能用，不知道是脚本更新还是网站更新，现在已经完全无法使用了。

www.icourse163.org那个

**Comment by xxxily** [comment]
> 目测这个也是用h5的，但是没有仔细研究过代码。
> 
> 之前偶尔能用，不知道是脚本更新还是网站更新，现在已经完全无法使用了。
> 
> [www.icourse163.org那个](http://www.icourse163.org%E9%82%A3%E4%B8%AA)

已支持
