### ISSUE TITLE
b站直播回车全屏后无法切换清晰度和弹幕

### ISSUE THREAD

**Issue by rookiezq** [xxxily/h5player#241]
1. **问题描述**
如题，回车全屏后b站原来的控件全都无法使用，重新回车退出全屏后恢复
![image](https://user-images.githubusercontent.com/43901891/119113232-77d06800-ba57-11eb-8c51-3e59feb3128c.png)

**Comment by qiansen1386** [comment]
是 bug，用播放器自己的全屏就没问题。
这应该是b站播放器的问题，这个插件原本也不是看直播用的吧。
我觉得优先级没有那么紧迫，你就先暂时别用回车全屏就好了

**Comment by fangyuan99** [comment]
我更新到最新版后，用浏览器自带的播放器全屏也没用控件了

**Comment by xxxily** [comment]
该问题现在还会出现吗？我自测了好像没发现这个问题，如果还会出现，请再打开一下issues

**Comment by rookiezq** [comment]
还是有问题，好像是鼠标必须点一下播放框，点网页上其他部分没用，才能按enter全屏；而且全屏后点右下角的全屏按钮没反应
