### ISSUE TITLE
百度网盘的资料群里的视频没法用这个倍速播放哦 

### ISSUE THREAD

**Issue by 516913605** [xxxily/h5player#244]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by xxxily** [comment]
请提供个可测试的视频地址给我试下

**Comment by 516913605** [comment]
不知道你能不能打开这个网址
发现我用edge可以用，但是用Chrome却不能用
https://pan.baidu.com/mbox/streampage?from_uk=1005952871&msg_id=4005954249809653774&fs_id=692101041433588&to=123914758587786754&type=2&name=%E3%80%90%E5%BD%95%E6%92%AD%E8%AF%BE%E3%80%91%E8%AF%BE%E6%97%B68%EF%BC%9A%E5%9F%BA%E7%A1%80%EF%BC%88%E4%BA%8C%EF%BC%89%E4%BB%A3%E6%95%B002%E3%80%90%E5%85%AC%C2%B7%E4%BC%97%C2%B7%E5%8F%B7%EF%BC%9A%E8%80%83%C2%B7%E7%A0%94%C2%B7%E9%A2%98%C2%B7%E5%BA%93%20%E3%80%91%E5%85%8D%C2%B7%E8%B4%B9%C2%B7%E5%88%86%C2%B7%E4%BA%AB%E3%80%90%E5%85%AC%C2%B7%E4%BC%97%C2%B7%E5%8F%B7%EF%BC%9A%E9%A2%98%C2%B7%E5%BA%93%C2%B7%E7%BD%91%20%E3%80%91%E5%85%8D%C2%B7%E8%B4%B9%C2%B7%E5%88%86%C2%B7%E4%BA%AB.mp4&path=%2F%E3%80%9002%E3%80%9122%2B21%EF%BC%88%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%2B396%EF%BC%89%2F22%2B21%EF%BC%88%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%2B396%EF%BC%89%2F01%E3%80%90%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%E3%80%91%2F%E2%99%A522%E3%80%90%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%E3%80%91%E5%85%A8%E7%A8%8B%EF%BC%88%E6%8A%BC%E9%A2%98%2B%E5%A4%8D%E8%AF%95%EF%BC%89%E2%99%A5%2F02.%2022%E3%80%90%E7%AE%A1%E7%BB%BC%E3%80%91%E2%80%94%E7%AC%AC%E4%BA%8C%E7%89%88%E6%9C%AC%E2%97%8F%2F2022%E8%80%83%E7%A0%94%E3%80%90%E9%91%AB%E5%85%A8%E3%80%91%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%2F%E9%9F%A6%E6%9E%97%E8%AF%BE%E5%A0%82%E7%89%88%E6%9C%AC%2F%E6%95%B0%E5%AD%A6%2F%E5%9F%BA%E7%A1%80%E7%8F%AD%2F%E3%80%90%E5%BD%95%E6%92%AD%E8%AF%BE%E3%80%91%E8%AF%BE%E6%97%B68%EF%BC%9A%E5%9F%BA%E7%A1%80%EF%BC%88%E4%BA%8C%EF%BC%89%E4%BB%A3%E6%95%B002%E3%80%90%E5%85%AC%C2%B7%E4%BC%97%C2%B7%E5%8F%B7%EF%BC%9A%E8%80%83%C2%B7%E7%A0%94%C2%B7%E9%A2%98%C2%B7%E5%BA%93%20%E3%80%91%E5%85%8D%C2%B7%E8%B4%B9%C2%B7%E5%88%86%C2%B7%E4%BA%AB%E3%80%90%E5%85%AC%C2%B7%E4%BC%97%C2%B7%E5%8F%B7%EF%BC%9A%E9%A2%98%C2%B7%E5%BA%93%C2%B7%E7%BD%91%20%E3%80%91%E5%85%8D%C2%B7%E8%B4%B9%C2%B7%E5%88%86%C2%B7%E4%BA%AB.mp4&md5=bbc460d2ao3e738ae83f6c2ce1df9db7

**Comment by xxxily** [comment]
> 不知道你能不能打开这个网址
> 发现我用edge可以用，但是用Chrome却不能用
> https://pan.baidu.com/mbox/streampage?from_uk=1005952871&msg_id=4005954249809653774&fs_id=692101041433588&to=123914758587786754&type=2&name=%E3%80%90%E5%BD%95%E6%92%AD%E8%AF%BE%E3%80%91%E8%AF%BE%E6%97%B68%EF%BC%9A%E5%9F%BA%E7%A1%80%EF%BC%88%E4%BA%8C%EF%BC%89%E4%BB%A3%E6%95%B002%E3%80%90%E5%85%AC%C2%B7%E4%BC%97%C2%B7%E5%8F%B7%EF%BC%9A%E8%80%83%C2%B7%E7%A0%94%C2%B7%E9%A2%98%C2%B7%E5%BA%93%20%E3%80%91%E5%85%8D%C2%B7%E8%B4%B9%C2%B7%E5%88%86%C2%B7%E4%BA%AB%E3%80%90%E5%85%AC%C2%B7%E4%BC%97%C2%B7%E5%8F%B7%EF%BC%9A%E9%A2%98%C2%B7%E5%BA%93%C2%B7%E7%BD%91%20%E3%80%91%E5%85%8D%C2%B7%E8%B4%B9%C2%B7%E5%88%86%C2%B7%E4%BA%AB.mp4&path=%2F%E3%80%9002%E3%80%9122%2B21%EF%BC%88%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%2B396%EF%BC%89%2F22%2B21%EF%BC%88%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%2B396%EF%BC%89%2F01%E3%80%90%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%E3%80%91%2F%E2%99%A522%E3%80%90%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%E3%80%91%E5%85%A8%E7%A8%8B%EF%BC%88%E6%8A%BC%E9%A2%98%2B%E5%A4%8D%E8%AF%95%EF%BC%89%E2%99%A5%2F02.%2022%E3%80%90%E7%AE%A1%E7%BB%BC%E3%80%91%E2%80%94%E7%AC%AC%E4%BA%8C%E7%89%88%E6%9C%AC%E2%97%8F%2F2022%E8%80%83%E7%A0%94%E3%80%90%E9%91%AB%E5%85%A8%E3%80%91%E7%AE%A1%E7%90%86%E7%B1%BB%E8%81%94%E8%80%83%2F%E9%9F%A6%E6%9E%97%E8%AF%BE%E5%A0%82%E7%89%88%E6%9C%AC%2F%E6%95%B0%E5%AD%A6%2F%E5%9F%BA%E7%A1%80%E7%8F%AD%2F%E3%80%90%E5%BD%95%E6%92%AD%E8%AF%BE%E3%80%91%E8%AF%BE%E6%97%B68%EF%BC%9A%E5%9F%BA%E7%A1%80%EF%BC%88%E4%BA%8C%EF%BC%89%E4%BB%A3%E6%95%B002%E3%80%90%E5%85%AC%C2%B7%E4%BC%97%C2%B7%E5%8F%B7%EF%BC%9A%E8%80%83%C2%B7%E7%A0%94%C2%B7%E9%A2%98%C2%B7%E5%BA%93%20%E3%80%91%E5%85%8D%C2%B7%E8%B4%B9%C2%B7%E5%88%86%C2%B7%E4%BA%AB%E3%80%90%E5%85%AC%C2%B7%E4%BC%97%C2%B7%E5%8F%B7%EF%BC%9A%E9%A2%98%C2%B7%E5%BA%93%C2%B7%E7%BD%91%20%E3%80%91%E5%85%8D%C2%B7%E8%B4%B9%C2%B7%E5%88%86%C2%B7%E4%BA%AB.mp4&md5=bbc460d2ao3e738ae83f6c2ce1df9db7

新版测试正常，如有问题欢迎再次反馈
