### ISSUE TITLE
[BUG] 升级到 3.3.3 后部分网页无法加载

### ISSUE THREAD

**Issue by stultulo** [xxxily/h5player#247]
1. **问题描述**
升级到 3.3.3 版本后，部分网页无法加载，关闭脚本后恢复访问

2. **出现上述问题的地址**
例如，https://pubs.rsc.org/en/content/articlelanding/2021/sc/d1sc01881g

3. **你使用的浏览器与浏览器版本信息**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

4. **其他附注信息**
暂无

**Comment by xxxily** [comment]
> 1. **问题描述**
>    升级到 3.3.3 版本后，部分网页无法加载，关闭脚本后恢复访问
> 2. **出现上述问题的地址**
>    例如，https://pubs.rsc.org/en/content/articlelanding/2021/sc/d1sc01881g
> 3. **你使用的浏览器与浏览器版本信息**
>    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
> 4. **其他附注信息**
>    暂无

这周内会更新一版，解决该问题

**Comment by xxxily** [comment]
已解决
