### ISSUE TITLE
[BUG]该插件使百度文库网页异常

### ISSUE THREAD

**Issue by helloyujiaxu** [xxxily/h5player#248]
1. **很抱歉在这里提这个完全用不到的网站，但是我还是想提下这个issue，在使用该脚本时打开百度文库会出现一些框架被误拦截导致一些按钮点不了导致的无法展开完整文档**

2. **wenku.baidu.com/***

3. **小白浏览器，谷歌80内核**

4. **使用的是油猴。**

**Comment by xxxily** [comment]
> 1. **很抱歉在这里提这个完全用不到的网站，但是我还是想提下这个issue，在使用该脚本时打开百度文库会出现一些框架被误拦截导致一些按钮点不了导致的无法展开完整文档**
> 
> 1. **wenku.baidu.com/***
> 
> 1. **小白浏览器，谷歌80内核**
> 
> 1. **使用的是油猴。**

脚本已更新
