### ISSUE TITLE
百度网盘倍速不行了，大神请尽快修复[错误]

### ISSUE THREAD

**Issue by z18297913118** [xxxily/h5player#250]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by z18297913118** [comment]
百度网盘倍速一直是1，麻烦大哥们尽快修复，感谢

**Comment by xxxily** [comment]
> 百度网盘倍速一直是1，麻烦大哥们尽快修复，感谢

已修复，更新试下

**Comment by z18297913118** [comment]
> > 百度网盘倍速一直是1，麻烦大哥们尽快修复，感谢
> 
> 已修复，更新试下

非常感谢大哥，辛苦
