### ISSUE TITLE
[BUG]无法删除油猴存储数据

### ISSUE THREAD

**Issue by lyjhyjyes** [xxxily/h5player#254]
1. **问题描述**
无法删除该html5脚本的存储数据，reload无法重置，删除脚本再安装，数据还在。明明开了脚本，Ctrl+\开了关了，刷新，无法启用enter全屏。怀疑存储数据错误，不知如何删除

2. **出现上述问题的地址**
https://www.bilibili.com/video/av540201382?p=1&t=347

3. **你使用的浏览器与浏览器版本信息**
chrome版本 90.0.4430.85（正式版本） （64 位）
脚本3.3.7
油猴4.13

4. **其他附注信息**
存储数据如下
{
    "_allowRestorePlayProgress_api.nixingle.com": "true",
    "_allowRestorePlayProgress_g.ieeod0.com": "true",
    "_allowRestorePlayProgress_www.pufei8.com": "false",
    "_global_id_": 71497,
    "globalKeydownEvent": {
        "data": {
            "isTrusted": true,
            "key": "Shift",
            "code": "ShiftLeft",
            "location": 1,
            "ctrlKey": false,
            "shiftKey": true,
            "altKey": false,
            "metaKey": false,
            "repeat": false,
            "isComposing": false,
            "charCode": 0,
            "keyCode": 16,
            "DOM_KEY_LOCATION_STANDARD": 0,
            "DOM_KEY_LOCATION_LEFT": 1,
            "DOM_KEY_LOCATION_RIGHT": 2,
            "DOM_KEY_LOCATION_NUMPAD": 3,
            "detail": 0,
            "which": 16,
            "type": "keydown",
            "eventPhase": 1,
            "bubbles": true,
            "cancelable": true,
            "defaultPrevented": false,
            "composed": true,
            "timeStamp": 211633.27999971807,
            "returnValue": true,
            "cancelBubble": false,
            "NONE": 0,
            "CAPTURING_PHASE": 1,
            "AT_TARGET": 2,
            "BUBBLING_PHASE": 3
        },
        "tabId": 71486,
        "title": "消息",
        "referrer": {
            "ancestorOrigins": {
                "0": "https://www.bilibili.com",
                "length": 1
            },
            "href": "https://message.bilibili.com/pages/nav/index_new_pc_sync",
            "origin": "https://message.bilibili.com",
            "protocol": "https:",
            "host": "message.bilibili.com",
            "hostname": "message.bilibili.com",
            "port": "",
            "pathname": "/pages/nav/index_new_pc_sync",
            "search": "",
            "hash": ""
        },
        "updateTime": 1622690829256
    },
    "globalPictureInPictureInfo": {
        "data": {
            "hasGlobalPictureInPictureElement": true
        },
        "tabId": 70546,
        "title": "微博视频",
        "referrer": {
            "ancestorOrigins": {
                "length": 0
            },
            "href": "https://video.h5.weibo.cn/1034:4639648685948935/4639669441265973?sudaref=www.lanqiudi.com&display=0&retcode=6102",
            "origin": "https://video.h5.weibo.cn",
            "protocol": "https:",
            "host": "video.h5.weibo.cn",
            "hostname": "video.h5.weibo.cn",
            "port": "",
            "pathname": "/1034:4639648685948935/4639669441265973",
            "search": "?sudaref=www.lanqiudi.com&display=0&retcode=6102",
            "hash": ""
        },
        "updateTime": 1621763175152
    }
}

**Comment by xxxily** [comment]
需要通过 GM_deleteValue 才能删除，我后头加个重置数据的操作吧

**Comment by xxxily** [comment]
> 1. **问题描述**
>    无法删除该html5脚本的存储数据，reload无法重置，删除脚本再安装，数据还在。明明开了脚本，Ctrl+\开了关了，刷新，无法启用enter全屏。怀疑存储数据错误，不知如何删除
> 2. **出现上述问题的地址**
>    https://www.bilibili.com/video/av540201382?p=1&t=347
> 3. **你使用的浏览器与浏览器版本信息**
>    chrome版本 90.0.4430.85（正式版本） （64 位）
>    脚本3.3.7
>    油猴4.13
> 4. **其他附注信息**
>    存储数据如下
>    {
>    "_allowRestorePlayProgress_api.nixingle.com": "true",
>    "_allowRestorePlayProgress_g.ieeod0.com": "true",
>    "_allowRestorePlayProgress_[www.pufei8.com](http://www.pufei8.com)": "false",
>    "_global_id_": 71497,
>    "globalKeydownEvent": {
>    "data": {
>    "isTrusted": true,
>    "key": "Shift",
>    "code": "ShiftLeft",
>    "location": 1,
>    "ctrlKey": false,
>    "shiftKey": true,
>    "altKey": false,
>    "metaKey": false,
>    "repeat": false,
>    "isComposing": false,
>    "charCode": 0,
>    "keyCode": 16,
>    "DOM_KEY_LOCATION_STANDARD": 0,
>    "DOM_KEY_LOCATION_LEFT": 1,
>    "DOM_KEY_LOCATION_RIGHT": 2,
>    "DOM_KEY_LOCATION_NUMPAD": 3,
>    "detail": 0,
>    "which": 16,
>    "type": "keydown",
>    "eventPhase": 1,
>    "bubbles": true,
>    "cancelable": true,
>    "defaultPrevented": false,
>    "composed": true,
>    "timeStamp": 211633.27999971807,
>    "returnValue": true,
>    "cancelBubble": false,
>    "NONE": 0,
>    "CAPTURING_PHASE": 1,
>    "AT_TARGET": 2,
>    "BUBBLING_PHASE": 3
>    },
>    "tabId": 71486,
>    "title": "消息",
>    "referrer": {
>    "ancestorOrigins": {
>    "0": "https://www.bilibili.com",
>    "length": 1
>    },
>    "href": "https://message.bilibili.com/pages/nav/index_new_pc_sync",
>    "origin": "https://message.bilibili.com",
>    "protocol": "https:",
>    "host": "message.bilibili.com",
>    "hostname": "message.bilibili.com",
>    "port": "",
>    "pathname": "/pages/nav/index_new_pc_sync",
>    "search": "",
>    "hash": ""
>    },
>    "updateTime": 1622690829256
>    },
>    "globalPictureInPictureInfo": {
>    "data": {
>    "hasGlobalPictureInPictureElement": true
>    },
>    "tabId": 70546,
>    "title": "微博视频",
>    "referrer": {
>    "ancestorOrigins": {
>    "length": 0
>    },
>    "href": "https://video.h5.weibo.cn/1034:4639648685948935/4639669441265973?sudaref=www.lanqiudi.com&display=0&retcode=6102",
>    "origin": "https://video.h5.weibo.cn",
>    "protocol": "https:",
>    "host": "video.h5.weibo.cn",
>    "hostname": "video.h5.weibo.cn",
>    "port": "",
>    "pathname": "/1034:4639648685948935/4639669441265973",
>    "search": "?sudaref=www.lanqiudi.com&display=0&retcode=6102",
>    "hash": ""
>    },
>    "updateTime": 1621763175152
>    }
>    }

全屏跟这里的数据无关的，这里的数据只是用来控制跨域/跨tab触发操作

**Comment by lyjhyjyes** [comment]
> > 1. **问题描述**
> >    无法删除该html5脚本的存储数据，reload无法重置，删除脚本再安装，数据还在。明明开了脚本，Ctrl+\开了关了，刷新，无法启用enter全屏。怀疑存储数据错误，不知如何删除
> > 2. **出现上述问题的地址**
> >    https://www.bilibili.com/video/av540201382?p=1&t=347
> > 3. **你使用的浏览器与浏览器版本信息**
> >    chrome版本 90.0.4430.85（正式版本） （64 位）
> >    脚本3.3.7
> >    油猴4.13
> > 4. **其他附注信息**
> >    存储数据如下
> >    {
> >    "_allowRestorePlayProgress_api.nixingle.com": "true",
> >    "_allowRestorePlayProgress_g.ieeod0.com": "true",
> >    "_allowRestorePlayProgress_[www.pufei8.com](http://www.pufei8.com)": "false",
> >    "_global_id_": 71497,
> >    "globalKeydownEvent": {
> >    "data": {
> >    "isTrusted": true,
> >    "key": "Shift",
> >    "code": "ShiftLeft",
> >    "location": 1,
> >    "ctrlKey": false,
> >    "shiftKey": true,
> >    "altKey": false,
> >    "metaKey": false,
> >    "repeat": false,
> >    "isComposing": false,
> >    "charCode": 0,
> >    "keyCode": 16,
> >    "DOM_KEY_LOCATION_STANDARD": 0,
> >    "DOM_KEY_LOCATION_LEFT": 1,
> >    "DOM_KEY_LOCATION_RIGHT": 2,
> >    "DOM_KEY_LOCATION_NUMPAD": 3,
> >    "detail": 0,
> >    "which": 16,
> >    "type": "keydown",
> >    "eventPhase": 1,
> >    "bubbles": true,
> >    "cancelable": true,
> >    "defaultPrevented": false,
> >    "composed": true,
> >    "timeStamp": 211633.27999971807,
> >    "returnValue": true,
> >    "cancelBubble": false,
> >    "NONE": 0,
> >    "CAPTURING_PHASE": 1,
> >    "AT_TARGET": 2,
> >    "BUBBLING_PHASE": 3
> >    },
> >    "tabId": 71486,
> >    "title": "消息",
> >    "referrer": {
> >    "ancestorOrigins": {
> >    "0": "https://www.bilibili.com",
> >    "length": 1
> >    },
> >    "href": "https://message.bilibili.com/pages/nav/index_new_pc_sync",
> >    "origin": "https://message.bilibili.com",
> >    "protocol": "https:",
> >    "host": "message.bilibili.com",
> >    "hostname": "message.bilibili.com",
> >    "port": "",
> >    "pathname": "/pages/nav/index_new_pc_sync",
> >    "search": "",
> >    "hash": ""
> >    },
> >    "updateTime": 1622690829256
> >    },
> >    "globalPictureInPictureInfo": {
> >    "data": {
> >    "hasGlobalPictureInPictureElement": true
> >    },
> >    "tabId": 70546,
> >    "title": "微博视频",
> >    "referrer": {
> >    "ancestorOrigins": {
> >    "length": 0
> >    },
> >    "href": "https://video.h5.weibo.cn/1034:4639648685948935/4639669441265973?sudaref=www.lanqiudi.com&display=0&retcode=6102",
> >    "origin": "https://video.h5.weibo.cn",
> >    "protocol": "https:",
> >    "host": "video.h5.weibo.cn",
> >    "hostname": "video.h5.weibo.cn",
> >    "port": "",
> >    "pathname": "/1034:4639648685948935/4639669441265973",
> >    "search": "?sudaref=www.lanqiudi.com&display=0&retcode=6102",
> >    "hash": ""
> >    },
> >    "updateTime": 1621763175152
> >    }
> >    }
> 
> 全屏跟这里的数据无关的，这里的数据只是用来控制跨域/跨tab触发操作

明白。https://bbs.hupu.com/43352488.html虎扑视频能全屏，难道b站更新了，导致脚本不能用？
