### ISSUE TITLE
[BUG] 0603最近youtube上无法使用倍速播放了，在bilibili上可以使用

### ISSUE THREAD

**Issue by thinkido** [xxxily/h5player#255]
1. **问题描述**
youtube上面的倍速已经失效，

2. **出现上述问题的地址**
 [《公司绝不会告诉你的50大秘密》帮助员工及雇主更好地看清彼此 - YouTube](https://www.youtube.com/watch?v=2H5WikTbrGQ&list=UU9GfzQV-6U_p3eyf_8bew_A&index=219&ab_channel=%E7%B1%B3%E5%A8%85%E8%A6%81%E5%A5%BD%E5%A5%BD%E8%AF%BB%E4%B9%A6) 

3. **你使用的浏览器与浏览器版本信息**
chrome 版本 87.0.4244.0（正式版本）

**Comment by xxxily** [comment]
> 1. **问题描述**
>    youtube上面的倍速已经失效，
> 2. **出现上述问题的地址**
>    [《公司绝不会告诉你的50大秘密》帮助员工及雇主更好地看清彼此 - YouTube](https://www.youtube.com/watch?v=2H5WikTbrGQ&list=UU9GfzQV-6U_p3eyf_8bew_A&index=219&ab_channel=%E7%B1%B3%E5%A8%85%E8%A6%81%E5%A5%BD%E5%A5%BD%E8%AF%BB%E4%B9%A6)
> 3. **你使用的浏览器与浏览器版本信息**
>    chrome 版本 87.0.4244.0（正式版本）

测试了能用，建议你删除重装下试试，或者看下控制台报了什么错误
