### ISSUE TITLE
视频自动播放的问题

### ISSUE THREAD

**Issue by GZ-Juice** [xxxily/h5player#257]
1. **问题描述**
打开内嵌bilibili视频的网页，所有的视频会自动播放，能否修改成只有点击播放才播放视频？

2. **出现上述问题的地址**
https://sspai.com/post/67053

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge
版本 91.0.864.41 (官方内部版本) (64 位)

4. **其他附注信息**
B站也有这种问题，一次打开多个视频页面，按Ctrl tab切换时会直接播放切到的视频

**Comment by lbk33333** [comment]
是的是的，更新了脚本之后，会自动播放，很难受

**Comment by xxxily** [comment]
> 1. **问题描述**
>    打开内嵌bilibili视频的网页，所有的视频会自动播放，能否修改成只有点击播放才播放视频？
> 2. **出现上述问题的地址**
>    https://sspai.com/post/67053
> 3. **你使用的浏览器与浏览器版本信息**
>    Microsoft Edge
>    版本 91.0.864.41 (官方内部版本) (64 位)
> 4. **其他附注信息**
>    B站也有这种问题，一次打开多个视频页面，按Ctrl tab切换时会直接播放切到的视频

已解决https://sspai.com/post/67053下自动播放问题，已增加关闭自动播放按钮

**Comment by xxxily** [comment]
> 是的是的，更新了脚本之后，会自动播放，很难受

已增加关闭自动播放按钮

**Comment by GZ-Juice** [comment]
> > 1. **问题描述**
> >    打开内嵌bilibili视频的网页，所有的视频会自动播放，能否修改成只有点击播放才播放视频？
> > 2. **出现上述问题的地址**
> >    https://sspai.com/post/67053
> > 3. **你使用的浏览器与浏览器版本信息**
> >    Microsoft Edge
> >    版本 91.0.864.41 (官方内部版本) (64 位)
> > 4. **其他附注信息**
> >    B站也有这种问题，一次打开多个视频页面，按Ctrl tab切换时会直接播放切到的视频
> 
> 已解决[https://sspai.com/post/67053下自动播放问题，已增加关闭自动播放按钮](https://sspai.com/post/67053%E4%B8%8B%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE%E9%97%AE%E9%A2%98%EF%BC%8C%E5%B7%B2%E5%A2%9E%E5%8A%A0%E5%85%B3%E9%97%AD%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE%E6%8C%89%E9%92%AE)

感谢大佬~

> > 1. **问题描述**
> >    打开内嵌bilibili视频的网页，所有的视频会自动播放，能否修改成只有点击播放才播放视频？
> > 2. **出现上述问题的地址**
> >    https://sspai.com/post/67053
> > 3. **你使用的浏览器与浏览器版本信息**
> >    Microsoft Edge
> >    版本 91.0.864.41 (官方内部版本) (64 位)
> > 4. **其他附注信息**
> >    B站也有这种问题，一次打开多个视频页面，按Ctrl tab切换时会直接播放切到的视频
> 
> 已解决[https://sspai.com/post/67053下自动播放问题，已增加关闭自动播放按钮](https://sspai.com/post/67053%E4%B8%8B%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE%E9%97%AE%E9%A2%98%EF%BC%8C%E5%B7%B2%E5%A2%9E%E5%8A%A0%E5%85%B3%E9%97%AD%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE%E6%8C%89%E9%92%AE)

OK了！感谢大佬~

**Comment by MC-dusk** [comment]
> > 是的是的，更新了脚本之后，会自动播放，很难受
> 
> 已增加关闭自动播放按钮

请问如果点击了`关闭自动播放`按钮，之后又想恢复自动播放该怎么办呢？

另外B站视频如果从历史记录进入带有时间标记（比如https://www.bilibili.com/video/av9193145?t=94&p=1 ），仍然会自动播放（也就是禁止无效），请问这个能修复吗？
