### ISSUE TITLE
[BUG]从3.3.7版本开始，浏览器自带的全屏播放器不能使用控件了

### ISSUE THREAD

**Issue by fangyuan99** [xxxily/h5player#258]
1. **问题描述**
如题，从**3.3.7版本**开始，浏览器自带的全屏播放器不能使用控件了
![image](https://user-images.githubusercontent.com/62874116/120927625-11fd0500-c714-11eb-848b-3f2eb6848a3c.png)
回退至**3.3.6版本**正常
![image](https://i.vgy.me/PPpIUU.png)

2. **出现上述问题的地址**
任意使用浏览器自带播放器的页面

3. **你使用的浏览器与浏览器版本信息**
使用edge和Chrome测试都一样

**Comment by xxxily** [comment]
具体的网址是什么？是所有视频都不支持，还是某些网站不支持？

**Comment by fangyuan99** [comment]
就是任意使用浏览器自带的播放器网站都不支持（比如后缀为.mp4的网站），如果网站有本身的播放器不影响

**Comment by xxxily** [comment]
> 就是任意使用浏览器自带的播放器网站都不支持（比如后缀为.mp4的网站），如果网站有本身的播放器不影响

我看的都正常啊，你把插件关了，是否能正常显示出来？

**Comment by fangyuan99** [comment]
我测试的网站是要登陆账号的，看看能不能留个联系方式私聊一下

**Comment by fangyuan99** [comment]
具体也不知道原因，我猜测可能是按了全屏也没有进到播放器的环境，所以没用显示控件。但是用3.3.6版本的是没有任何问题的

**Comment by xxxily** [comment]
> 具体也不知道原因，我猜测可能是按了全屏也没有进到播放器的环境，所以没用显示控件。但是用3.3.6版本的是没有任何问题的

3.3.7调整了全屏的计算方式，但并没修改右键，非全屏模式下是否可以调取到自带的控件按钮？如果非全屏下不行，那全屏下应该也是不行的

**Comment by fangyuan99** [comment]
之前的版本是非全屏不能，全屏能，升级后全屏也不能了

**Comment by xxxily** [comment]
> 之前的版本是非全屏不能，全屏能，升级后全屏也不能了

那就是了，之前是对video标签进行全屏，现在是对其父级标签进行全屏，因为只对video标签全屏很多时候会导致自定义的工具栏被遮挡

**Comment by fangyuan99** [comment]
确实，这样的话这两个问题就不太好兼容了，那我自己用旧版得了
