### ISSUE TITLE
[BUG]爱奇艺空格键失效

### ISSUE THREAD

**Issue by nicduke** [xxxily/h5player#262]
1. **问题描述**
播放视频时无法用空格键暂停和继续播放

2. **出现上述问题的地址**
https://www.iqiyi.com/

3. **你使用的浏览器与浏览器版本信息**
360极速浏览器13.0.2250

4. **其他附注信息**
插件版本3.3.9

**Comment by xxxily** [comment]
> 1. **问题描述**
>    播放视频时无法用空格键暂停和继续播放
> 2. **出现上述问题的地址**
>    https://www.iqiyi.com/
> 3. **你使用的浏览器与浏览器版本信息**
>    360极速浏览器13.0.2250
> 4. **其他附注信息**
>    插件版本3.3.9

测试正常，看下是不是跟其它插件冲突了？
