### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ben-md5** [xxxily/h5player#264]
1. **问题描述**
播放哔哩哔哩番剧时，需要双击才能暂停

2. **出现上述问题的地址**
https://www.bilibili.com/bangumi/play/ep31387?from=search&seid=2283416488515963068
3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge 91.0.864.59
4. **其他附注信息**
于此同时没有开启与哔哩哔哩有关的脚本，试过重新安装

**Comment by xxxily** [comment]
> 1. **问题描述**
>    播放哔哩哔哩番剧时，需要双击才能暂停
> 2. **出现上述问题的地址**
>    https://www.bilibili.com/bangumi/play/ep31387?from=search&seid=2283416488515963068
> 3. **你使用的浏览器与浏览器版本信息**
>    Microsoft Edge 91.0.864.59
> 4. **其他附注信息**
>    于此同时没有开启与哔哩哔哩有关的脚本，试过重新安装

估计是和其它插件冲突了吧，我播放正常
