### ISSUE TITLE
【建议】网页声音可以增大到超过100%么？

### ISSUE THREAD

**Issue by tangli159** [xxxily/h5player#265]
1. **问题描述**

百度网盘部分视频的声音太小，开到最大也勉强可以听见，但是看了下好像没有继续增加音量超过100%的功能

2. **出现上述问题的地址**

https://pan.baidu.com/mbox/

3. **你使用的浏览器与浏览器版本信息**

百分浏览器版本Cent Browser 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198) 

4. **其他附注信息**

**Comment by JAGulin** [comment]
You can try this script and let us know if it works for you.
https://greasyfork.org/en/scripts/389804-boost-volume

For chromium there are also several extensions available.
https://chrome.google.com/webstore/search/volume?hl=en&_category=extensions

**Comment by tangli159** [comment]
> You can try this script and let us know if it works for you.
> https://greasyfork.org/en/scripts/389804-boost-volume
> 
> For chromium there are also several extensions available.
> https://chrome.google.com/webstore/search/volume?hl=en&_category=extensions

Thanks!It works.
