### ISSUE TITLE
[BUG]中国大学mooc需要科学上网才能使用此插件的功能

### ISSUE THREAD

**Issue by weiSENshu** [xxxily/h5player#268]
1. **问题描述**
中国大学mooc使用快捷键倍速等操作，必须使用科学上网才生效，普通网络下加载视频无法使用。
科学上网时
![image](https://user-images.githubusercontent.com/62413717/124120456-62af1600-daa6-11eb-9adc-9f3bab46393a.png)
普通网络下
![屏幕截图 2021-07-01 195821](https://user-images.githubusercontent.com/62413717/124121014-f8e33c00-daa6-11eb-986c-cee7b0d33f95.png)

2. **出现上述问题的地址**
https://www.icourse163.org/

3. **你使用的浏览器与浏览器版本信息**
Google Chrome
版本：91.0.4472.106

4. **其他附注信息**

**Comment by xuexilaide** [comment]
可以用 网页限制解除这个插件  我以前也是这样，后来两个插件一起用就没有这些了

**Comment by weiSENshu** [comment]
> 可以用网页关闭插件我以前也是这样，结果两个这个插件一起用就没有这些了

![image](https://user-images.githubusercontent.com/62413717/124856578-5adafe80-dfdd-11eb-9088-9a9cef6df8cc.png)
好像还不行哈哈

**Comment by weiSENshu** [comment]
> 可以用 网页限制解除这个插件 我以前也是这样，后来两个插件一起用就没有这些了

![image](https://user-images.githubusercontent.com/62413717/124857488-fa4cc100-dfde-11eb-9420-7f2c44d49a4d.png)
这个版本也不行

**Comment by MC-dusk** [comment]
github被樯的问题，和脚本无关
