### ISSUE TITLE
[BUG]本插件对哔哩哔哩番剧播放器失效

### ISSUE THREAD

**Issue by Ben-md5** [xxxily/h5player#269]
1. **问题描述**
如题，没有同时开任何插件，快捷键失效

2. **出现上述问题的地址**
https://www.bilibili.com/bangumi/play/ss1719/

3. **你使用的浏览器与浏览器版本信息**
edge  91.0.864.64

4. **其他附注信息**

**Comment by Rheinmetallskorpion** [comment]
现已对 bilibili 所有视频失效😔

**Comment by jamyxe** [comment]
同样的问题
