### ISSUE TITLE
能不能在视频全屏的时候，在视频底下加一个进度条。或者显示 播放时间/剩余时间 也行。感谢！

### ISSUE THREAD

**Issue by rain298** [xxxily/h5player#274]
能不能在视频全屏的时候，在视频底下加一个进度条。或者显示 播放时间/剩余时间 也行。感谢！

**Comment by JAGulin** [comment]
I don't think a progress bar for full-screen is a much requested feature, so it may not get priority. Possibly it could be a separate script just for this.
It would probably need to be tailored to each site. Which sites do you need it for? Youtube and some other sites seems to have the progress bar show when you move the mouse.

---
英文機器翻譯：
我不認為全屏的進度條是一個非常需要的功能，所以它可能沒有優先級。 可能它可以是一個單獨的腳本。
它可能需要針對每個站點進行定制。 哪些網站需要它？ Youtube 和其他一些網站似乎在您移動鼠標時顯示進度條。
---

**Comment by rain298** [comment]
这个情况好像确实是个例，大部分网站上没问题，在有些个别视频网站上，按Enter或shift+Enter进入全屏后，移动鼠标就看不到原来的进度条和标题了，就好像卡住了一样，比如阿里云盘里自己上传的视频。我觉得可能是阿里云盘的问题，估计他们以后更新就好了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月21日(星期三) 中午1:42
收件人: ***@***.***&gt;; 
抄送: "┍ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xxxily/h5player] 能不能在视频全屏的时候，在视频底下加一个进度条。或者显示 播放时间/剩余时间 也行。感谢！ (#274)





 
I don't think a progress bar for full-screen is a much requested feature, so it may not get priority. Possibly it could be a separate script just for this.
 It would probably need to be tailored to each site. Which sites do you need it for? Youtube and some other sites seems to have the progress bar show when you move the mouse.
 
 
英文機器翻譯：
 我不認為全屏的進度條是一個非常需要的功能，所以它可能沒有優先級。 可能它可以是一個單獨的腳本。
 它可能需要針對每個站點進行定制。 哪些網站需要它？ Youtube 和其他一些網站似乎在您移動鼠標時顯示進度條。
 
—
‎您收到此消息是因为您编写了该线程。‎
‎直接回复此电子邮件，‎‎在 GitHub 上查看，‎‎或‎‎取消订阅‎‎。‎

**Comment by rain298** [comment]
既然是个例，就不用专门更新了，我之前还以为是Bug，不好意思！

**Comment by JAGulin** [comment]
If you can share a link it could be investigated. I tried these videos and it worked for Enter, but for Shift-Enter (in Edge browser) the video was bigger than my screen and the progress bar wasn't accessible.
https://www.alibabacloud.com/videos

**Comment by rain298** [comment]
不是那个阿里云。。是这个阿里网盘地址，https://www.aliyundrive.com/，不过既然是个例，那就不用investigated了，实际使用也不影响。刚开始因为没有试其他视频网站，还以为是个Bug，现在看来不是，把我这个issues忽略了吧！感谢大佬的热心解答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月21日(星期三) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: "┍ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xxxily/h5player] 能不能在视频全屏的时候，在视频底下加一个进度条。或者显示 播放时间/剩余时间 也行。感谢！ (#274)





 
If you can share a link it could be investigated. I tried these videos and it worked for Enter, but for Shift-Enter (in Edge browser) the video was bigger than my screen and the progress bar wasn't accessible.
 https://www.alibabacloud.com/videos

**Comment by QiTianzu** [comment]
安装防止网站禁用右键的插件，再右键选择显示控件试试
![image](https://user-images.githubusercontent.com/50047003/126513527-9b305c53-29b8-464d-a71a-dd7def61c9fb.png)

**Comment by rain298** [comment]
可以了！大佬牛皮！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月21日(星期三) 晚上11:14
收件人: ***@***.***&gt;; 
抄送: "┍ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xxxily/h5player] 能不能在视频全屏的时候，在视频底下加一个进度条。或者显示 播放时间/剩余时间 也行。感谢！ (#274)





 
安装防止网站禁用右键的插件，再右键选择显示控件试试
