### ISSUE TITLE
B站视频空格暂停失效

### ISSUE THREAD

**Issue by Devnull6** [xxxily/h5player#276]
B站视频空格暂停失效，测试过youbube和其它视频网站，空格暂停都没有问题，就在B站会有问题，希望可以改进。

**Comment by QingW-7023** [comment]
对的，我也刚刚排查出这个问题！！

**Comment by QingW-7023** [comment]
不对，限制一下范围，是在Edge上失效了，在Chrome上没有失效。我之前特意打开不常用的Chrome试过。

**Comment by LeeYaTuMu** [comment]
我也是B站无法用空格暂停，其他网站正常，用的是edge浏览器

**Comment by lamueno** [comment]
Chrome下：
B站空格键失效。ctrl+space的快捷键显示「禁用h5player插件」后，空格键恢复。
cctv空格键同样失效，表现为视频播放时按下空格键→视频会暂停不到1秒；视频暂停时按下空格键→视频会播放不到1秒。感觉是空格键在很短的间隔内被按了两下。由此怀疑是否是插件没有正确屏蔽原来的空格键控制。
