### ISSUE TITLE
能不能增加一个空格暂停键，挺需要的

### ISSUE THREAD

**Issue by 01Petard** [xxxily/h5player#277]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by JAGulin** [comment]
@01Petard You didn't say what site you have problem with etc. Is it a duplicate of the Bilibili issue above?

**Comment by 01Petard** [comment]
Yes, I didn’t see what others said above, sorry to repeat it again. But I have solved it, this plug-in and another plug-in of the same kind are extremely prone to shortcut key conflicts.

**Comment by 01Petard** [comment]
> @01Petard You didn't say what site you have problem with etc. Is it a duplicate of the Bilibili issue above?

Yes, I didn’t see what others said above, sorry to repeat it again. But I have solved it, this plug-in and another plug-in of the same kind are extremely prone to shortcut key conflicts.
