### ISSUE TITLE
[BUG]哔哩哔哩分p连播后不显示左上角提示,功能正常

### ISSUE THREAD

**Issue by dyxang** [xxxily/h5player#278]
1. **问题描述**
分p或切换p时，网页刷新后正常

2. **出现上述问题的地址**
例子：https://www.bilibili.com/video/BV1Sb411e7zr

3. **你使用的浏览器与浏览器版本信息**
Edge 92.0.902.55  (64 位) Tampermonkey 
4. **其他附注信息**
无其他浏览器插件

**Comment by xxxily** [comment]
目前已正常
