### ISSUE TITLE
[feature request]可以支持<audio>标签吗?

### ISSUE THREAD

**Issue by ts8zs** [xxxily/h5player#279]
悬浮通知显示在界面中间就好

**Comment by JAGulin** [comment]
I suppose audio could be supported, just as video is, but what features do you want to use for audio? Most existing features are currently video related... Possibly your use-case is better handled by another script.

That said, please supply an example URL and clarify your request.

**Comment by ts8zs** [comment]
Some podcast have a low speech speed, So I want speed them up.

**Comment by JAGulin** [comment]
Maybe one of these works until this suggestion has been evaluated.
https://www.userscript.zone/search?a=1&source=header&q=audio+speed
I haven't tested any of them, but I'd try the last one first.

**Comment by ts8zs** [comment]
I will have a try.
but I may uninstall this one because I don't need two,LMAO
