### ISSUE TITLE
在n站全屏播放时没有弹幕

### ISSUE THREAD

**Issue by Tnuo** [xxxily/h5player#280]
1. **问题描述**

在niconico全屏播放时没有弹幕
2. **出现上述问题的地址**

www.nicovideo.jp
3. **你使用的浏览器与浏览器版本信息**

 Google Chrome 版本 91.0.4472.77（正式版本） （64 位）
4. **其他附注信息**

**Comment by xxxily** [comment]
需要通过自定义的方式来调用网站自身的全屏，自定义配置见：https://h5player.anzz.top/home/customConfiguration.html
