### ISSUE TITLE
使用了该增强插件，图形界面便无法调节倍速

### ISSUE THREAD

**Issue by ChineseJavaer** [xxxily/h5player#281]
<img width="715" alt="截屏2021-07-28 上午2 14 42" src="https://user-images.githubusercontent.com/42126940/127206507-0c1d85c0-cf2c-4ef1-a534-b57f268d002d.png">
如图，调节的倍速依然是一倍速，只能通过cxz三个快捷键调节！

**Comment by MY1L** [comment]
同问。已确认与 https://github.com/igrigorik/videospeed 、几乎所有网页播放器自带调速冲突。

**Comment by xxxily** [comment]
已进行兼容
