### ISSUE TITLE
【需求】想要一个黑白名单

### ISSUE THREAD

**Issue by AYijun** [xxxily/h5player#282]
1. **问题描述**
回车是全屏，无法进行弹幕评论。B站默认全屏回车是输入弹幕。
需求：想要针对个别网站关闭插件，像B站，已经有习惯的操作，然后想把插件把B站加入白名单，不在B站的域名运行。

2. **出现上述问题的地址**
https://live.bilibili.com

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge
版本 92.0.902.55 (官方内部版本) (64 位)

4. **其他附注信息**
第一次使用该插件，目前不知道是否有使用说明之类的。如果已有这样功能，还麻烦告知一下。现在只能通过开关插件来达到自己想要的效果，很麻烦。

**Comment by AYijun** [comment]
虽然使用快捷键Ctrl+space可以开关插件，但每次新页面打开都需要按一次，很麻烦，想要设置一次，永久解决那种方式。

**Comment by MC-dusk** [comment]
这是用户自定义的事情啊，不是脚本的事。。
你可以自己在脚本开头添加一行`// @exclude        https://www.bilibili.com`
或者直接在脚本管理器设置黑名单排除

![图片](https://user-images.githubusercontent.com/52311860/128109548-242e5fbe-4bd5-4df3-be9a-b12c10a6e702.png)

**Comment by AYijun** [comment]
> 这是用户自定义的事情啊，不是脚本的事。。
> 10月1日，马元
> 元表示，他要当中"国"，"国""金""国""国""金"国""金""国`// @exclude https://www.bilibili.com`
> 
> ![图片](https://user-images.githubusercontent.com/52311860/128109548-242e5fbe-4bd5-4df3-be9a-b12c10a6e702.png)

**Comment by AYijun** [comment]
> 这是用户自定义的事情啊，不是脚本的事。。
> 10月1日，马元
> 元表示，他要当中"国"，"国""金""国""国""金"国""金""国`// @exclude https://www.bilibili.com`
> 
> ![图片](https://user-images.githubusercontent.com/52311860/128109548-242e5fbe-4bd5-4df3-be9a-b12c10a6e702.png)

不怎么会用油猴，因为有些插件是自带排除模块，只需要改一下参数，就可以排除。谢谢大佬的教程，已经成功排除。
