### ISSUE TITLE
[BUG]B站（番剧区）播放器bug，主要是空格不能播放/暂停

### ISSUE THREAD

**Issue by MC-dusk** [xxxily/h5player#283]
1. **问题描述**
B站（番剧区）播放器bug，主要是空格不能播放/暂停

2. **出现上述问题的地址**
以 https://www.bilibili.com/bangumi/play/ss5983 为例

3. **你使用的浏览器与浏览器版本信息**
火狐浏览器 90.0.2 (64 位)
Tampermonkey BETA 4.14.6142

4. **其他附注信息**
可能和播放器灰度更新有关

- 普通区

![图片](https://user-images.githubusercontent.com/52311860/128110954-ccce5885-5b39-46aa-ba3b-673d4dc9b525.png)

- 番剧区

![图片](https://user-images.githubusercontent.com/52311860/128110965-d607ef26-a6e7-4aeb-b614-ce78a9d73bad.png)

**Comment by MC-dusk** [comment]
参见：
https://github.com/the1812/Bilibili-Evolved/issues/1992 
#269 #273 #276 #277

**Comment by xxxily** [comment]
已正常支持
