### ISSUE TITLE
[BUG] b站部分视频无法使用 / failed in some Bilibili videos

### ISSUE THREAD

**Issue by Mocky-533** [xxxily/h5player#290]
1. **问题描述**

在某些B站视频内脚本失效，具体表现为快捷键按下后有左上角提示，但对视频播放本身没有效果
Script failed to run in some bilibili videos. for example, when I click <kbd>C</kbd>, a "playback 1.1" is shown on the top left, but video did not speed up. 

2. **出现上述问题的地址**

脚本可用的视频地址 / video that script works : https://www.bilibili.com/video/BV1mo4y1U7Fc
脚本在大部分B站视频播放时失效 / script failed in most bilibili videos

3. **你使用的浏览器与浏览器版本信息**

microsoft edge 94.0.982.2 (Official build) dev (64-bit)

4. **其他附注信息**

None

**Comment by Mocky-533** [comment]
脚本其他功能如**快进、色彩调节**等也不起作用

**Comment by WuTianming** [comment]
我的感觉是这个bug是随机触发的，例如您给出的那个可用的地址，我试了一下，也会出bug。现在就是大部分情况下都会失效。

**Comment by Mocky-533** [comment]
嗯，刚才看了一下主楼的那个链接也出bug了，😔

**Comment by WinkeyLin** [comment]
我这边的情况是B站所有视频 100% 失效，包括倍速、左右方向键进度调节，版本 Chrome 92.0.4515.159

**Comment by FXTD-ODYSSEY** [comment]
我将B站的浏览器网站数据清空，然后重新登录一下就好了

**Comment by Mocky-533** [comment]
> 我将B站的浏览器网站数据清空，然后重新登录一下就好了

欸，还真可以了

-----

> 应该是跟B站的新版播放器灰度有关，参考：[the1812/Bilibili-Evolved#1992](https://github.com/the1812/Bilibili-Evolved/issues/1992)

嗯，看上去应该是了，不过普通视频的播放器好像一直是2.64.3这个？我没有仔细看过。
刚才按着楼下的方法试了一下也确实又可以正常使用了hhhh

**Comment by avarpow** [comment]
看起来是b站对video标签做了改变

![d9936774b8b27ff8e922df57042ad38](https://user-images.githubusercontent.com/20969172/130529744-1a741a2b-bc54-4d28-b115-dd8faaf104e6.png)

使用新标签输入命令还是能变速的
```
document.querySelector('bwp-video').playbackRate = 5.0;
```
目前b站还没有全量使用这个，部分网页仍然使用<video>标签。

**Comment by soloopooo** [comment]
根据浏览器扩展哔哩哔哩助手的提示，极大的可能是因为播放器的播放策略采用了优先HEVC解码。
![image](https://user-images.githubusercontent.com/36123081/130741382-d4664e8e-d4ed-4723-96b3-8ea970c16914.png)
将其禁止后，所有的快捷键即恢复正常。

**Comment by Mocky-533** [comment]
> 根据浏览器扩展哔哩哔哩助手的提示，极大的可能是因为播放器的播放策略采用了优先HEVC解码。
> 将其禁止后，所有的快捷键即恢复正常。

有效！感谢~
