### ISSUE TITLE
B站快进失效 [BUG]

### ISSUE THREAD

**Issue by tanxy619** [xxxily/h5player#291]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by qiansen1386** [comment]
好像是跟这个有关。不知道怎么解
```
当前处于跨域受限的Iframe中，h5Player相关功能可能无法正常开启
```

**Comment by nnnnzz** [comment]
你在播放界面，有个播放设置，点击更多播放设置，播放策略  选择禁用HEVC 试一试

**Comment by zgxkbtl** [comment]
> 你在播放界面，有个播放设置，点击更多播放设置，播放策略 选择禁用HEVC 试一试

确实是这个原因，为啥HEVC编码就不能快进了

**Comment by qiansen1386** [comment]
但是这是为什么呢？启用 HEVC 的时候如果点一下画中画再恢复，也可以启用倍速。
