### ISSUE TITLE
[BUG]西瓜视频网页版脚本失效

### ISSUE THREAD

**Issue by lyjhyjyes** [xxxily/h5player#293]
1. **问题描述**

Ctrl+\开启，Ctrl+space开启，确认过了。依然无法使用/w/e/r之类快捷键

2. **出现上述问题的地址**

https://www.ixigua.com/6997252156352889374?logTag=a77d23655ff810f24009

3. **你使用的浏览器与浏览器版本信息**

win10 chrome92
油猴4.13

4. **其他附注信息**

**Comment by JAGulin** [comment]
I tried that site and it worked for me. I use TamperMonkey 4.13, and I suppose you did too, as you run chrome. 
When you press w, do you get a message in upper left corner? Do you get any error message in logs?

The script is in some case specific for QWERTY/English keyboard layout and expects keycode 87 for w.
What do you get if you load https://keycode.info/ and press the w key?
Are these shortcuts working on other sites for you?

**Comment by xxxily** [comment]
目前支持正常
