### ISSUE TITLE
[BUG]关于现阶段B站无法使用脚本的可能原因

### ISSUE THREAD

**Issue by soloopooo** [xxxily/h5player#294]
1. **问题描述**
B站无法使用脚本的情况应该持续了将近两个月。以下是可能原因。

2. **出现上述问题的地址**
bilibili.com/video/*

3. **你使用的浏览器与浏览器版本信息**
Chrome任意版本

4. **其他附注信息**
根据浏览器扩展“哔哩哔哩助手”的提示，现阶段B站HTML5播放器默认采用了优先HEVC编码的播放策略。该策略下，几乎所有第三方脚本与扩展的快捷键均不生效，脚本甚至会将视频的大小识别为整个DOM（表现为提示在浏览器的左上角显示而不是在视频div的左上角显示）。
目前可用的解决办法：
![image](https://user-images.githubusercontent.com/36123081/130741988-49221275-f526-4a90-a89c-bda34bd9fb7e.png)
![image](https://user-images.githubusercontent.com/36123081/130742026-ed98b3c7-13d3-46ad-b939-937ba259df5b.png)
将播放方式改为禁止HEVC即可。

**Comment by TalonX1** [comment]
Thank you ,you are right.

**Comment by Surf565** [comment]
赞

**Comment by bi9potato** [comment]
edge这样解决了，赞

**Comment by letterk** [comment]
赞, 我这是b站最近几天才给我优先成了HEVC, 前几天都没事

**Comment by guotd** [comment]
很有用，解决了问题

**Comment by LakeishaKowalczyk** [comment]
为什么我没有这个选项

![图片](https://user-images.githubusercontent.com/14090545/131291097-b873f973-2e97-469e-ad54-84f137ec7f88.png)

**Comment by letterk** [comment]
> 为什么我没有这个选项
> 
> ![图片](https://user-images.githubusercontent.com/14090545/131291097-b873f973-2e97-469e-ad54-84f137ec7f88.png)

b站目前好像并没有全站推广HEVC, 毕竟许多手机无法硬解. 这个选项功能好像是你点开第一个4K视频后才出现的

**Comment by scutxd** [comment]
非常感谢！

**Comment by kdyouidiankun** [comment]
牛啊大哥，一下就好了

**Comment by changyexing** [comment]
多谢哦！

**Comment by notfornothing** [comment]
有用！感谢！

**Comment by zr1026** [comment]
3qqqqqqqqqqqqqqqqq
