### ISSUE TITLE
学习强国网站视频，播放声音正常，图像消失

### ISSUE THREAD

**Issue by alexander688** [xxxily/h5player#3]
你好，用你的脚本播放好多网站都很好用，非常感谢！
但在强国学习上播放视频出现问题：视频声音正常，播放初期两秒钟画面正常，闪一下图像消失，但声音还在正常播放，快捷键调节也正常使用，就是下面网址。
PS：系统是win10企业版，Chrome74.0.3729.157（正式版本） （64 位）

https://www.xuexi.cn/4d9c383798a2b91a51e2a1015bb55e23/b2e5aa79be613aed1f01d261c4a2ae17.html

**Comment by xxxily** [comment]
看了下，这个网站做了一些特殊性检测，它自己故意自动隐藏的，基于该网站的敏感性，占不打算对其进行兼容性处理，抱歉
