### ISSUE TITLE
[BUG]按左右箭头快进没反应

### ISSUE THREAD

**Issue by freshBirdA** [xxxily/h5player#302]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by JAGulin** [comment]
I don't see that you listed which URL or video you have this problem for. It should not be a general problem, I think.
Are the other commands working as intended? 

Note: I'm using machine translation to read your issue and I may misunderstand because of that.
