### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kkk8574990** [xxxily/h5player#306]
1. **问题描述**
docs.qq.com 开启插件会导致腾讯文档打不开 

2. **出现上述问题的地址**
https://docs.qq.com/sheet/DWHNjdXZ1aUhSbWlS?tab=03ji2f

3. **你使用的浏览器与浏览器版本信息**
chrome最新

4. **其他附注信息**

**Comment by JAGulin** [comment]
> opening plug-in will cause Tencent documents to fail to open

Can you explain some more of what this means? I tried the link and I could see a spread-sheet. But I wasn't logged in and don't know if it worked as intended during edit. 

As a workaround, you should be able to add docs.qq.com to the "exclude" domains in the script settings.

**Comment by xxxily** [comment]
问题已修复
