### ISSUE TITLE
[BUG]一些只有推出全屏才能切集的网站不能切集

### ISSUE THREAD

**Issue by vsdf23vd** [xxxily/h5player#308]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by JAGulin** [comment]
Please provide more info. Machine translation gives "Some websites that can only be cut in full screen cannot be cut" which I can't understand. 

Reading your initial issue title, I guess agefans was an example and randomly tried this video.
[https://www.agefans.cc/play/20180015?playid=4_1](https://www.agefans.cc/play/20180015?playid=4_1)

For me, play/pause works fine. Full screen (Enter) works fine, Full Page (Shift-Enter) did nothing. Next Episode (N) is a feature implemented for each page separately. It's not implemented, so does nothing. Other things I tried worked fine.

Note: This website tries to prevent tampering, so it may be hard to overcome problems.
