### ISSUE TITLE
[BUG]b站调节速度不生效

### ISSUE THREAD

**Issue by 18-air** [xxxily/h5player#310]
1. **问题描述**

b站调节速度不生效 调节上下帧也不生效
2. **出现上述问题的地址**

https://www.bilibili.com/video/BV13q4y1Z7hv?spm_id_from=333.851.b_7265706f7274466972737432.6
3. **你使用的浏览器与浏览器版本信息**

Microsoft Edge
版本 94.0.992.31 (官方内部版本) (64 位)
4. **其他附注信息**

**Comment by 18-air** [comment]
测试了一下 是所有功能都不能用。

**Comment by leyuuu** [comment]
![image](https://user-images.githubusercontent.com/50611440/136701782-b676b372-37fd-4e2a-aff8-559ee2516a5d.png)
Try disable HEVC.

**Comment by FunAomi** [comment]
禁止hevc就可以了！
