### ISSUE TITLE
[BUG] 画中画窗口问题

### ISSUE THREAD

**Issue by Naileon** [xxxily/h5player#312]
1. **问题描述**

画中画放大，窗口会卡不见
2. **出现上述问题的地址**

https://www.agefans.cc/play/20130030?playid=3_1
3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by JAGulin** [comment]
I coundn't reproduce this issue, maybe I didn't understand the problem. Please fill in the other questions (e.g. browser you use and other plugins that may be interfering) and provide more information about how to reproduce.
