### ISSUE TITLE
netflix error code ﻿f7375[BUG]

### ISSUE THREAD

**Issue by roeravid** [xxxily/h5player#317]
1. **问题描述**

i do not know the language here but netflix error code f7375 occurs when i try to play any video
2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by kkksa528** [comment]
7375bug 100%复现方法，进脚本打开情况下netflix视频，进入视频的前几秒钟进行视频快进或者跳转，100%复现这个bug

**Comment by xxxily** [comment]
兼容在netflix上关闭该插件

**Comment by roeravid** [comment]
Yo what

**Comment by RokeJulianLockhart** [comment]
@roeravid, you might have encountered https://github.com/MALSync/MALSync/issues/3134#issue-3271343092. [^1]

[^1]: [`bugzilla.mozilla.org/show_bug.cgi?id=1352934#c23`][1]

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1352934#c23
