### ISSUE TITLE
建议增加知乎首页视频播放速度

### ISSUE THREAD

**Issue by 1353604736** [xxxily/h5player#318]

**Comment by JAGulin** [comment]
I didn't understand the problem. Please provide more information.

1. Problem Description
2. The URL address where the above problem occurs
3. Information about the browser and browser version you are using
4. Other relevant information

**Comment by 1353604736** [comment]
https://www.zhihu.com/

视频：无法记住播放速度（Video: Can’t remember playback speed ）
Shortcut key is invalid
