### ISSUE TITLE
谷歌浏览器在bilibili播放插件失效问题

### ISSUE THREAD

**Issue by chilly-java** [xxxily/h5player#319]
同时使用的还有“网盘智能助手”插件。
使用该插件时，不止该插件失效，bilibili本身自带的键盘控制（如快进、音量大小）也无法控制视频。
谷歌浏览器版本：版本 92.0.4515.159（正式版本） （64 位）

**Comment by cary-rowen** [comment]
同样的问题，求解决。

**Comment by JAGulin** [comment]
Please provide a link to the "other" plugin, translation said "Network Disk Smart Assistant" and I couldn't find that. Is everything ok if you disable that temporarily?

**Comment by cary-rowen** [comment]
I disabled other scripts on Bilibili and can still reproduce this problem. I use violent monkey

**Comment by muoyuu** [comment]
![1635946933(1)](https://user-images.githubusercontent.com/93660819/140071079-ef71a71b-ff52-44c5-8599-2497c8e87f29.jpg)
B站视频设置里面设置禁止HEVC即可解决大部分使用问题。

**Comment by muoyuu** [comment]
> 使用的还有“网盘智能助手”插件。 使用该插件时，不应该插件失效，bilibili自带的键盘控制（如快进、音量大小）也无法控制视频。 谷歌浏览器版本：92.0 .4515.159（正式版） （64位）
![1635946933(1)](https://user-images.githubusercontent.com/93660819/140071652-c9be0552-2d46-4466-9e6f-0908d8539e1d.jpg)
B站视频设置里面设置 “禁止 HEVC“ 即可解决大部分使用问题。

**Comment by cary-rowen** [comment]
The above method is effective, thank you

**Comment by xxxily** [comment]
已兼容B站的HEVC视频（bwp播放器）
