### ISSUE TITLE
在高校邦观看网课时脚本被禁用无法生效

### ISSUE THREAD

**Issue by Collier01** [xxxily/h5player#320]
https://hfuu.class.gaoxiaobang.com/class/49884/unit/388928/chapter/2879561#!state=chapter&chapterId=2879561
账号：18805695075
密码：fwa1913122036
使用快进30s功能时，进度条原地踏步；
使用倍速播放时被检测而禁用；
请问这个网址有解决方案吗

**Comment by xxxily** [comment]
脚本已进行优化升级，目前已可支持该地址上的倍速和视频进度控制
