### ISSUE TITLE
[BUG] Bilibili部分视频在调整图像设置后后出现卡顿、掉帧的情况

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [xxxily/h5player#322]
1. **问题描述**
Bilibili部分视频在调整图像设置后后出现卡顿、掉帧的情况，复位图像属性无效

2. **出现上述问题的地址**
https://www.bilibili.com/video/BV1TP4y1j7jL （其实大部分视频都会有）

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge	95.0.1020.40 (官方内部版本) (64 位)
修订	1f61f1c45c1e4229af88888771afd46a90ce2e88
操作系统	Windows 10 Version 21H1 (Build 19043.1320)
JavaScript	V8 9.5.172.25
用户代理	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.40

4. **其他附注信息**
此bug并非必然出现，其他视频网站亦会出现，但出现频率较低

**Comment by JAGulin** [comment]
Can you describe the "image adjustments" made? Translated, I read "resetting the image attributes is invalid" which I don't understand. Isn't it possible to reset the adjustments back to normal?

When there is frame drop it might be that you accidentally change playback speed. Try to reset all image modifications to pin-point which change that is the problem:
* Z	Normal speed playback
* shift + Z	Restore video frame
* Q	Image reset

**Comment by Galaxy-Studio-Code** [comment]
例如调节亮度之后，视频就会出现掉帧，我尝试了按下Q键或者用其他方法（包含刷新）来使视频不再掉帧，但这没有作用，当我倍速播放视频时，这种情况并没有改善

**Comment by Galaxy-Studio-Code** [comment]
当我打开硬件加速时，这种情况出现的概率小得多，但是我认为即使关闭了硬件加速电脑也足以处理这些视频

**Comment by xxxily** [comment]
没发现此情况，或最新版已修复
