### ISSUE TITLE
[BUG]B站番剧无法使用空格 暂停

### ISSUE THREAD

**Issue by agni-bumi** [xxxily/h5player#326]
1. **问题描述**
B站番剧设置里没有 关于“ HEVC“这栏的选项 ，但普通视频无论有没有打开HEVC都能正常使用快捷键

2. **出现上述问题的地址**
比如：https://www.bilibili.com/bangumi/play/ep400982

3. **你使用的浏览器与浏览器版本信息**
Vivaldi | 3.3.2022.45 (Stable channel) （64 位）

4. **其他附注信息**

**Comment by iamqiz** [comment]
是的,启用这个脚本之后, 空格没法暂停了

**Comment by iamqiz** [comment]
解决了, 方法是吧 hasUseKey 里的keyCodeList 和keyList 删掉空格,这样isRegisterKey就不会处理空格,这样空格就是原本功能了
下面是改完后的代码
```
const hasUseKey = {
  keyCodeList: [13, 16, 17, 18, 27, 37, 38, 39, 40, 49, 50, 51, 52, 67, 68, 69, 70, 73, 74, 75, 78, 79, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 97, 98, 99, 100, 220],
  keyList: ['enter', 'shift', 'control', 'alt', 'escape', 'arrowleft', 'arrowright', 'arrowup', 'arrowdown', '1', '2', '3', '4', 'c', 'd', 'e', 'f', 'i', 'j', 'k', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'w', 'x', 'y', 'z', '\\', '|'],
```

**Comment by agni-bumi** [comment]
> 解决了, 方法是吧 hasUseKey 里的keyCodeList 和keyList 删掉空格,这样isRegisterKey就不会处理空格,这样空格就是原本功能了 下面是改完后的代码
> 
> ```
> const hasUseKey = {
>   keyCodeList: [13, 16, 17, 18, 27, 37, 38, 39, 40, 49, 50, 51, 52, 67, 68, 69, 70, 73, 74, 75, 78, 79, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 97, 98, 99, 100, 220],
>   keyList: ['enter', 'shift', 'control', 'alt', 'escape', 'arrowleft', 'arrowright', 'arrowup', 'arrowdown', '1', '2', '3', '4', 'c', 'd', 'e', 'f', 'i', 'j', 'k', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'w', 'x', 'y', 'z', '\\', '|'],
> ```

非常感谢，问题解决了
