### ISSUE TITLE
在b站看直播频繁刷新[BUG]

### ISSUE THREAD

**Issue by MuXia-0326** [xxxily/h5player#329]
浏览器控制台报错信息
id 7: video native error: {"code":90002,"errInfo":{"code":3,"msg":"PIPELINE_ERROR_DECODE: D3D11VideoDecoder error: 0x102 VDA Error 0"}}

**Comment by JAGulin** [comment]
I would not assume the error to be related to this script. Can you confirm that the problem disappears when you deactivate the script?

**Comment by MuXia-0326** [comment]
> I would not assume the error to be related to this script. Can you confirm that the problem disappears when you deactivate the script?
> 
> If it is related to the script, can you restore all image modifications:
> 
> * Z	Normal speed playback
> * shift + Z	Restore video frame
> * Q	Image reset

When I have time on the weekend, I will try to see if it was caused by my own reasons. Thank you for your answer.

**Comment by MuXia-0326** [comment]
![image](https://user-images.githubusercontent.com/63834850/146640638-8dbd3a87-6844-4953-865a-a8d69d294b34.png)
看直播的时候会自动反复刷新这个，是不是脚本原因导致的？

**Comment by MuXia-0326** [comment]
![image](https://user-images.githubusercontent.com/63834850/146640638-8dbd3a87-6844-4953-865a-a8d69d294b34.png)
看直播的时候会自动反复刷新这个，是不是脚本原因导致的？
