### ISSUE TITLE
[BUG] 控制台警告 ```popper.js.map``` 404

### ISSUE THREAD

**Issue by StephanoGeorge** [xxxily/h5player#330]
1. **问题描述**
Firefox 控制台警告：
`源映射错误：Error: NetworkError when attempting to fetch resource.
源 URL：moz-extension://762576d8-a2bc-46d5-8378-05db97ae6a1d/userscripts/HTML5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8%E5%A2%9E%E5%BC%BA%E8%84%9A%E6%9C%AC.user.js?id=6dc149c8-400d-4550-84fc-0b12e9ce5221
源映射 URL：popper.js.map`
Chromium 控制台警告：
`DevTools 无法加载来源映射：无法加载 chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/popper.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME`

2. **出现上述问题的地址**
任意网址，如：https://docs.python.org/3

3. **你使用的浏览器与浏览器版本信息**
Firefox for Linux 94.0.2
Chromium for Linux 96.0.4664.45

4. **其他附注信息**
若关闭此脚本，则不会出现警告

**Comment by scrgy** [comment]
借个楼 插件很好用  希望倍速调节可以每次加减0.3 虽然可以手动改()

**Comment by xxxily** [comment]
这个暂时无法修复，也不算是BUG，可能强迫症看起来会有点难受，抱歉
