### ISSUE TITLE
[BUG]跨Tab控制功能失效，请问跨域访问有什么技巧嘛，测试了firfox,360极速，360安全，微软edge浏览器，貌似都用不了（全局控制打开的）

### ISSUE THREAD

**Issue by chantsing** [xxxily/h5player#332]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by chantsing** [comment]
firefox 95.0.1
edge   96.0.1054.62
系统是window11,处理器是锐龙3750H

**Comment by xxxily** [comment]
> firefox 95.0.1 edge 96.0.1054.62 系统是window11,处理器是锐龙3750H

最新版已修复了跨域和画中画垮TAB控制的能力，可以更新测试下是否正常
