### ISSUE TITLE
在B站上功能失效了

### ISSUE THREAD

**Issue by haidongsong** [xxxily/h5player#338]
在B站上功能又失效了，全屏后弹幕没了，前进后退无效。。。

**Comment by Hodpel** [comment]
是停更了吗 明明作者还很活跃 就是不更这个

**Comment by keeker233** [comment]
普通视频好像还是可以的，但是番剧和电影就不行，优酷视频也是，全屏后没弹幕也没下面进度条，用鼠标点击它的全屏按钮才行

**Comment by elvisli** [comment]
求更新。。

**Comment by dingar** [comment]
禁止HEVC试试
![image](https://user-images.githubusercontent.com/499606/150677058-da9a5ec5-3e88-4fa6-a5f0-95f05cda3158.png)

**Comment by elvisli** [comment]
> 禁止HEVC试试 ![image](https://user-images.githubusercontent.com/499606/150677058-da9a5ec5-3e88-4fa6-a5f0-95f05cda3158.png)
试了下可以！

**Comment by forestlet** [comment]
新版设置使用 `AVC` 播放策略

<img width="211" alt="image" src="https://user-images.githubusercontent.com/80408376/151132446-44394ecd-538e-4376-a390-8f11471a48dd.png">

**Comment by Hodpel** [comment]
此外由于播放工具栏无法显示, 在全屏状态下看不到播放进度 只能退出全屏看下面的蓝条这一点也很烦

**Comment by xxxily** [comment]
已更新并修复了相关问题，如果还有其它问题，欢迎新开issues反馈
