### ISSUE TITLE
左上角的信息文字要怎么去除

### ISSUE THREAD

**Issue by seong1995** [xxxily/h5player#340]
1. **问题描述**
左上角的信息文字要怎么去除，我不希望每一次点击快捷键都会出现

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**
chrome最新稳定版

4. **其他附注信息**

**Comment by xxxily** [comment]
> 1. **问题描述**
>    左上角的信息文字要怎么去除，我不希望每一次点击快捷键都会出现
> 2. **出现上述问题的地址**
> 
> 3. **你使用的浏览器与浏览器版本信息**
>    chrome最新稳定版
> 4. **其他附注信息**
这个去除不了，如果没有操作信息反馈，将会不知道自己进行的操作是否成功
