### ISSUE TITLE
[BUG]pilipili部分视频空格暂停失效

### ISSUE THREAD

**Issue by BaiBuCYBGT** [xxxily/h5player#346]
1. **问题描述**

部分网站空格暂停失效
2. **出现上述问题的地址**

https://www.bilibili.com/bangumi/play/ep321917
带bangumi的全部按空格无法暂停
3. **你使用的浏览器与浏览器版本信息**

火狐97x64
4. **其他附注信息**

**Comment by invobzvr** [comment]
```js
{
    switchPlayStatus: '.bilibili-player-video-btn-start', // 3.3.9版本第954行
}
```
网站播放器更新导致，注释掉该行即可

**Comment by BaiBuCYBGT** [comment]
> 我修复了 但是作者还没理我😥 #342

大佬，现在/video的空格暂停又失效了，可以帮忙改一下不

**Comment by ESWZY** [comment]
> > 我修复了 但是作者还没理我😥 #342
> 
> 大佬，现在/video的空格暂停又失效了，可以帮忙改一下不

哪个页面的 我明早瞅瞅

**Comment by BaiBuCYBGT** [comment]
> > > 我修复了 但是作者还没理我😥 #342
> > 
> > 
> > 大佬，现在/video的空格暂停又失效了，可以帮忙改一下不
> 
> 哪个页面的 我明早瞅瞅

www.bilibili.com/video这个的

**Comment by BaiBuCYBGT** [comment]
> > > 我修复了 但是作者还没理我😥 #342
> > 
> > 
> > 大佬，现在/video的空格暂停又失效了，可以帮忙改一下不
> 
> 哪个页面的 我明早瞅瞅

https://www.bilibili.com/video/
这个页面的

**Comment by ESWZY** [comment]
> > > > 我修复了 但是作者还没理我😥 #342
> > > 
> > > 
> > > 大佬，现在/video的空格暂停又失效了，可以帮忙改一下不
> > 
> > 
> > 哪个页面的 我明早瞅瞅
> 
> https://www.bilibili.com/video/ 这个页面的

没啥问题啊 我还能用😂

**Comment by BaiBuCYBGT** [comment]
> > > > > 我修复了 但是作者还没理我😥 #342
> > > > 
> > > > 
> > > > 大佬，现在/video的空格暂停又失效了，可以帮忙改一下不
> > > 
> > > 
> > > 哪个页面的 我明早瞅瞅
> > 
> > 
> > https://www.bilibili.com/video/ 这个页面的
> 
> 没啥问题啊 我还能用😂

那好奇怪啊，我/video/的空格失灵了，用了你改的/bangumi/还是好的

**Comment by Shinnosuke6** [comment]
> > > > > 我修复了 但是作者还没理我😥 #342
> > > > 
> > > > 
> > > > 大佬，现在/video的空格暂停又失效了，可以帮忙改一下不
> > > 
> > > 
> > > 哪个页面的 我明早瞅瞅
> > 
> > 
> > https://www.bilibili.com/video/ 这个页面的
> 
> 没啥问题啊 我还能用😂

兄弟，我的也是chrome看bilibili空格暂停失效，回车全屏加载不了弹幕，你现在用的脚本真的没出现这个问题吗😂

**Comment by Shinnosuke6** [comment]
> 



> > > > > > > 我修复了 但是作者还没理我😥 #342
> > > > > > 
> > > > > > 
> > > > > > 大佬，现在/video的空格暂停又失效了，可以帮忙改一下不
> > > > > 
> > > > > 
> > > > > 哪个页面的 我明早瞅瞅
> > > > 
> > > > 
> > > > https://www.bilibili.com/video/ 这个页面的
> > > 
> > > 
> > > 没啥问题啊 我还能用😂
> > 
> > 
> > 兄弟，我的也是chrome看bilibili空格暂停失效，回车全屏加载不了弹幕，你现在用的脚本真的没出现这个问题吗😂
> 
> 😂 你看看我修改的那部分 在你的dashboard那里修改一下 我现在是完美运行😂

已经修改，但是回车全屏还是没有弹幕，算了，将就用，谢谢大佬

**Comment by xxxily** [comment]
已修复
