### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lczhuce1801100** [xxxily/h5player#347]
1. **问题描述**
A。我在一个视频集，第一个视频全屏看，自动播放第二个视频，就不是全屏了，能否自动全屏？
B。正在播放一个视频，会车全屏，然后f5刷新，打开后不全屏，能否自动全屏？
2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by xxxily** [comment]
这个暂时估计没法支持
