### ISSUE TITLE
「功能请求」B站字幕快捷键和弹幕开关快捷键

### ISSUE THREAD

**Issue by draftman9** [xxxily/h5player#352]
虽然不是刚需，但是如果可以的话，麻烦还是加上吧。感谢！😄

**Comment by xxxily** [comment]
> 虽然不是刚需，但是如果可以的话，麻烦还是加上吧。感谢！😄

这个暂不考虑增加，过多的快捷键记不住，后续如果能开发自定义快捷键的能力再自行加上吧
