### ISSUE TITLE
暫時解決快捷鍵衝突的問題

### ISSUE THREAD

**Issue by EndlessNull** [xxxily/h5player#355]
# **目前這個方法沒辦法指定某個網站，而是直接永久性地取消那快捷鍵**

以取消esc鍵為例：
![2022-03-17 12:06:52-ScreenshotByFFmpeg](https://user-images.githubusercontent.com/34579128/158735668-c8023252-c1e2-453a-b49a-32f4458278e2.png)
刪除keyMap中的`esc: 27,`，它指示了`esc`對應到`27`，所以一併刪除keyList中的`'escape', `、keyCodeList中的`27,`

它應該變成這樣
![2022-03-17 12:19:13-ScreenshotByFFmpeg](https://user-images.githubusercontent.com/34579128/158736451-5c391d1c-d887-4a52-865f-c20ca002580b.png)

儲存後就好了，想恢復的話重裝一次或把備份的覆蓋回去（腳本更新時好像也會被變成新版的樣子）

## **備份：**
以`/*`和`*/`框住`const hasUseKey`的區域，然後複製一份到它後面
![2022-03-17 12:26:27-ScreenshotByFFmpeg](https://user-images.githubusercontent.com/34579128/158737058-069f57b2-25e5-42e4-8055-896a9e57cfa9.png)

**Comment by 7peanuts** [comment]
确实，只要播放了，即使立即关闭播放器，也会导致快捷键被占用，连 Ctrl+C 都没法用
感觉需要改一下，只在播放时使用快捷键。

**Comment by xxxily** [comment]
已支持自定义配置：https://h5player.anzz.top/home/customConfiguration.html
