### ISSUE TITLE
[BUG]关于b站视频无法获取的一种解决方法

### ISSUE THREAD

**Issue by luguoyixiazi** [xxxily/h5player#356]
1. **问题描述**

在我使用的 3.3.9版本上无法获取哔哩哔哩的video标签，经过观察发现b站是把video封到bwp-video里面了，直接拿video拿到的是里面的video，操作时promise会失败，但是直接获取bwp-video可以获得真实有效的dom
我在代码里面加了这一句，然后就生效了：
list.push(document.getElementsByTagName('bwp-video')[0])
2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

Chrome 98.0.4758.82（正式版本） （32 位）
4. **其他附注信息**

**Comment by itheabyss** [comment]
厉害啊，哥们，果然能用了。谢谢

**Comment by xxxily** [comment]
> 1. **问题描述**
> 
> 在我使用的 3.3.9版本上无法获取哔哩哔哩的video标签，经过观察发现b站是把video封到bwp-video里面了，直接拿video拿到的是里面的video，操作时promise会失败，但是直接获取bwp-video可以获得真实有效的dom 我在代码里面加了这一句，然后就生效了： list.push(document.getElementsByTagName('bwp-video')[0]) 2. **出现上述问题的地址**
> 
> 3. **你使用的浏览器与浏览器版本信息**
> 
> Chrome 98.0.4758.82（正式版本） （32 位） 4. **其他附注信息**

最新脚本已支持B站的HEVC视频（bwp播放器）
