### ISSUE TITLE
[BUG]pilipili上空格暂停失效以及回车全屏无法加载弹幕

### ISSUE THREAD

**Issue by BaiBuCYBGT** [xxxily/h5player#357]
1. **问题描述**
空格暂停失效，回车以及上当+回车进入的全屏和全网页会导致弹幕失效
2. **出现上述问题的地址**
https://www.bilibili.com/video/BV1Za41147hR
3. **你使用的浏览器与浏览器版本信息**
Firefox 98.0.2
暴力猴v2.13.0
4. **其他附注信息**
新ie在p站的空格暂停没失效

**Comment by Shinnosuke6** [comment]
我也有同样的问题，原来是插件的问题

**Comment by BaiBuCYBGT** [comment]
> 我也有同样的问题，原来是插件的问题

怎么解决的？

**Comment by Shinnosuke6** [comment]
> 

我解决不了啊，估计是bug吧，等作者完善

**Comment by DengYuncheng27** [comment]
我也是这样的问题！

**Comment by kosakiw** [comment]
暂停键的issue里有大佬帮忙解决了
但是回车全屏后 弹幕无法加载这个 还亟需解决

**Comment by xxxily** [comment]
> 1. **问题描述**
>    空格暂停失效，回车以及上当+回车进入的全屏和全网页会导致弹幕失效
> 2. **出现上述问题的地址**
>    https://www.bilibili.com/video/BV1Za41147hR
> 3. **你使用的浏览器与浏览器版本信息**
>    Firefox 98.0.2
>    暴力猴v2.13.0
> 4. **其他附注信息**
>    新ie在p站的空格暂停没失效

已更新支持，感谢反馈
