### ISSUE TITLE
建议修改网页视频快捷键

### ISSUE THREAD

**Issue by bitxx** [xxxily/h5player#361]
大部分的全屏快捷键是 Alt+Ent 并不是 Shift + Ent 玩过游戏的人都知道的。

网页中，按下ESC 为退出全屏， 建议作者可以处理一下ESC的特殊性， 检查 当前页面是不是网页全屏， 用ESC来替代 Shift+ent 更方便。 按下Esc进入网页全屏 按下Esc退出网页全屏

**Comment by xxxily** [comment]
> 

shift+enter是网页全屏（进入或退出都可以），Esc可取消全屏或网页全屏
