### ISSUE TITLE
好哥哥能不能旋转+缩放

### ISSUE THREAD

**Issue by BenjaminLN** [xxxily/h5player#37]
pornhub，不能同时旋转且缩放，横向的视频旋转90°之后会损失上下两侧的画面

**Comment by Tubackup** [comment]
我修复了一下，自己测试没问题
[地址](https://github.com/Tubackup/h5player/raw/master/dist/h5player.js)

**Comment by BenjaminLN** [comment]
> 我修复了一下，自己测试没问题
> [地址](https://github.com/Tubackup/h5player/raw/master/dist/h5player.js)

爱你！！😀
