### ISSUE TITLE
[BUG]百度云不行！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！感谢大大赶紧修改

### ISSUE THREAD

**Issue by sangsangyonglan** [xxxily/h5player#372]
1. **问题描述**
百度云在线观看视频，什么都没有。快捷键失灵

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**
谷歌

4. **其他附注信息**

**Comment by xxxily** [comment]
百度盘的非会员用户建议结合：https://greasyfork.org/zh-CN/scripts/441747  这个脚本使用，即可实现倍速
