### ISSUE TITLE
鼠标左键或者空格点击两次才会暂停[BUG]

### ISSUE THREAD

**Issue by skogsng** [xxxily/h5player#376]
1. **问题描述**
鼠标左键或者空格点击两次才会暂停

2. **出现上述问题的地址**
https://www.bilibili.com/

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge
版本 101.0.1210.39 (正式版本) (64 位)

**Comment by normalhh** [comment]
> 1. 将第953行注释掉，可解决点击两次才能暂停的bug，但是在暂停状态下，按←和→方向键不能自动播放了（我无所谓）
>    `    autoPlay: '.bilibili-player-video-btn-start',`
> 2. 将第954行注释掉，可解决番剧播放时按空格键无法暂停和播放的bug
>    `    switchPlayStatus: '.bilibili-player-video-btn-start',`
>    我的Chrome版本 101.0.4951.64在这样改之后是可以解决这两个问题的

番剧和普通视频有效，但在直播间无效
