### ISSUE TITLE
[BUG]B站如果是HEVC视频则无法控制

### ISSUE THREAD

**Issue by sakumakenshin** [xxxily/h5player#377]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by skystary** [comment]
AV1与AVC编码都可用，另外主要发生在Chrome浏览器，Firefox一直正常，不知是否浏览器影响了默认选取的编码格式。问题存在很久了，希望能尽快修复

**Comment by maboloshi** [comment]
Chrome开启HEVC硬解 就没这个问题

**Comment by JianYuhaha** [comment]
> Chrome开启HEVC硬解 就没这个问题

CHROME真么开硬解？我查到的都是edge开

**Comment by maboloshi** [comment]
https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding

**Comment by JianYuhaha** [comment]
thankyou～


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月14日(周四) 上午10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xxxily/h5player] [BUG]B站如果是HEVC视频则无法控制 (Issue #377)




 
https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding
 
&mdash;

**Comment by xxxily** [comment]
最新脚本已支持B站的HEVC视频（bwp播放器）

**Comment by skystary** [comment]
谢谢更新，但已经用iPad代替MacBook了，目前该脚本还无法在iPad上运行，无法测试，使用的是拦截100
