### ISSUE TITLE
[BUG]百度网盘视频不能倍速

### ISSUE THREAD

**Issue by qaz-123-123** [xxxily/h5player#380]
1. **问题描述**
使用快捷键对百度网盘视频无效，不能倍速观看

2. **出现上述问题的地址**
https://pan.baidu.com/

3. **你使用的浏览器与浏览器版本信息**
Edge

4. **其他附注信息**
希望您可以改进一下，十分感谢！！！

**Comment by xxxily** [comment]
> 

百度盘的非会员用户建议结合：https://greasyfork.org/zh-CN/scripts/441747  这个脚本使用，即可实现倍速
