### ISSUE TITLE
[BUG]Netflix暂停等操作出错

### ISSUE THREAD

**Issue by sypgfg** [xxxily/h5player#381]
1. **问题描述**
<netflix可自动播放视频，但是暂停，快进等任何操作都会报错，错误代码M7375，关闭脚本后正常>

2. **出现上述问题的地址**
<www.netflix.com>

3. **你使用的浏览器与浏览器版本信息**
<Chrome最新版>

**Comment by xxxily** [comment]
倍速会导致netflix 的视频流失效，暂时没好的解决办法，建议在netflix上禁止该脚本，快捷键：Ctrl+space
