### ISSUE TITLE
[BUG] 暂停视频，按下逐帧播放后自动继续播放

### ISSUE THREAD

**Issue by GIT-Zireael** [xxxily/h5player#382]
1. **问题描述**
暂停视频，按下逐帧播放后自动继续播放

2. **出现上述问题的地址**
www.bilibili.com 

3. **你使用的浏览器与浏览器版本信息**
EDGE浏览器 版本 101.0.1210.53 (正式版本) (64 位) 

4. **其他附注信息**
用AV1和AVC编码都试了一下，还是不行

**Comment by xxxily** [comment]
自测，逐帧播放支持正常
