### ISSUE TITLE
[BUG]百度网盘倍数播放失效了

### ISSUE THREAD

**Issue by SalayDay** [xxxily/h5player#385]
1. **问题描述**
百度网盘在线播放不能倍数

2. **出现上述问题的地址**
https://pan.baidu.com/

3. **你使用的浏览器与浏览器版本信息**
edge 版本 103.0.1255.0 (正式版本) dev (64 位)

4. **其他附注信息**
考研党不能倍数看网课，难受，求修复

**Comment by yzfeng-CHEN** [comment]
同求

**Comment by just-automatic** [comment]
> 同求

脚本没问题, 同求啥呢

**Comment by xxxily** [comment]
> 1. **问题描述**
>    百度网盘在线播放不能倍数
> 2. **出现上述问题的地址**
>    https://pan.baidu.com/
> 3. **你使用的浏览器与浏览器版本信息**
>    edge 版本 103.0.1255.0 (正式版本) dev (64 位)
> 4. **其他附注信息**
>    考研党不能倍数看网课，难受，求修复

自测百度盘支持正常
