### ISSUE TITLE
[BUG]脚本截图失败，请作者尽快修复这个问题。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [xxxily/h5player#388]
1. **问题描述**

    截图失败

2. **出现上述问题的地址**

https://www.bilibili.com/

3. **你使用的浏览器与浏览器版本信息**

浏览器：360极速浏览器X

浏览器版本：V21.0.1100.0

4. **其他附注信息**
![HTML5增强脚本bug1](https://user-images.githubusercontent.com/103800975/171376534-62dd7905-e490-40ad-a69c-d6ea4f852b57.jpg)

**Comment by xxxily** [comment]
视频源限制了，目前没有啥好办法可以解决
