### ISSUE TITLE
[BUG] B站目前播放快捷键功能都不能使用

### ISSUE THREAD

**Issue by Jamin00** [xxxily/h5player#392]
1. **问题描述**
倍速、音量等快捷键都会有显示，但是没有实际效果

2. **出现上述问题的地址**
https://www.bilibili.com/video/BV19U4y1b7VP?p=10&spm_id_from=pageDriver&vd_source=7c9f5118f9a595b8a61fa19fe96fe254

3. **你使用的浏览器与浏览器版本信息**
 Chrome 已是最新版本
版本 102.0.5005.115（正式版本）

4. **其他附注信息**

**Comment by Jamin00** [comment]
已解决， 在播放里  选   设置—>更多播放设置—>里更换播放策略  就可以了

**Comment by JianYuhaha** [comment]
> 

更换除HECV的策略都可以用吗？
