### ISSUE TITLE
[BUG]你好，开发者，这个（https://www.jubaibai.cc/）网址的视屏网页全屏的快捷键没有响应，希望能够添加一下。

### ISSUE THREAD

**Issue by Colaloverrr** [xxxily/h5player#393]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by Colaloverrr** [comment]
1.网页全屏快捷键无用
2.https://www.jubaibai.cc/
3.我是用的是win10 edge浏览器
4。Microsoft Edge  版本 102.0.1245.39 (正式版本) (64 位)

**Comment by xxxily** [comment]
> https://www.jubaibai.cc/

这个网站的播放器是通过iframe引入的，需要焦点在播放器里快捷键才能生效
