### ISSUE TITLE
[BUG]百度云视频无法使用动画倍速

### ISSUE THREAD

**Issue by ilikerainydays** [xxxily/h5player#394]
1. **问题描述**
打开百度云视频无法使用倍速，但是视频在加载的时候可以使用倍速并且加载动画明显成功倍速。
[加载动画完成后无法使用倍速功能及其他功能。
![3S1E{2 56L{G286C@S_3Z(4](https://user-images.githubusercontent.com/44765329/174419813-590fa395-1a92-44ac-8e77-3b278a6bd8cc.png)

2. **出现上述问题的地址**
(https://pan.baidu.com/)

3. **你使用的浏览器与浏览器版本信息**
Google Chrome 102.0.5005.115

4. **其他附注信息**
如果可以麻烦修复一下 谢谢

**Comment by qudder** [comment]
我也遇到这个问题，关键是我看第一个视频是可以用的，第二个就不行了，我卸了重装了好几次都不行。

**Comment by frankzheng43** [comment]
加一

**Comment by xxxily** [comment]
百度盘的非会员用户建议结合：https://greasyfork.org/zh-CN/scripts/441747  这个脚本使用，即可实现倍速

**Comment by ilikerainydays** [comment]
> 百度盘的非会员用户建议结合：[https](https://greasyfork.org/zh-CN/scripts/441747) : //greasyfork.org/zh-CN/scripts/441747这个脚本使用，可以实现倍速

好的问题解决了 谢谢
