### ISSUE TITLE
将快捷键大全集成在脚本中

### ISSUE THREAD

**Issue by abcdesteve** [xxxily/h5player#395]
1. **问题描述**

将快捷键大全集成在脚本中，GitHub有时候很难访问，通过网页提示实现
就像这样![image](https://user-images.githubusercontent.com/72078508/174433356-9f61e406-490b-47f1-b01a-0c824bebd002.png)

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

edge 102.0.1245.44 (正式版本) (64 位)

4. **其他附注信息**

**Comment by xxxily** [comment]
已集成到插件的菜单里
