### ISSUE TITLE
希望支持腾讯视频 还有希望添加画中画快捷键

### ISSUE THREAD

**Issue by LucisZheng** [xxxily/h5player#4]
你好，非常喜欢你的这个脚本

但我发现脚本的倍速对***腾讯视频***不起作用

搜了一圈，终于搜到个脚本对腾讯视频起作用的

[倍速播放](https://greasyfork.org/zh-CN/scripts/383265)  在这位大佬的这个脚本里的脚本描述有段说明

>特别说明
腾讯视频 由于是封装了播放器，把设置速率的接口屏蔽了。目前没有找到直接修改播放速率的接口。所以，只能通过设置 window.session 数据来改变速率。并且，需要有刷新（比如网页刷新，上下集，快进快退等等）动作的时候，设置过的播放速率才会生效。
经过测试，腾讯播放器接受的最高播放速率是 4.0 倍。

但它不支持快捷键，每次都要滑动调节倍速，总感觉有点麻烦，所以想问一下能不能把功能集成进去？

还有一点，能不能添加画中画的快捷键

之前一直在用谷歌出的  [Picture-in-Picture Extension](https://chrome.google.com/webstore/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg)  按  alt+p  调出画中画

之后我才知道原来画中画是  html5 的一个功能，虽然谷歌的那个扩展才  6k 大小，但我还是希望把功能添进去，这样就又能少个扩展~

**Comment by xxxily** [comment]
画中画这个功能可以支持，但是腾讯这玩意真不好兼容，有时间了解他是怎么实现的再去兼容吧，或者通过模拟操作去兼容它

**Comment by xxxily** [comment]
画中画这个功能可以支持，但是腾讯这玩意真不好兼容，有时间了解他是怎么实现的再去兼容吧，或者通过模拟操作去兼容它

**Comment by xxxily** [comment]
已增加画中画功能（shift+P）,增加了腾讯视频快捷键兼容，如有问题欢迎继续反馈。

**Comment by LucisZheng** [comment]
> 已增加画中画功能（shift+P）,增加了腾讯视频快捷键兼容，如有问题欢迎继续反馈。

好快👍
不过腾讯视频现在只能  0.5x ~2.0x  吗，有办法像那位一样  0.1x~4.0x  吗

**Comment by xxxily** [comment]
> > 已增加画中画功能（shift+P）,增加了腾讯视频快捷键兼容，如有问题欢迎继续反馈。
> 
> 好快
> 不过腾讯视频现在只能 0.5x ~ 2.0x 吗
> 有办法像那位一样 0.1x ~ 4.0x 吗

0.5-2确实不过瘾～ 最新版本已经支持0.1x ~ 4.0x 了

**Comment by LucisZheng** [comment]
> > > 已增加画中画功能（shift+P）,增加了腾讯视频快捷键兼容，如有问题欢迎继续反馈。
> > 
> > 
> > 好快
> > 不过腾讯视频现在只能 0.5x ~ 2.0x 吗
> > 有办法像那位一样 0.1x ~ 4.0x 吗
> 
> 0.5-2确实不过瘾～ 最新版本已经支持0.1x ~ 4.0x 了

太棒了👍
