### ISSUE TITLE
一些情况下没有进度条。

### ISSUE THREAD

**Issue by takenusername** [xxxily/h5player#40]
全屏（enter）和网页全屏（shift+enter）没有进度条。
回到初始状态（esc或切换enter）要在按一下 enter 才显示进度条。

**Comment by xxxily** [comment]
> 全屏（enter）和网页全屏（shift+enter）没有进度条。
> 回到初始状态（esc或切换enter）要在按一下 enter 才显示进度条。

这个功能无法做到全兼容，每个网站的dom结构都不一样

**Comment by takenusername** [comment]
> > 全屏（enter）和网页全屏（shift+enter）没有进度条。
> > 回到初始状态（esc或切换enter）要在按一下 enter 才显示进度条。
> 
> 这个功能无法做到全兼容，每个网站的dom结构都不一样

谢谢，了解了。
