### ISSUE TITLE
建议添加一个视频镜像翻转功能

### ISSUE THREAD

**Issue by 5chi-3cun-4fen** [xxxily/h5player#402]
1. **问题描述**
希望能够增加一个视频镜像功能

3. **你使用的浏览器与浏览器版本信息**
firefox 103.0b4 (64 位)

4. **其他附注信息**
跳舞的时候很需要这个功能

**Comment by xxxily** [comment]
> 1. **问题描述**
>    希望能够增加一个视频镜像功能
> 2. **你使用的浏览器与浏览器版本信息**
>    firefox 103.0b4 (64 位)
> 3. **其他附注信息**
>    跳舞的时候很需要这个功能

不太明白为啥需要这个功能

**Comment by 5chi-3cun-4fen** [comment]
> > 1. **问题描述**
> >    希望能够增加一个视频镜像功能
> > 2. **你使用的浏览器与浏览器版本信息**
> >    firefox 103.0b4 (64 位)
> > 3. **其他附注信息**
> >    跳舞的时候很需要这个功能
> 
> 不太明白为啥需要这个功能

因为跳舞的很多视频视频是正向的，但是学舞蹈的时候看镜像会方便很多。如果有这个功能的话就不用再把视频下载下来镜像了

**Comment by xxxily** [comment]
> > > 1. **问题描述**
> > >    希望能够增加一个视频镜像功能
> > > 2. **你使用的浏览器与浏览器版本信息**
> > >    firefox 103.0b4 (64 位)
> > > 3. **其他附注信息**
> > >    跳舞的时候很需要这个功能
> > 
> > 
> > 不太明白为啥需要这个功能
> 
> 因为跳舞的很多视频视频是正向的，但是学舞蹈的时候看镜像会方便很多。如果有这个功能的话就不用再把视频下载下来镜像了

最新版已增加这个功能：快捷键：M
