### ISSUE TITLE
can not take screenshots in some webpage or video players

### ISSUE THREAD

**Issue by seriousgigi** [xxxily/h5player#406]
in some webpages or video players it says in english "<website name> says"  then long japanese sentence when you try to take screenshot. so you can not take screenshot from that web page or video player.

here took a screenshot:

![Screenshot (66) (2jpg)](https://user-images.githubusercontent.com/83796753/179327141-e3bc4938-4012-43fd-a062-9fb6c8d9e07e.jpg)

please help me :)

**Comment by xxxily** [comment]
截图功能已优化
