### ISSUE TITLE
能否支撑播放/暂停的快捷键？

### ISSUE THREAD

**Issue by mining-id** [xxxily/h5player#407]
1. **问题描述**
目前只能是用鼠标点击播放，然后再按加速或者减速的快捷键控制
希望播放也可以支撑快捷键，这样就可以全程都用键盘操作了。会更方便。感谢！

2. **出现上述问题的地址**
无

3. **你使用的浏览器与浏览器版本信息**
无

4. **其他附注信息**
无

**Comment by pzh200707** [comment]
希望支持空格键播放/暂停

**Comment by qiansen1386** [comment]
YouTube可以，Bilibili跟官方的快捷键冲突，有点难受。

**Comment by yigexuezha** [comment]
希望b站支持空格键播放/暂停，官方快捷键能屏蔽吗

**Comment by RJiazhen** [comment]
> 希望b站支持空格键播放/暂停，官方快捷键能屏蔽吗

如果要屏蔽插件的空格键功能可以参考我提交的[issue](https://github.com/xxxily/h5player/issues/414)，修改和删除空格键相关的内容即可

**Comment by xxxily** [comment]
> YouTube可以，Bilibili跟官方的快捷键冲突，有点难受。

B站的播放、暂停、全屏、网页全屏、下一集快捷键异常问题已修复
