### ISSUE TITLE
bilibili 回车 全屏后  弹幕无法加载，退出全屏模式后正常

### ISSUE THREAD

**Issue by kosakiw** [xxxily/h5player#410]
1. **问题描述**
bilibili 回车全屏后 默认弹幕无法加载

2. **出现上述问题的地址**
](https://www.bilibili.com/)

3. **你使用的浏览器与浏览器版本信息**
Chrome 已是最新版本
版本 103.0.5060.134（正式版本） （64 位）

4. **其他附注信息**
ESC 退出全屏后，弹幕扔可加载

**Comment by xxxily** [comment]
> 1. **问题描述**
>    bilibili 回车全屏后 默认弹幕无法加载
> 2. **出现上述问题的地址**
>    ](https://www.bilibili.com/)
> 3. **你使用的浏览器与浏览器版本信息**
>    Chrome 已是最新版本
>    版本 103.0.5060.134（正式版本） （64 位）
> 4. **其他附注信息**
>    ESC 退出全屏后，弹幕扔可加载

B站的播放、暂停、全屏、网页全屏、下一集快捷键异常问题已修复
