### ISSUE TITLE
希望可以提供在某些网站禁用部分功能的选项

### ISSUE THREAD

**Issue by qiansen1386** [xxxily/h5player#411]
1. **问题描述**
我举两个例子，两个场景：
  - 由于Enter和Space两个按键和B站的默认功能冲突，而官方的默认功能挺好用的。我只需要使用B站没有的功能，比如快速调速。这时候希望可以移除Enter和space的监听，或者监听了不执行动作，继续向后传递事件。
  - Twitter对于视频全屏的支持并不好，全屏了之后再退出界面就全乱了，有时候在推特点开某个抖音视频，再按ESC，页面就挂了，必须刷新才能回到信息流。
目前跟B站相关的大部分Issues都跟这个有关

3. **出现上述问题的地址**
任意Bilibili和Twitter网址。

4. **你使用的浏览器与浏览器版本信息**
Chrome 103.0.5060.134 Tampermonkey 4.16.1

5. **其他附注信息**

**Comment by xxxily** [comment]
> 

B站的问题已修复，单独禁用某些快捷键功能应该比较少人用，暂不打算提供
