### ISSUE TITLE
[BUG]空格键无法控制暂停和播放

### ISSUE THREAD

**Issue by RJiazhen** [xxxily/h5player#414]
1. **问题描述**
在使用B站时空格键无法正常暂停和播放视频，在Youtube中正常。手动删除代码中`hasUseKey.keyCodeList`、`hasUseKey.keyList`和`hasUseKey.keyMap`中空格键相关内容，以及注释掉`keyCode === 32`的相关if判断语句后能够正常使用B站自带的空格暂停视频功能。
尝试过在Chrome隐私模式下关闭所有其他浏览器扩展和油猴插件后测试，问题依旧。

2. **出现上述问题的地址**
https://www.bilibili.com/

3. **你使用的浏览器与浏览器版本信息**
Chrome Version 103.0.5060.134 (Official Build) (64-bit)

4. **其他附注信息**
无

**Comment by VermilionStarUniverse** [comment]
同这个issue的问题, 也曾尝试过提PR解决一下, 但管理员一直没回复, 不知道是不是这个项目停止维护了, 貌似很久没更新了
https://github.com/xxxily/h5player/issues/398

**Comment by silenceallat** [comment]
刚研究了一下，在源程序103行 ` const key = event.key.toLowerCase(); ` 下一行添加判断语句：
```
    if (keyCode == 32){
        return false;
    }
```
即可解决 空格键（space）**暂停/开始**的问题，同时也能避免对**回车键全屏**造成影响！

**Comment by licocy** [comment]
> 

太感谢了，我被这个问题困扰了好几天

**Comment by joewsr** [comment]
> if (keyCode == 32){
>         return false;
>     }

谢谢老哥 真的帮助很大

**Comment by 01Petard** [comment]
> 刚研究了一下，在源程序103行 `const key = event.key.toLowerCase();` 下一行添加判断语句：
> 
> ```
>     if (keyCode == 32){
>         return false;
>     }
> ```
> 
> 即可解决 空格键（space）**暂停/开始**的问题，同时也能避免对**回车键全屏**造成影响！

实测可用，感谢！应该是屏蔽了脚本本身的按键，然后走b站自己按键是吧？

**Comment by xxxily** [comment]
> 同这个issue的问题, 也曾尝试过提PR解决一下, 但管理员一直没回复, 不知道是不是这个项目停止维护了, 貌似很久没更新了 #398

还在维护的，只是我很少用B站看视频，所以并未及时修复，目前已经修复

**Comment by xxxily** [comment]
> 1. **问题描述**
>    在使用B站时空格键无法正常暂停和播放视频，在Youtube中正常。手动删除代码中`hasUseKey.keyCodeList`、`hasUseKey.keyList`和`hasUseKey.keyMap`中空格键相关内容，以及注释掉`keyCode === 32`的相关if判断语句后能够正常使用B站自带的空格暂停视频功能。
>    尝试过在Chrome隐私模式下关闭所有其他浏览器扩展和油猴插件后测试，问题依旧。
> 2. **出现上述问题的地址**
>    https://www.bilibili.com/
> 3. **你使用的浏览器与浏览器版本信息**
>    Chrome Version 103.0.5060.134 (Official Build) (64-bit)
> 4. **其他附注信息**
>    无

B站的播放、暂停、全屏、网页全屏、下一集快捷键异常问题已修复

**Comment by yigexuezha** [comment]
> 刚研究了一下，在源程序103行 `const key = event.key.toLowerCase();` 下一行添加判断语句：
> 
> ```
>     if (keyCode == 32){
>         return false;
>     }
> ```
> 
> 即可解决 空格键（space）**暂停/开始**的问题，同时也能避免对**回车键全屏**造成影响！

大佬能不能帮我解决下这个问题，万谢！！#415
