### ISSUE TITLE
大佬能不能加个速度档位？比如1，2，3各自是不同的速度？

### ISSUE THREAD

**Issue by yigexuezha** [xxxily/h5player#415]
大佬能不能加个变速档位？比如1，2，3各自是不同的速度？

**Comment by DreamerDK** [comment]
按x和c可以自己调整。
或者自己改搜“按1-4设置播放速度”改改代码。

**Comment by yigexuezha** [comment]
不懂编程。。。

**Comment by yigexuezha** [comment]
> 按x和c可以自己调整。 或者自己改搜“按1-4设置播放速度”改改代码。

不懂编程。。。我连这个脚本用的什么语言都不知道。。

就是设置数字键1，2, 3， 分别对应三种固定的速度，不知道哪里有教程吗

**Comment by wulei-student** [comment]
默认就支持，你按字母区上面的数字键或者小键盘的数字键1、2、3、4
