### ISSUE TITLE
[BUG]B站的网页全屏(Shift+Enter)不显示弹幕和进度条

### ISSUE THREAD

**Issue by pumpbumb** [xxxily/h5player#416]
1. **问题描述**
B站的网页全屏(Shift+Enter)用了后，不显示弹幕和进度条了

2. **出现上述问题的地址**
https://www.bilibili.com

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge
版本 103.0.1264.77 (正式版本) (64 位)

**Comment by UncleZhang13** [comment]
bilibili我也遇到了这个问题
我用的浏览器是 Google Chrome 102.0.5005.63 还有 Edge 103.0.1264.37

**Comment by xxxily** [comment]
> 1. **问题描述**
>    B站的网页全屏(Shift+Enter)用了后，不显示弹幕和进度条了
> 2. **出现上述问题的地址**
>    https://www.bilibili.com
> 3. **你使用的浏览器与浏览器版本信息**
>    Microsoft Edge
>    版本 103.0.1264.77 (正式版本) (64 位)

B站的播放、暂停、全屏、网页全屏、下一集快捷键异常问题已修复

**Comment by xxxily** [comment]
> bilibili我也遇到了这个问题 我用的浏览器是 Google Chrome 102.0.5005.63 还有 Edge 103.0.1264.37

B站的播放、暂停、全屏、网页全屏、下一集快捷键异常问题已修复

**Comment by LakeishaKowalczyk** [comment]
@xxxily 干啥去了，想死宝宝们了

**Comment by pumpbumb** [comment]
> > 1. **问题描述**
> >    B站的网页全屏(Shift+Enter)用了后，不显示弹幕和进度条了
> > 2. **出现上述问题的地址**
> >    https://www.bilibili.com
> > 3. **你使用的浏览器与浏览器版本信息**
> >    Microsoft Edge
> >    版本 103.0.1264.77 (正式版本) (64 位)
> 
> B站的播放、暂停、全屏、网页全屏、下一集快捷键异常问题已修复

谢谢！辛苦了！
