### ISSUE TITLE
Support for 9GAG

### ISSUE THREAD

**Issue by rahaaatul** [xxxily/h5player#417]
Add support for 9gag.com videos, please.

**Comment by LakeishaKowalczyk** [comment]
Tested it and it seems to be supported originally

**Comment by rahaaatul** [comment]
> Tested it and it seems to be supported originally

Doesn't work for me. I tested on Kiwi Browser with ViolentMonkey, and on IceRaven with TamperMonkey.

**Comment by LakeishaKowalczyk** [comment]
> Doesn't work for me. I tested on Kiwi Browser with ViolentMonkey, and on IceRaven with TamperMonkey.

Android? 
This script is used to add shortcuts to the html5 player, it should only work with devices with keyboards

**Comment by rahaaatul** [comment]
> > Doesn't work for me. I tested on Kiwi Browser with ViolentMonkey, and on IceRaven with TamperMonkey.
> 
> Android? 
> This script is used to add shortcuts to the html5 player, it should only work with devices with keyboards

I thought it add controls on video. Sorry, my bad.
