### ISSUE TITLE
[BUG]pornhub不会自动调用H5player了？求救

### ISSUE THREAD

**Issue by hzfa** [xxxily/h5player#419]
1. **问题描述**
pornhub怎么不会自动调用H5player了？播放视频一直转圈圈啊，不是节点问题，油管和BILIBILI其余网站全都正常，pornhub用过别的脚本可以调用出HTML5正常播放，用无痕模式也能播放，奇怪了

2. **出现上述问题的地址**
cn.pornhub.com

3. **你使用的浏览器与浏览器版本信息**
Google Chrome版本 104.0.5112.102（正式版本） （64 位）

**Comment by qiansen1386** [comment]
亲测可以触发。你是不是加入黑名单了？或者是匿名窗口未激活油猴？

**Comment by xxxily** [comment]
可能是跟其他插件冲突了
