### ISSUE TITLE
[BUG]B站禁止自动播放按钮不出现

### ISSUE THREAD

**Issue by gakaks** [xxxily/h5player#421]
B站禁止自动播放按钮不出现 尝试过禁用其他脚本 反复测试 一直无法复现 
之前也是有这个问题 不过弄来弄去成功按出来一次的话就不用理了 
现在死活出不来很难受 任何播放页都不生效 自动播放很烦

Chrome 已是最新版本
版本 104.0.5112.102（正式版本） （64 位）
![B站自动播放按钮不出现](https://user-images.githubusercontent.com/43461224/185420858-0ab30f58-3c17-42cd-baee-872503b67610.jpg)

**Comment by xxxily** [comment]
> B站禁止自动播放按钮不出现 尝试过禁用其他脚本 反复测试 一直无法复现 之前也是有这个问题 不过弄来弄去成功按出来一次的话就不用理了 现在死活出不来很难受 任何播放页都不生效 自动播放很烦
> 
> Chrome 已是最新版本 版本 104.0.5112.102（正式版本） （64 位） ![B站自动播放按钮不出现](https://user-images.githubusercontent.com/43461224/185420858-0ab30f58-3c17-42cd-baee-872503b67610.jpg)

没有这个功能，不过可以考虑加一个

**Comment by gakaks** [comment]
> > B站自动试运行之前也禁止其他脚本理去反复出现测试，一直无法重复成功执行一次的话就不用了，现在死活出不来难受任何播放页面的影响生效 自动播放很烦
> > Chrome 已经是最新版本 104.0.5112.102（正式版本） （64位）![B站自动播放按钮不出现](https://user-images.githubusercontent.com/43461224/185420858-0ab30f58-3c17-42cd-baee-872503b67610.jpg)
> 
> 没有这个功能，不过可以考虑加一个

我记得之前是有的啊 而且日志里也有这个功能 我在edge上的也是禁止B站自动播放的 本来Chrome也是 但是昨天清理了一下浏览器就遭重了 自动播放对于我这种习惯刷动态打开好多视频一个个看过去的人非常难受 希望尽快添加一下这个功能

**Comment by gakaks** [comment]
> > B站自动试运行之前也禁止其他脚本理去反复出现测试，一直无法重复成功，但它弄来弄出一次的话就不用了，现在死活出不来难受任何播放页面的影响生效 自动播放很烦
> > Chrome 已经是最新版本 104.0.5112.102（正式版本） （64位）![B站自动播放按钮不出现](https://user-images.githubusercontent.com/43461224/185420858-0ab30f58-3c17-42cd-baee-872503b67610.jpg)
> 
> 没有这个功能，不过可以考虑加一个

禁止在此网站自动播放失效功能无法正常生效 依然会自动播放 播放策略切换至HEVC则脚本完全失效 其他两个策略则只有禁止在此网站自动播放失效 
B站播放页为旧版播放页
浏览器为Chrome 已是最新版本
版本 104.0.5112.102（正式版本） （64 位）
