### ISSUE TITLE
[BUG]youjizz 网页播放时快进时间会叠加为15秒

### ISSUE THREAD

**Issue by qinfeng22222** [xxxily/h5player#422]
1.问题描述
网页播放快进一次时间会叠加为15秒，变速播放时会卡死需要鼠标点击播放

2.网页
youjizz.com

3. edge浏览器

**Comment by xxxily** [comment]
> 1.问题描述 网页播放快进一次时间会叠加为15秒，变速播放时会卡死需要鼠标点击播放
> 
> 2.网页 youjizz.com
> 
> 3. edge浏览器

更新到最新版试试，或检查是否跟其它插件冲突了，看浏览器控制台是否有报错之类的
