### ISSUE TITLE
[BUG]edge浏览器快捷键设置B站播放速度不生效，默认播放速度也没有被记录

### ISSUE THREAD

**Issue by wulei-student** [xxxily/h5player#423]
1. **问题描述**

[BUG]edge浏览器快捷键设置B站播放速度不生效，默认播放速度也没有被记录

**Comment by xxxily** [comment]
> 1. **问题描述**
> 
> [BUG]edge浏览器快捷键设置B站播放速度不生效，默认播放速度也没有被记录

更新到最新版本看下能否正常，另外参见下 https://github.com/xxxily/h5player/issues/294 这个issues，看是否跟开启HEVC有关
