### ISSUE TITLE
macOS 使用adguard作为脚本管理器无效

### ISSUE THREAD

**Issue by zushl** [xxxily/h5player#424]
1。**问题描述**
macOS 使用adguard for mac版作为脚本管理器，无效

2。**出现上述问题的地址**
已测试bilibili，优酷，西瓜视频

3。**你使用的浏览器与浏览器版本信息**
Safari 版本15.6.1 (17613.3.9.1.16)

4。**其他附注信息**
无

**Comment by xxxily** [comment]
> 1。**问题描述** macOS 使用adguard for mac版作为脚本管理器，无效
> 
> 2。**出现上述问题的地址** 已测试bilibili，优酷，西瓜视频
> 
> 3。**你使用的浏览器与浏览器版本信息** Safari 版本15.6.1 (17613.3.9.1.16)
> 
> 4。**其他附注信息** 无

建议在chrome上的tampermonkey里运行该脚本

**Comment by xxxily** [comment]
> Safari

没测试过Safari，所以不太清楚是否能正常运行
