### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zcljxhy7002Z** [xxxily/h5player#427]
<b站不能使用暂停
>

**Comment by xxxily** [comment]
是更新脚本之后出现的吗？提供个具体视频地址，看下能否复现

**Comment by zahuo** [comment]
我这里的情况是可以暂停播放，但是不能做其他控制。
https://www.bilibili.com/video/BV1ZV411E7Pb?vd_source=3f61fdc5894da63300f687e795a62aa3

**Comment by xxxily** [comment]
> 我这里的情况是可以暂停播放，但是不能做其他控制。 https://www.bilibili.com/video/BV1ZV411E7Pb?vd_source=3f61fdc5894da63300f687e795a62aa3

我这边测试都正常，看下控制台是否有报错，或者检查下是否跟其它插件冲突了？
