### ISSUE TITLE
[BUG] b站无法禁止自动播放

### ISSUE THREAD

**Issue by draftman9** [xxxily/h5player#429]
1. **问题描述**
b站无法禁止自动播放。

2. **出现上述问题的地址**
[视频链接](https://www.bilibili.com/video/BV1kY4y1H7Gy?spm_id_from=333.880.my_history.page.click&vd_source=e1f4d89847961d7d3be7cf22d090baf1)

3. **你使用的浏览器与浏览器版本信息**
星愿浏览器：当前版本 7.6.2000.2103 ( Chromium: 80.0.3987.163 Res: 2102.453 ) （64 位）

4. **其他附注信息**
无

**Comment by xxxily** [comment]
> 1. **问题描述**
>    b站无法禁止自动播放。
> 2. **出现上述问题的地址**
>    [视频链接](https://www.bilibili.com/video/BV1kY4y1H7Gy?spm_id_from=333.880.my_history.page.click&vd_source=e1f4d89847961d7d3be7cf22d090baf1)
> 3. **你使用的浏览器与浏览器版本信息**
>    星愿浏览器：当前版本 7.6.2000.2103 ( Chromium: 80.0.3987.163 Res: 2102.453 ) （64 位）
> 4. **其他附注信息**
>    无

好像是b站自身的默认行为吧？脚本不会阻止默认播放行为，只会阻止自身配置的自动播放逻辑

**Comment by gakaks** [comment]
> > 1. **描述**
> >    b站无法禁止自动播放问题。
> > 2. **出现上述问题的地址**
> >    [视频链接](https://www.bilibili.com/video/BV1kY4y1H7Gy?spm_id_from=333.880.my_history.page.click&vd_source=e1f4d89847961d7d3be7cf22d090baf1)
> > 3. **您使用的浏览器与浏览器版本信息**
> >    星愿浏览器：当前版本 7.6.2000.2103 ( Chromium: 80.0.3987.163 Res: 2102.453 ) （64位）
> > 4. **其他附注信息**
> >    无
> 
> 是好像是的默认行为吧？

同遇到此问题 禁止在此网站自动播放失效功能无法正常生效 依然会自动播放 播放策略切换至HEVC则脚本完全失效 其他两个策略则只有禁止在此网站自动播放失效
B站播放页为旧版播放页
浏览器为Chrome 已是最新版本
版本 104.0.5112.102（正式版本） （64 位）

**Comment by draftman9** [comment]
> 好像是b站自身的默认行为吧？脚本不会阻止默认播放行为，只会阻止自身配置的自动播放逻辑

关闭脚本后，就不会自动播放了。初步推测是脚本造成的自动播放。

**Comment by xxxily** [comment]
> > 好像是b站自身的默认行为吧？脚本不会阻止默认播放行为，只会阻止自身配置的自动播放逻辑
> 
> 关闭脚本后，就不会自动播放了。初步推测是脚本造成的自动播放。

菜单里有个禁止自动播放的开关，你禁止自动播放看是否有效

**Comment by draftman9** [comment]
> > 关闭脚本后，就不会自动播放了。初步推测是脚本造成的自动播放。
> 
> 菜单里有个禁止自动播放的开关，你禁止自动播放看是否有效

我在b站和脚本的设置上都试了，没有效果。

另外，我在脚本中发现了下图所示的config中，autoplay我改为false了，但是只要刷新就会自动恢复为true。希望这个消息会给你提供线索。

![image](https://user-images.githubusercontent.com/99490289/187055944-b6273f7e-6ef9-47d8-a50c-44d62cdb564a.png)

**Comment by xxxily** [comment]
> > > 关闭脚本后，就不会自动播放了。初步推测是脚本造成的自动播放。
> > 
> > 
> > 菜单里有个禁止自动播放的开关，你禁止自动播放看是否有效
> 
> 我在b站和脚本的设置上都试了，没有效果。
> 
> 另外，我在脚本中发现了下图所示的config中，autoplay我改为false了，但是只要刷新就会自动恢复为true。希望这个消息会给你提供线索。
> 
> ![image](https://user-images.githubusercontent.com/99490289/187055944-b6273f7e-6ef9-47d8-a50c-44d62cdb564a.png)

你在B站下有看到这个菜单吗？切换这个试试
![image](https://user-images.githubusercontent.com/3418704/187106323-59c1aea7-a4d8-409f-960f-2e88f4fb9db6.png)

**Comment by draftman9** [comment]
> 你在B站下有看到这个菜单吗？切换这个试试 ![image](https://user-images.githubusercontent.com/3418704/187106323-59c1aea7-a4d8-409f-960f-2e88f4fb9db6.png)

我更新到3.4.4后，相关问题已消失。谢谢作者！😄

**Comment by gakaks** [comment]
nice 3.44已修复相关问题
