### ISSUE TITLE
感谢开发者,Facebook视频支持有点问题.

### ISSUE THREAD

**Issue by RoeltaNcRave** [xxxily/h5player#43]
Facebook里面的视频,如果直接点击它自带的播放器右下角的全屏,其实不会全屏的.当然这其实不是用户想要的,用户想要的是进入真正的全屏.而刚好用此脚本插件,按键盘回车键,是可以进入正常的真正的全屏播放的.可是,在Facebook里就会出现,全屏切换黑屏,或者卡顿,或者有时候全屏再切回来后,画面不见了等等不正常的状态.
使用浏览器edge,多次,多个不同Facebook的视频测试

**Comment by xxxily** [comment]
> Facebook里面的视频,如果直接点击它自带的播放器右下角的全屏,其实不会全屏的.当然这其实不是用户想要的,用户想要的是进入真正的全屏.而刚好用此脚本插件,按键盘回车键,是可以进入正常的真正的全屏播放的.可是,在Facebook里就会出现,全屏切换黑屏,或者卡顿,或者有时候全屏再切回来后,画面不见了等等不正常的状态.
> 使用浏览器edge,多次,多个不同Facebook的视频测试

Facebook的兼容性确实不好，它家网页选择器全是随机的，目前对全屏做了部分兼容，要做到完全兼容还是比较困难
