### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MengXueSD** [xxxily/h5player#430]
1. **问题描述**
b站无法加速播放

2. **出现上述问题的地址**
www.bilibili.com

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge
版本 104.0.1293.70 (正式版本) (64 位)

4. **其他附注信息**
请求大佬修复

**Comment by xxxily** [comment]
> 

看下控制台有什么报错吗？

**Comment by xxxily** [comment]
> 1. **问题描述**
>    b站无法加速播放
> 2. **出现上述问题的地址**
>    [www.bilibili.com](http://www.bilibili.com)
> 3. **你使用的浏览器与浏览器版本信息**
>    Microsoft Edge
>    版本 104.0.1293.70 (正式版本) (64 位)
> 4. **其他附注信息**
>    请求大佬修复

应该是使用了HEVC格式下的bwp播放器导致的没法控制加速，最新版已增加了bwp播放器的兼容
