### ISSUE TITLE
EDGE 浏览器播放 在线mp4链接时使用插件画面会被缩得很小

### ISSUE THREAD

**Issue by eason1234560** [xxxily/h5player#431]
EDGE 浏览器播放 在线mp4链接（https://ts7.sztv.com.cn/szmg/vod/2022/08/25/88737e1312064df997b95327885ab627/_h264_1200k_mp4.mp4）时使用插件画面会被缩得很小
![image](https://user-images.githubusercontent.com/111443595/187060727-bdbc72e9-3ff9-49b3-bbb2-526b286819eb.png)

**Comment by xxxily** [comment]
> EDGE 浏览器播放 在线mp4链接（[https://ts7.sztv.com.cn/szmg/vod/2022/08/25/88737e1312064df997b95327885ab627/_h264_1200k_mp4.mp4）时使用插件画面会被缩得很小](https://ts7.sztv.com.cn/szmg/vod/2022/08/25/88737e1312064df997b95327885ab627/_h264_1200k_mp4.mp4%EF%BC%89%E6%97%B6%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6%E7%94%BB%E9%9D%A2%E4%BC%9A%E8%A2%AB%E7%BC%A9%E5%BE%97%E5%BE%88%E5%B0%8F) ![image](https://user-images.githubusercontent.com/111443595/187060727-bdbc72e9-3ff9-49b3-bbb2-526b286819eb.png)

是最新版本的脚本了吗？最新的脚本会检查如果严重影响了画面尺寸，会自动回退样式

**Comment by xxxily** [comment]
我先关掉issues了，如果更新脚本后，还有问题，请重新打开issues
