### ISSUE TITLE
[BUG]B站“禁止在此网站自动播放视频”功能失效

### ISSUE THREAD

**Issue by gakaks** [xxxily/h5player#432]
该功能无法正常运作 不管选择允许还是禁止 都会自动播放视频 禁用该脚本则不会自动播放
尝试过禁用全部脚本仅保留该脚本 功能仍然失效
播放策略切换至HEVC则脚本完全失效 AV1和AVC则此功能失效
Chrome 已是最新版本
版本 104.0.5112.102（正式版本） （64 位）
![Clip_20220829_095353](https://user-images.githubusercontent.com/43461224/187107718-a1a216c7-f90a-4d8e-a38a-9f4b1a852c05.png)

https://user-images.githubusercontent.com/43461224/187109932-175b15e9-b491-43bb-b6f2-0406180529f9.mp4

**Comment by xxxily** [comment]
> 该功能无法正常运作 不管选择允许还是禁止 都会自动播放视频 禁用该脚本则不会自动播放 尝试过禁用全部脚本仅保留该脚本 功能仍然失效 播放策略切换至HEVC则脚本完全失效 AV1和AVC则此功能失效 Chrome 已是最新版本 版本 104.0.5112.102（正式版本） （64 位） ![Clip_20220829_095353](https://user-images.githubusercontent.com/43461224/187107718-a1a216c7-f90a-4d8e-a38a-9f4b1a852c05.png)
> 
>  bandicam.2022-08-29.09-48-04-873_x264_x264.2._new.mp4

将该脚本也禁用了，能停止自动播放吗？

**Comment by gakaks** [comment]
> > 该功能无法正常运作 不管选择允许还是禁止 都会自动播放视频 禁用该脚本则不会自动播放 尝试过禁用全部脚本仅保留该脚本 功能仍然失效 播放策略切换至HEVC则脚本完全失效 AV1和AVC则此功能失效 Chrome 已是最新版本 版本 104.0.5112.102（正式版本） （64 位） ![Clip_20220829_095353](https://user-images.githubusercontent.com/43461224/187107718-a1a216c7-f90a-4d8e-a38a-9f4b1a852c05.png)
> > bandicam.2022-08-29.09-48-04-873_x264_x264.2._new.mp4
> 
> 将该脚本也禁用了，能停止自动播放吗？

对 如果禁用该脚本则不会自动播放 在视频第50秒有演示

**Comment by xxxily** [comment]
> > > 该功能无法正常运作 不管选择允许还是禁止 都会自动播放视频 禁用该脚本则不会自动播放 尝试过禁用全部脚本仅保留该脚本 功能仍然失效 播放策略切换至HEVC则脚本完全失效 AV1和AVC则此功能失效 Chrome 已是最新版本 版本 104.0.5112.102（正式版本） （64 位） ![Clip_20220829_095353](https://user-images.githubusercontent.com/43461224/187107718-a1a216c7-f90a-4d8e-a38a-9f4b1a852c05.png)
> > > bandicam.2022-08-29.09-48-04-873_x264_x264.2._new.mp4
> > 
> > 
> > 将该脚本也禁用了，能停止自动播放吗？
> 
> 对 如果禁用该脚本则不会自动播放 在视频第50秒有演示

好的，我回头有空排查下是什么问题

**Comment by xxxily** [comment]
> > > 该功能无法正常运作 不管选择允许还是禁止 都会自动播放视频 禁用该脚本则不会自动播放 尝试过禁用全部脚本仅保留该脚本 功能仍然失效 播放策略切换至HEVC则脚本完全失效 AV1和AVC则此功能失效 Chrome 已是最新版本 版本 104.0.5112.102（正式版本） （64 位） ![Clip_20220829_095353](https://user-images.githubusercontent.com/43461224/187107718-a1a216c7-f90a-4d8e-a38a-9f4b1a852c05.png)
> > > bandicam.2022-08-29.09-48-04-873_x264_x264.2._new.mp4
> > 
> > 
> > 将该脚本也禁用了，能停止自动播放吗？
> 
> 对 如果禁用该脚本则不会自动播放 在视频第50秒有演示

最新脚本已经修复了相关问题，你看下能否正常停止自动播放

**Comment by gakaks** [comment]
> > > > 该功能无法正常运作 不管选择允许还是禁止 都会自动播放视频 禁用该脚本则不会自动播放 尝试过禁用全部脚本仅保留该脚本 功能仍然失效 播放策略切换至HEVC则脚本完全失效 AV1和AVC则此功能失效 Chrome 已是最新版本 版本 104.0.5112.102（正式版本） （64 位） ![Clip_20220829_095353](https://user-images.githubusercontent.com/43461224/187107718-a1a216c7-f90a-4d8e-a38a-9f4b1a852c05.png)
> > > > bandicam.2022-08-29.09-48-04-873_x264_x264.2._new.mp4
> > > 
> > > 
> > > 将该脚本也禁用了，能停止自动播放吗？
> > 
> > 
> > 对 如果禁用该脚本则不会自动播放 在视频第50秒有演示
> 
> 最新脚本已经修复了相关问题，你看下能否正常停止自动播放

测试后 3.44已修复相关问题 感谢作者

**Comment by da-pang-za** [comment]
现在又有这个问题了，辛苦处理一下~
