### ISSUE TITLE
[Feature Request] Invert colors of video

### ISSUE THREAD

**Issue by jupiter104** [xxxily/h5player#433]
Just like you can adjust brightness, contrast, saturation, etc., it would be great if you could also invert the video colors using a keyboard shortcut.

![1426](https://user-images.githubusercontent.com/24752210/187894711-f9ffcb7d-dada-4cdf-a5ec-ac5f552b72a4.jpg)

**Comment by xxxily** [comment]
能支持这个功能，但会导致过多的快捷键，所以等后续能自定义快捷键了再考虑将这个功能集成进来
