### ISSUE TITLE
[BUG]画中画播放其它网页的视频或直播时将导致以ctrl键以主导的组合快捷键无法使用！！！！！

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [xxxily/h5player#439]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
1. **问题描述**

 如标题所示，当使用画中画模式播放其它网页的视频与直播时将无法使用如ctrl+c、ctrl+v与ctrl+f等一系列以ctrl为主导的组合快捷键，禁用本插件后即可正常使用。并且已经询问微软官方相关人员表示edge本身无此bug无论什么版本，详见：(https://answers.microsoft.com/zh-hans/microsoftedge/forum/msedge_video-msedge_win10/%e5%bd%93%e5%9c%a8edge%e6%b5%8f%e8%a7%88%e5%99%a8/d3a3ee7d-e532-462e-a25d-0b4a3a48fece)
2. **出现上述问题的地址**

全部支持画中画模式的所有网页
3. **你使用的浏览器与浏览器版本信息**

 edge   105.0.1343.27 (正式版本) (64 位)
4. **其他附注信息**


严重影响用户使用，请及早修复！

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
哈哈哈，那就请尽快修复一下这个问题吧大佬。
还有一个问题，就是放大视频画面这一功能可以一次性只加0.05吗？一次加0.1有点太大了画面。

**Comment by xxxily** [comment]
需要进行跨TAB控制就会出现这个问题，代码已经优化，但不能彻底修复，下个版本发布这部分优化后的代码就会跟着发布，后续再考虑加个禁止跨TAB控制的选项吧

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
> 需要进行跨TAB控制就会出现这个问题，代码已经优化，但不能彻底修复，下个版本发布这部分优化后的代码就会跟着发布，后续再考虑加个禁止跨TAB控制的选项吧

那么“放大视频画面这一功能可以一次性只加0.05吗？一次加0.1有点太大了画面。”这个功能建议可以实现吗大佬？

**Comment by xxxily** [comment]
> > 需要进行跨TAB控制就会出现这个问题，代码已经优化，但不能彻底修复，下个版本发布这部分优化后的代码就会跟着发布，后续再考虑加个禁止跨TAB控制的选项吧
> 
> 那么“放大视频画面这一功能可以一次性只加0.05吗？一次加0.1有点太大了画面。”这个功能建议可以实现吗大佬？

可以

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
> > > 需要进行跨TAB控制就会出现这个问题，代码已经优化，但不能彻底修复，下个版本发布这部分优化后的代码就会跟着发布，后续再考虑加个禁止跨TAB控制的选项吧
> > 
> > 
> > 那么“放大视频画面这一功能可以一次性只加0.05吗？一次加0.1有点太大了画面。”这个功能建议可以实现吗大佬？
> 
> 可以

万分感谢！

**Comment by xxxily** [comment]
最新版已对上述问题进行优化
