### ISSUE TITLE
介绍里又错别字 “倍数播放”

### ISSUE THREAD

**Issue by freeleefly** [xxxily/h5player#44]
感谢作者，看脚本，学习到很多。
想自己改点，适合下自己，又想保持更新，难受了。

**Comment by xxxily** [comment]
> 感谢作者，看脚本，学习到很多。
> 想自己改点，适合下自己，又想保持更新，难受了。

后面看下能不能提供自由点的自定义功能，目前的自定义还是不太适合用户使用
