### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mason-Greenwood-ssss** [xxxily/h5player#446]
### 浏览器内复制快捷键ctrl+c异常

1. **问题描述**
在edge开启画中画模式后，复制快捷键ctrl+c被劫持在视频所在网页，在edge的其他选项卡页面均无法使用ctrl+c快捷键。关闭本脚本后恢复正常。

2. **出现上述问题的地址**
所有网站

3. **你使用的浏览器与浏览器版本信息**
Microsoft edge，版本 105.0.1343.33 (正式版本) (64 位)

4. **其他附注信息**

**Comment by xxxily** [comment]
下个版本优化： https://github.com/xxxily/h5player/issues/439
