### ISSUE TITLE
B站视频上按空格不能暂停/播放

### ISSUE THREAD

**Issue by YandLiu** [xxxily/h5player#448]
Edge/Firefox+Tampermonkey
例：https://www.bilibili.com/video/BV1Eo4y1k7QA

**Comment by xxxily** [comment]
可能是B站特有的HEVC格式播放器导致的，建议切换其它格式试试

**Comment by YandLiu** [comment]
3种编码都试了，都有这个问题

**Comment by xxxily** [comment]
旧版本测试正常，最新版提升了兼容能力，升级下看能否解决你的问题，如果还不行请留意下控制台是否有啥报错信息

**Comment by YandLiu** [comment]
谢谢 更新后没问题了
