### ISSUE TITLE
关于截图功能

### ISSUE THREAD

**Issue by 1357310795** [xxxily/h5player#45]
能否支持截取png格式的图片？
jpg有损感觉不太舒服
谢谢作者啦，这个插件真的非常好用！

**Comment by xxxily** [comment]
> 能否支持截取png格式的图片？
> jpg有损感觉不太舒服
> 谢谢作者啦，这个插件真的非常好用！

PNG格式文件太大了，之前默认是PNG的，4K视频截图容易卡死，而且一张图就10几M，不太靠谱，后来改成了jpg，压缩率95%，不会损失太多
