### ISSUE TITLE
Video Speed problems [BUG]

### ISSUE THREAD

**Issue by fylexr** [xxxily/h5player#450]
1. **问题描述**
The player works great but the video plays at x2 speed (but still indicates the "normal" speed indicator in the parameters)

2. **出现上述问题的地址**
I had to disable the script for now because I cant change the speed of the video anymore.

3. **你使用的浏览器与浏览器版本信息**
Firefox 104.0.2 (64 bits) running on Windows 10

4. **其他附注信息**
none for now but ask me anything

**Comment by xxxily** [comment]
请提供具体的视频地址，否则没法定位问题

**Comment by xxxily** [comment]
缺乏有用信息，建议更新到最新版，相关问题或许已经得到解决

**Comment by fylexr** [comment]
Wow that was quick I could'nt even answer your last message wtf.

This problem isn't on a specific video it's on every video, it just plays at speed x2. And I dont know why.

Is there a log somewhere that I can show you ? + sterno900 says he/she has the same issue, I think it's worth checking.
