### ISSUE TITLE
[BUG]3.5.0 youtube 音量控制与播放器实际显示不统一

### ISSUE THREAD

**Issue by cantonadong** [xxxily/h5player#454]
播放器的被废弃了，只能用插件，这个跟之前逻辑不一样啊？
能不能统一？

**Comment by xxxily** [comment]
新版的播放器为了确保能对音量调节屏蔽的网站也能正常调音，所以做了底层接管，跟调速一样，不保证跟视频原来ui看到的保持一致，你只要使用一套调节系统就好了，没必要一会快捷键操作，一会鼠标操作
