### ISSUE TITLE
[BUG]特定网址截图键未生效

### ISSUE THREAD

**Issue by a419416951** [xxxily/h5player#458]
1. **问题描述**

截图键没有生效
2. **出现上述问题的地址**

https://www.ysjdm.net/

3. **你使用的浏览器与浏览器版本信息**

百分浏览器
4. **其他附注信息**

貌似只有这个网址的截图键无法生效

**Comment by xxxily** [comment]
网站禁止了下载和拷贝
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/3418704/192555355-00c62018-8086-47bd-af2e-16e1ef27826f.png">

**Comment by na82h2S96469793o** [comment]
微博视频也不能截图吗

**Comment by xxxily** [comment]
> 微博视频也不能截图吗

微博的可以截图啊，但不能自动下载
