### ISSUE TITLE
[BUG]百度网盘无法加速

### ISSUE THREAD

**Issue by xzw2935** [xxxily/h5player#459]
1. **问题描述**
无法加速百度网盘在线视频。

2. **出现上述问题的地址**
https://pan.baidu.com/play/video#

3. **你使用的浏览器与浏览器版本信息**
尝试了chrome和edge，黑红tempermonkey都用了，同样无法加速。测试其他网站正常。

4. **其他附注信息**
控制台信息：
h5player message:  获取tips的包裹容器异常<video id="html5player_html5_api" class="vjs-tech" autoplay="" preload="auto" tabindex="-1" role="application"></video>播放速度：2

**Comment by xxxily** [comment]
非百度会员可结合这个脚本使用，应该就能正常加速：https://greasyfork.org/zh-CN/scripts/441747

**Comment by lingtongwang** [comment]
> 非百度会员可结合这个脚本使用，应该就能正常加速：https://greasyfork.org/zh-CN/scripts/441747

感谢，完美解决问题
