### ISSUE TITLE
这个能兼容下火狐浏览器么:joy:

### ISSUE THREAD

**Issue by JingleDingDang** [xxxily/h5player#46]
能兼容下火狐浏览器么:joy:哪怕不支持全部功能，支持多少开放多少也行

**Comment by xxxily** [comment]
> 能兼容下火狐浏览器么😂哪怕不支持全部功能，支持多少开放多少也行

大部分功能都是兼容火狐的啊

**Comment by JingleDingDang** [comment]
我的火狐上发现这些脚本的快捷键都没有作用在微博上

**Comment by xxxily** [comment]
> 我的火狐浏览器打开微博，发现这脚本的快捷键都没起作用，也没发现脚本启用的UI显示什么的

你的火狐版本是不是太旧了？我这边测试了微博兼容没问题啊

**Comment by JingleDingDang** [comment]
75.0 (64 位)  
版本应该是没啥问题，或者是其他的快捷键什么的冲突了？我再试试吧，话说这个脚本会在浏览器上显示按钮什么的么

**Comment by xxxily** [comment]
> 75.0 (64 位)
> 版本应该是没啥问题，或者是其他的快捷键什么的冲突了？我再试试吧，话说这个脚本会在浏览器上显示按钮什么的么

没有任何按钮，你可以在其它网站多试试，大部分主流网站都是兼容的，如果都不行肯定是你的环境有问题
