### ISSUE TITLE
[BUG] weibo网页版看视频，全屏或网页全屏，按ESC退出后，直接跳回到网页顶部。

### ISSUE THREAD

**Issue by itheabyss** [xxxily/h5player#460]
1. **问题描述**
无论这个视频在网页的何处，比如一页有50条微博，第30条微博有视频，你点击播放，enter或shift+enter，全屏时要按两次ESC，网页全屏按一次ESC，然后会直接跳到页面的顶部，也就是第一条微博。不知道是什么原因。

期望是在哪里打开的视频，结束时也在哪里，网页不要乱跳。

2. **出现上述问题的地址**
weibo.com

3. **你使用的浏览器与浏览器版本信息**
Edge最新版：版本 105.0.1343.53 (正式版本) (64 位)
脚本是最新的3.5.3

4. **其他附注信息**
今天才用到这功能，以前的版本没试过这功能，所以不确定以前的版本会不会有这种问题。

**Comment by itheabyss** [comment]
作者大佬能不能参照一下这个脚本：https://greasyfork.org/zh-CN/scripts/4870-maximize-video

用过不少网页全屏的脚本，就这个暂时没发现问题，作者貌似不更新了。我现在碰到的网页全都可以正常使用。而且也不会出现我一楼说的问题。非常好用。如果能集成进去就最好了。

**Comment by doyoudo** [comment]
一样的问题，只是浏览器不同，我在微博，推特，都是跑到顶部第一条消息了
