### ISSUE TITLE
打开抖音 登录自己的账号 看自己发布的私密视频 点开说格式不支持 禁用这个插件 才能播放自己的视频 

### ISSUE THREAD

**Issue by J74w264399** [xxxily/h5player#462]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by J74w264399** [comment]
问题描述 打开抖音 登录自己的账号 看自己发布的私密视频 点开说格式不支持 禁用这个插件 才能播放自己的视频 
出现上述问题的地址 douyin.com
你使用的浏览器与浏览器版本信息 edge最新版 win10自带 
其他附注信息 看其他人的视频没有问题

**Comment by xxxily** [comment]
经测试，未能重现此问题
