### ISSUE TITLE
[BUG] Infinite Extension Reload on Certain Webpages

### ISSUE THREAD

**Issue by chen-jin021** [xxxily/h5player#463]
1. **问题描述**
This chrome extension reloads infinite times on certain webpages. It was found mostly on webpages where there are video ad banners. This caused my browser application to crash.

2. **出现上述问题的地址**
An example of such website: https://www.geeksforgeeks.org/what-are-hash-functions-and-how-to-choose-a-good-hash-function/

3. **你使用的浏览器与浏览器版本信息**
Chrome Browser Version 106.0.5249.91 (Official Build) (arm64)

4. **其他附注信息**

**Comment by xxxily** [comment]
在对应的网站上未能重现到该问题
