### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 13411067770** [xxxily/h5player#464]
1. **问题描述**
哔哩哔哩视频播放在第一次进度控制后（按键快进）全部失效，包括点击进度条，按键快进等

2. **出现上述问题的地址**
【【言语理解】《行测》——国考省考通用版本】 https://www.bilibili.com/video/BV1BD4y1Q7t8?p=8&share_source=copy_web&vd_source=5c6d164cd2082e61821b4d7906ba77ee

3. **你使用的浏览器与浏览器版本信息**
Microsoft Edge
版本 106.0.1370.34 (正式版本) (64 位)

4. **其他附注信息**
感谢开发者的实用插件

**Comment by xxxily** [comment]
用chrome测试正常，理论上Edge应该也正常
