### ISSUE TITLE
新版会造成B站持续卡顿[BUG]

### ISSUE THREAD

**Issue by itheabyss** [xxxily/h5player#465]
1. **问题描述**
B站直播会持续卡顿，大概5-10秒会卡一次，每次卡半秒到一秒左右会继续。换了各种备线，各种清晰度，完全没用。和网速无关。
**尝试禁用本脚本，非常流畅。**
B站视频没问题，其它网站暂时没发现问题。比如抖音直播之类的都正常。

2. **出现上述问题的地址**
B站直播

3. **你使用的浏览器与浏览器版本信息**
EDGE最新版，WIN11 22H2

4. **其他附注信息**
请问如何在B站暂时禁用这个？我不想禁用整个脚本，因为在其它网站正常。

**Comment by itheabyss** [comment]
暂时解决了，在下面代码加入disable这一行，先在直播页面禁用吧。
```
'live.bilibili.com': {
    disable: true,
```

**Comment by xxxily** [comment]
直播的时候将倍速跳回1.x的倍速即可，因为不可能提前获取到还没传输过来的视频流，所以大于1.x的倍速会导致持续缓冲不过来而不断卡顿

**Comment by twzchi** [comment]
> 暂时解决了，在下面代码加入disable这一行，先在直播页面禁用吧。
> 
> ```
> 'live.bilibili.com': {
>     disable: true,
> ```

禁用干啥呀！！直接改下播放模式即可解决问题：
改成AVC模式，不要默认HEVC ~~~

**Comment by itheabyss** [comment]
> 

还真是这个原因。可能是之前看视频调成了1.2倍速，没有调回来。然后就一直默认是1.2了。

我也根本没想到这个原因，以为是关掉页面会恢复1.0的，所以当时重启浏览器，重启电脑都没用，根本不知道视频是以1.2倍速播放的，还以为是BUG。

**Comment by itheabyss** [comment]
> 直播的时候将倍速跳回1.x的倍速即可，因为不可能提前获取到还没传输过来的视频流，所以大于1.x的倍速会导致持续缓冲不过来而不断卡顿

还真是这个原因。可能是之前看视频调成了1.2倍速，没有调回来。然后就一直默认是1.2了。

我也根本没想到这个原因，以为是关掉页面会恢复1.0的，所以当时重启浏览器，重启电脑都没用，根本不知道视频是以1.2倍速播放的，还以为是BUG。
