### ISSUE TITLE
请求增加一个，按空格控制视频播放暂停的功能

### ISSUE THREAD

**Issue by noneaddress** [xxxily/h5player#467]
请求增加一个，按空格控制视频播放暂停的功能！就如同B站原生的快捷键那样。
感谢您开发的脚本！

**Comment by xxxily** [comment]
默认就是支持按空格键播放暂停的，如果你访问的网址不支持，可以将网址贴出来，我看下是什么原因导致的不支持

**Comment by stormjing** [comment]
您好！mac safari 下开启扩展 b 站空格暂停就不能用了。
bilibili.com
