### ISSUE TITLE
没有找到如何自定义快捷键

### ISSUE THREAD

**Issue by Saafo** [xxxily/h5player#47]
快捷键和自己习惯的键位不是很符合，希望能够自定义键位。在Changelog里看到有说支持自定义键位，但实在没有找到在哪里自定义。还望明示。

**Comment by xxxily** [comment]
> 快捷键和自己习惯的键位不是很符合，希望能够自定义键位。在Changelog里看到有说支持自定义键位，但实在没有找到在哪里自定义。还望明示。

需要通过修改代码进行自定义，不是很方便，还是等后续优化后再自定义快捷键吧
