### ISSUE TITLE
[BUG]部分域名的视频，无法网页全屏和屏幕全屏

### ISSUE THREAD

**Issue by h731233178** [xxxily/h5player#470]
1. **问题描述**
部分域名的视频，无法网页全屏和屏幕全屏

2. **出现上述问题的地址**
haokan.baidu.com、v.qq.com

3. **你使用的浏览器与浏览器版本信息**
百分浏览器

4. **其他附注信息**

**Comment by xxxily** [comment]
下个版本优化

**Comment by h731233178** [comment]
> 下个版本优化
1.v.qq.com域名空格暂停被播放器自动解开。
2.https://www.o8tv.com/vodplay/375260-1-229.html 刷新页面，xx播放速度提示会一直显示不消失
