### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by a419416951** [xxxily/h5player#471]
1. **问题描述**

脚本不断出现的序号是啥，会导致卡顿
2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

百分浏览器
4. **其他附注信息**

![`@1E9U %A4M%B _2BHX5}OH](https://user-images.githubusercontent.com/55371090/194982806-1a9fa494-58e4-42f4-8c2c-830c9e1c88b8.png)

**Comment by xxxily** [comment]
你用的是什么浏览器插件？tampermonkey的话不会出现这个问题

**Comment by dontaskhy** [comment]
我也有遇到相同的问题，不过只在使用bilibili时序号会不断增加，其他网站都是5个，而且我是通过tampermonkey使用这个脚本的

**Comment by a419416951** [comment]
用的是Tampermonkey BETA

**Comment by melody11110** [comment]
我也有这个问题，而且也是用bilibili的时候会特别多序号，最多有两百多个，其他视频网站都是5个。我用的是TamperMonkey v4.18.0, 谢谢

**Comment by xxxily** [comment]
> 我也有这个问题，而且也是用bilibili的时候会特别多序号，最多有两百多个，其他视频网站都是5个。我用的是TamperMonkey v4.18.0, 谢谢

你用的是什么浏览器？关掉其它插件试试，这似乎是不断有外部网页被注入到你浏览的页面导致的
