### ISSUE TITLE
[BUG]使用左箭头无法重置到0:00

### ISSUE THREAD

**Issue by githubcatheaven** [xxxily/h5player#473]
这个文章里的视频时：https://www.wsj.com/articles/illegal-undocumented-migrant-immigrant-asylum-seeker-southern-border-biden-harris-nyc-tent-adams-desantis-bus-rule-of-law-11665609797?mod=latest_headlines

在播放到 0:04 时，按左箭头，反复在 0:01 和 0:03 之间切换，始终无法重置到 0:00 与预期不符，希望修复。

**Comment by xxxily** [comment]
感谢反馈，下个版本修复该问题
