### ISSUE TITLE
Make keybinds easier for the user 使用户更容易绑定键位

### ISSUE THREAD

**Issue by joeytwiddle** [xxxily/h5player#478]
Great script! I have two suggestions:

1. When the user presses `?` or `h` or `F1` key while focused on the video, display some help: a list of keybinds.

2. Provide four sets of keybinds, so the user can choose keybinds they are familiar with:

---

很棒的剧本！ 我有两个建议：

1. 当用户在专注于视频的同时按下`?`或`h`或`F1`键时，显示帮助：键绑定列表。

2. 提供四组键位，用户可以选择自己熟悉的键位：

---

```js
// Config
var keybindScheme = 'h5player'; // or 'youtube' or 'mplayer' or 'custom'

// Definitions
var keybindSchemes = {
    h5player: {
        toggleFullscreen: 'enter',
        decreasePlaybackRate: 'x',
        increasePlaybackRate: 'c',
        ...
    },
    youtube: {
        toggleFullscreen: 'f',
        decreasePlaybackRate: '<',
        increasePlaybackRate: '>',
        ...
    },
    mplayer: {
        toggleFullscreen: 'f',
        decreasePlaybackRate: '[',
        increasePlaybackRate: ']',
        ...
    },
    custom: {
        // Copy of h5player, but the user can put what they want here
        ...
    },
```

If you accept this idea, I can help you to build the keybind schemes. 如果您接受这个想法，我可以帮助您构建键绑定方案。

**Comment by xxxily** [comment]
有这样的打算，但一直没时间做这个功能

**Comment by xxxily** [comment]
已支持该功能，具体说明见：https://h5player.anzz.top/home/customConfiguration.html
