### ISSUE TITLE
有没有办法自己编辑脚本来禁止掉一些快捷键? 

### ISSUE THREAD

**Issue by rsyqvthv** [xxxily/h5player#48]
如果可行, 劳烦指导一下该怎么修改. 

比如我想将shift加方向键这一组全部禁用.

非常感谢.

**Comment by xxxily** [comment]
> 如果可行, 劳烦指导一下该怎么修改.
> 
> 比如我想将shift加方向键这一组全部禁用.
> 
> 非常感谢.

2003到2029行的代码删掉即可，或者你可以通过搜索“shift+”来查找相关代码

**Comment by rsyqvthv** [comment]
非常感谢. 我已经用 `/*...*/` 注释掉他们了. 

只是如果脚本更新, 是不是就需要重新设置了?

要是能有更好的办法进行设置就好了. 

我这里使用volentmonkey, 对每个脚本后面有变量设置, 不知道你可否利用这个来设置快捷键?

无论如何, 非常感谢你的脚本, 这是解救我这个经常看视频的人的最好工具.

**Comment by xxxily** [comment]
> 非常感谢. 我已经用 `/*...*/` 注释掉他们了.
> 
> 只是如果脚本更新, 是不是就需要重新设置了?
> 
> 要是能有更好的办法进行设置就好了.
> 
> 我这里使用volentmonkey, 对每个脚本后面有变量设置, 不知道你可否利用这个来设置快捷键?
> 
> 无论如何, 非常感谢你的脚本, 这是解救我这个经常看视频的人的最好工具.

这个后续看能不能提供一个禁用设置吧，要等配置界面出来才可以添加这个功能，由于是业余维护代码，所以预计还要一段时间才会增加UI设置界面

**Comment by Emphasia** [comment]
能独立网站禁用快捷键吗？有一些网站会有自己的默认快捷键..直接统一接管可能会有不方便..
