### ISSUE TITLE
[BUG]百度网盘播放视频不可调整倍速

### ISSUE THREAD

**Issue by ChristopherWLM** [xxxily/h5player#483]
1. **问题描述**
百度网盘播放视频，无法使用Z、X、C调整倍速（按ZXC都是一直显示倍速是1）但是键盘上的2还是会倍速播放。其他的控制都能用，唯独调整倍速失败了。一开始想配合Dplayer一起解决，结果用Dplayer无法加载视频

2. **出现上述问题的地址**
https://pan.baidu.com/

3. **你使用的浏览器与浏览器版本信息**
Google Chrome 107.0.5304.63 (正式版本) (64 位元)

4. **其他附注信息**
谢谢作者的热心分享！让我在备考路上减轻负担！

**Comment by xxxily** [comment]
百度盘的非会员用户建议结合：https://greasyfork.org/zh-CN/scripts/441747 这个脚本使用，即可实现倍速

**Comment by ChristopherWLM** [comment]
已解决，原来非会员设置720P无法加载，配合脚本降低清晰度即可，谢谢作者！

**Comment by ChristopherWLM** [comment]
您好，我是伟隆。我已收到您的邮件并将尽快处理，谢谢！
