### ISSUE TITLE
暂停视频播放 或 前进退后，会影响视设置的速度

### ISSUE THREAD

**Issue by whichone766** [xxxily/h5player#484]
1. **问题描述**
设置2倍速后，暂停或前后移动进度，速度会恢复为1倍速。

2. **出现上述问题的地址**
https://www.bilibili.com/video/BV1yP411E7TU/?spm_id_from=333.851.b_7265636f6d6d656e64.4&vd_source=1487fee6f618c31de8cfc6685effd230

3. **你使用的浏览器与浏览器版本信息**
edge 版本 106.0.1370.52 (正式版本) (x86_64)

4. **其他附注信息**

**Comment by xxxily** [comment]
我这边暂时没能复现到这个问题

**Comment by Pandrink** [comment]
我也发现有这个问题，有点难受
