### ISSUE TITLE
[BUG] Script is activated on the site w/o video

### ISSUE THREAD

**Issue by Schmarotzer** [xxxily/h5player#487]
1. The script is activated on the site without a video and it interferes with text input

2. https://translate.yandex.ru (site like translate.google.com)

3. Vivaldi browser v.5.5.2805.42 stable

4. Script version: 3.6.1 
   OS: Kubuntu 22.04
   JavaScript | V8 10.6.194.23
   User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by xxxily** [comment]
脚本也支持音频，所以会被激活，建议在该网站上单独禁用掉脚本
