### ISSUE TITLE
请教，我交换了Ctrl+↑和↑的效果，但在B站遇到了一些问题？

### ISSUE THREAD

**Issue by KKFantasy** [xxxily/h5player#49]
感谢作者，插件非常好用。

```js
//因为mac快捷键冲突，我改成了alt键
//音量10%比较常用，所以我交换了两个操作的效果

// alt+方向键上↑：音量升高 1%
if (event.altKey && keyCode === 38) {
t.setVolume(0.01);
}
// 方向键下↓：音量降低 1%
if (event.altKey && keyCode === 40) {
t.setVolume(-0.01);
}

// 方向键上↑：音量升高 10%
if (keyCode === 38) {
t.setVolume(0.1);
}
// 方向键下↓：音量降低 10%
if (keyCode === 40) {
t.setVolume(-0.1);
}
```

原本建的键位下`↑`和`ctrl+↑`会覆盖B站自己的快捷键效果。而当我修改后只有`↑`可以，而`alt+↑`会和B站自身的快捷键同时生效，从而导致每次都会步进11%。

请问这个问题要怎么解决，谢谢。

**Comment by xxxily** [comment]
> 感谢作者，插件非常好用。
> 
> ```js
> //因为mac快捷键冲突，我改成了alt键
> //音量10%比较常用，所以我交换了两个操作的效果
> 
> // alt+方向键上↑：音量升高 1%
> if (event.altKey && keyCode === 38) {
> t.setVolume(0.01);
> }
> // 方向键下↓：音量降低 1%
> if (event.altKey && keyCode === 40) {
> t.setVolume(-0.01);
> }
> 
> // 方向键上↑：音量升高 10%
> if (keyCode === 38) {
> t.setVolume(0.1);
> }
> // 方向键下↓：音量降低 10%
> if (keyCode === 40) {
> t.setVolume(-0.1);
> }
> ```
> 
> 原本建的键位下`↑`和`ctrl+↑`会覆盖B站自己的快捷键效果。而当我修改后只有`↑`可以，而`alt+↑`会和B站自身的快捷键同时生效，从而导致每次都会步进11%。
> 
> 请问这个问题要怎么解决，谢谢。

需要阻止事件冒泡，才能阻止事件被原逻辑捕获：event.stopPropagation()  
后面再优化下，把它默认改为调10%，默认1%值太小了，不明显

**Comment by KKFantasy** [comment]
好的好的，谢谢。

还有一个不大的问题，斗鱼用回车切换全屏时第一次点击图像会偏移到左上四分之一处，再按一次就正常了。退出全屏也是要按两下。
我关掉了另一个斗鱼相关的脚本和stylus样式后测试还是这样。
