### ISSUE TITLE
This error's showing in chrome 'manage extension> Tampermonkey> collect error.'

### ISSUE THREAD

**Issue by spidy2356** [xxxily/h5player#492]
1. **问题描述**
Unchecked runtime.lastError: Cannot create item with duplicate id 70e159e0-b903-4731-927b-81fc476e1132
%c h5player message: color: white; background-color: #D33F49 defineProperty error: TypeError: Cannot redefine property: rwt
%c h5player message: color: white; background-color: #D33F49 defineProperty error: TypeError: Cannot redefine property: rwt
%c h5player message: color: white; background-color: #D33F49 defineProperty error: TypeError: Cannot redefine property: rwt
%c h5player message: color: white; background-color: #D33F49 defineProperty error: TypeError: Cannot redefine property: rwt
%c h5player message: color: white; background-color: #D33F49 defineProperty error: TypeError: Cannot redefine property: rwt
Unchecked runtime.lastError: Cannot create item with duplicate id 32ad03e9-fbcc-457d-9e48-1e390f2881c1

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**
Version 107.0.5304.106 (Official Build) (64-bit), Chrome browser and extension Tampermonkey v4.18.0

4. **其他附注信息**

**Comment by xxxily** [comment]
以上信息对定位BUG毫无帮助
