### ISSUE TITLE
对ckplayer支持有问题

### ISSUE THREAD

**Issue by sojey** [xxxily/h5player#50]
https://www.agefans.tv/play/20190210?playid=2_24

我发现几乎所有chrome的插件，对ckplayer的支持，尤其是截图功能的支持基本都不兼容。

我测试了 HTML5视频播放器增强脚本 3.2.3   上一帧、下一帧，可以跳帧，但跳帧后会继续自动播放。

视频截屏完全没用。

每次处理这个网站的播放器都极其困难，只有把资源下载硬盘后用potplayer处理跳帧截图的问题。很麻烦。

希望能够尽快支持。谢谢。

**Comment by xxxily** [comment]
> https://www.agefans.tv/play/20190210?playid=2_24
> 
> 我发现几乎所有chrome的插件，对ckplayer的支持，尤其是截图功能的支持基本都不兼容。
> 
> 我测试了 HTML5视频播放器增强脚本 3.2.3 上一帧、下一帧，可以跳帧，但跳帧后会继续自动播放。
> 
> 视频截屏完全没用。
> 
> 每次处理这个网站的播放器都极其困难，只有把资源下载硬盘后用potplayer处理跳帧截图的问题。很麻烦。
> 
> 希望能够尽快支持。谢谢。

最新代码已支持ckplayer截图和取帧操作，但还需多测试一段时间才会发布新版本，如果你想先体验可以自行先更新：https://raw.githubusercontent.com/xxxily/h5player/master/dist/h5player.js
