### ISSUE TITLE
[BUG]b站进度条为什么拖不动呀？[・ヘ・?]

### ISSUE THREAD

**Issue by Geebar18** [xxxily/h5player#502]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by leic4u** [comment]
+1 方向键也失灵了

**Comment by rainbow2man** [comment]
直至今天上面两个问题还没修。。。不过人家免费无可厚非
