### ISSUE TITLE
[BUG]部分学习网站有进度条记录跟视频倒计时记录时加速无效

### ISSUE THREAD

**Issue by vip1314** [xxxily/h5player#517]
![网页捕获_23-2-2023_203947_www hnsydwpx cn](https://user-images.githubusercontent.com/25585053/220908525-84af5366-5974-489f-9e4e-81d8d9ff6471.jpeg)

1. **问题描述**
只能加速视频中的播放时间，视频实际画面没改变，学习记录进度条，倒计时都没改变

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by xxxily** [comment]
刷课请详细阅读插件说明
