### ISSUE TITLE
Netflix画中画模式没法显示字幕

### ISSUE THREAD

**Issue by mattliu007** [xxxily/h5player#52]
这个问题麻烦看下，不知道能不能解决

**Comment by xxxily** [comment]
> 这个问题麻烦看下，不知道能不能解决

这个功能支持不了，画中画是浏览器单独处理的，Netflix的字幕是通过其它元素标签呈现，视频和字幕两者是完全分离的，除非浏览器本身支持对其它元素进行画中画呈现，否则不可能实现得了
