### ISSUE TITLE
请求添加：一键切换剧场模式

### ISSUE THREAD

**Issue by xQoox** [xxxily/h5player#529]
1. **问题描述**
请求添加功能，一键切换剧场模式
譬如油管，默认按「t」以相互切换剧场模式及普通模式
希望在西瓜视频、B站也可如此

2. **出现上述问题的地址**
西瓜视频、B站

3. **你使用的浏览器与浏览器版本信息**
Edge

4. **其他附注信息**
无

**Comment by xxxily** [comment]
建议通过自定义配置，自行定制下即可，具体可见：https://h5player.anzz.top/home/customConfiguration.html
