### ISSUE TITLE
使用脚本在B站对视频进行倍速播放的情况下，在用键盘左右键快进或后退时，倍速播放会失效

### ISSUE THREAD

**Issue by CC7K** [xxxily/h5player#53]
如题，使用脚本在B站对视频进行倍速播放的情况下，在用键盘左右键快进或后退时，倍速播放会失效，希望解决修复，谢谢

**Comment by xxxily** [comment]
> 如题，使用脚本在B站对视频进行倍速播放的情况下，在用键盘左右键快进或后退时，倍速播放会失效，希望解决修复，谢谢

我这边测试没有这种情况，请问你用的是什么浏览器？是整个B站都这样还是只是某些页面下的视频会这样？

**Comment by CC7K** [comment]
![image](https://user-images.githubusercontent.com/63133923/78745553-0cccea80-7997-11ea-874d-184f65f57e26.png)
使用的是百分浏览器，tampermonkey v4.9。仅开启这一个脚本，b站全站都是这个情况。在快进快退后，倍速（0.5/0.75/1.5/2倍速全部失效）播放会失效。例如倍速档位仍显示2倍速，但实际是正常播放，需要手动再次选择2倍速播放。

**Comment by xxxily** [comment]
> ![image](https://user-images.githubusercontent.com/63133923/78745553-0cccea80-7997-11ea-874d-184f65f57e26.png)
> 使用的是百分浏览器，tampermonkey v4.9。仅开启这一个脚本，b站全站都是这个情况。在快进快退后，倍速（0.5/0.75/1.5/2倍速全部失效）播放会失效。例如倍速档位仍显示2倍速，但实际是正常播放，需要手动再次选择2倍速播放。

用你这个浏览器也测试过了，是正常的，脚本你用的是最新版吗？

**Comment by CC7K** [comment]
是最新的脚本，十分感谢大佬，我自己再去排查一下，十分感谢
