### ISSUE TITLE
[BUG]与Global Speed冲突

### ISSUE THREAD

**Issue by xzh767** [xxxily/h5player#537]
1. **问题描述**
<与Global Speed的d,a,s快捷键冲突,而且会卡死网页>

2. **出现上述问题的地址**
<http(s)://*/*/>

3. **你使用的浏览器与浏览器版本信息**
<EMicrosoft Edge
版本 112.0.1722.39 (正式版本) (64 位)>

4. **其他附注信息**
<没了>

**Comment by xxxily** [comment]
不建议两个同类型的脚本一起使用，冲突是没法避免的
