### ISSUE TITLE
[BUG]newbing回车网页黑屏，文心一言总是跳转欢迎页

### ISSUE THREAD

**Issue by CJCchester** [xxxily/h5player#538]
1. **问题描述**

  newbing点击回车发送聊天消息会造成网页黑屏，感觉是把聊天页面识别成视频了，回车视频全屏。。
  一访问文心一言也就是https://yiyan.baidu.com ，总是跳转欢迎页https://yiyan.baidu.com/welcome ，而我关闭脚本后，这个问题不再出现。
  
2. **出现上述问题的地址**

newbing：https://www.bing.com/search?q=Bing+AI
文心一言：https://yiyan.baidu.com/
文心一言欢迎页：https://yiyan.baidu.com/welcome
3. **你使用的浏览器与浏览器版本信息**

360极速浏览器X | 21.0.1200.0 (正式版本) （64 位）
内核Chrome/95.0.4638.69
油猴脚本
4. **其他附注信息**

之前一直用exclude解决。。每次更新都要写一次

**Comment by 1353604736** [comment]
同样问题

**Comment by ProgrammerSakura** [comment]
哎呀，刚准备来提issue，同样问题，文心一言会自动刷新。

**Comment by xxxily** [comment]
最新版已修复该问题
