### ISSUE TITLE
腾讯微云屏蔽了这个脚本，希望能解决这个问题，开了微云会员不能倍数很难受

### ISSUE THREAD

**Issue by git12343423423** [xxxily/h5player#54]
我一安装使用这个脚本去播放微云里面的视频，腾讯微云就显示浏览器不支持播放该格式视频，请安装腾讯微云APP观看，关闭了就可以正常观看视频

**Comment by git12343423423** [comment]
现在用的是谷歌插件，微云可以正常用，但是占资源啊

**Comment by xxxily** [comment]
> 我一安装使用这个脚本去播放微云里面的视频，腾讯微云就显示浏览器不支持播放该格式视频，请安装腾讯微云APP观看，关闭了就可以正常观看视频

把这句【player.setAttribute('crossorigin', 'anonymous')】删掉即可，或者先用着3.2.3版本，下个版本发布的时候会增加这个网站的兼容

**Comment by xxxily** [comment]
> 我一安装使用这个脚本去播放微云里面的视频，腾讯微云就显示浏览器不支持播放该格式视频，请安装腾讯微云APP观看，关闭了就可以正常观看视频

最新版本已经把问题修复了
