### ISSUE TITLE
作者您好, 进行 播放速度倍数 和 音量加减的时候, 能不能字体调大一些!

### ISSUE THREAD

**Issue by chenzhihao1040728129** [xxxily/h5player#549]
作者您好, 
进行 播放速度 和 音量加减的时候, 能不能字体调大一些!  
电脑连接投影仪, 坐远了, 进行 播放速度倍数 和 音量加减的时候字体太小, 看不清楚!....

**Comment by grayren** [comment]
5457行  fontSize: 16,
