### ISSUE TITLE
微博（未登录）shift p小窗看视频，一往下滑动视频就暂停

### ISSUE THREAD

**Issue by likewhale** [xxxily/h5player#55]
微博（未登录）shift p小窗看视频，一往下滑动视频就暂停，然后点继续，再滑动又暂停

**Comment by xxxily** [comment]
> 微博（未登录）shift p小窗看视频，一往下滑动视频就暂停，然后点继续，再滑动又暂停

应该是只有某些置顶或banner上的视频才会吧，滚动到下方，然后暂停，这个我后面想下该怎么兼容

**Comment by likewhale** [comment]
> > 微博（未登录）shift p小窗看视频，一往下滑动视频就暂停，然后点继续，再滑动又暂停
> 
> 应该是只有某些置顶或banner上的视频才会吧，滚动到下方，然后暂停，这个我后面想下该怎么兼容

不是置顶的，因为微博的是视频是你滑动到哪里哪个视频就自动播放，我在把上一个视频小窗后划着浏览到了其他视频，小窗的视频就暂停了，然后正好看到的那个视频开始自动播放了（非小窗），就是第二个视频的自动播放挤停了第一个，感谢大佬
