### ISSUE TITLE
[BUG] 谷歌浏览器使用此脚本打开哔哩哔哩首页一段时间浏览器卡死

### ISSUE THREAD

**Issue by chuchuaner** [xxxily/h5player#553]
1. **问题描述**
B站使用本脚本会导致内存泄露，导致浏览器卡死，目前最严重的是B站首页，不打开B站首页，只看视频无论多少个视频都没事，但是打开B站首页，十几分钟后，哪怕就单独一个标签页，也会爆内存卡死

2. **出现上述问题的地址**
https://www.bilibili.com/

3. **你使用的浏览器与浏览器版本信息**
Chrome 114.0.5735.90

**Comment by nmpassthf** [comment]
在Tampermonkey中的脚本设置里，`User excludes` 选项中添加  `https://www.bilibili.com/` 应该可以解决此问题

**Comment by Eric-lHHI** [comment]
很久之前就发现长时间开着B站首页看视频会内存泄露，原来是这个脚本的问题吗，我还以为是B站的问题😮

**Comment by juicemock** [comment]
> 在Tampermonkey中的脚本设置里，`User excludes` 选项中添加 `https://www.bilibili.com/` 应该可以解决此问题

具体怎么操作呢？ 我在油猴（Tampermonkey）没有找到这个User excludes，我尝试加入了黑名单 但是其他哔站视频就无法启用这个油猴了

**Comment by chuchuaner** [comment]
![QQ截图20230613101814](https://github.com/xxxily/h5player/assets/71181305/02a7640d-40cc-4926-a0de-f4e406056499)

**Comment by juicemock** [comment]
> ![QQ截图20230613101814](https://user-images.githubusercontent.com/71181305/245332451-02a7640d-40cc-4926-a0de-f4e406056499.png)

非常感谢
