### ISSUE TITLE
[BUG]B站按下空格键无法播放以及暂停视频

### ISSUE THREAD

**Issue by talentam** [xxxily/h5player#557]
1. **问题描述**
B站按下空格键无法播放以及暂停视频

2. **出现上述问题的地址**
https://www.bilibili.com/

3. **你使用的浏览器与浏览器版本信息**
Chrome 114.0.5735.199（正式版本） （64 位）
4. **其他附注信息**
在Youtube可以正常使用，空格也可以控制播放以及暂停

**Comment by Fujiwara-Chika** [comment]
我这里是 bilibili 正常，但是 Youtube 有毛病
