### ISSUE TITLE
bilibili的播放器拖动音量条和进度条有问题

### ISSUE THREAD

**Issue by 1357310795** [xxxily/h5player#56]
[bandicam 2020-04-11 12-42-01-370.zip](https://github.com/xxxily/h5player/files/4464055/bandicam.2020-04-11.12-42-01-370.zip)
录屏如上，概括一下就是点击slider后slider的滑块会一直跟随鼠标，不会停下来。

**Comment by xxxily** [comment]
> [bandicam 2020-04-11 12-42-01-370.zip](https://github.com/xxxily/h5player/files/4464055/bandicam.2020-04-11.12-42-01-370.zip)
> 录屏如上，概括一下就是点击slider后slider的滑块会一直跟随鼠标，不会停下来。

最新版已修复了该问题，你更新看下还会不会

**Comment by 1357310795** [comment]
> > [bandicam 2020-04-11 12-42-01-370.zip](https://github.com/xxxily/h5player/files/4464055/bandicam.2020-04-11.12-42-01-370.zip)
> > 录屏如上，概括一下就是点击slider后slider的滑块会一直跟随鼠标，不会停下来。
> 
> 最新版已修复了该问题，你更新看下还会不会

没问题了，谢谢修复😁
