### ISSUE TITLE
tiktok上，如何部分屏蔽快捷键？

### ISSUE THREAD

**Issue by githubcatheaven** [xxxily/h5player#560]
tiktok上， 键盘上下是换视频。
这2个我需要用网站的，
其他的还用插件的。

**Comment by xxxily** [comment]
建议进行自定义快捷键，可以通过菜单的【全局设置】里对不需要的快捷键屏蔽掉，也可以通过自定义配置来实现，具体见：https://h5player.anzz.top/home/customConfiguration.html
