### ISSUE TITLE
需求123 和 插件Global Speed

### ISSUE THREAD

**Issue by cjcchester** [xxxily/h5player#561]
现在脚本存在最大的问题就是，无法完美的获取视频实例。
有时候要点击视频获取焦点才能进行操作。
而且不同的地方有不同的视频层级，时不时某个页面脚本就无法获取到实例去进行操作，然后疯狂报错，导致卡死。

当然有些功能可能确实是要获取到焦点才行，比如视频截图、上一帧、镜像等等。

但是有些功能，我发现一个插件Global Speed，好像可以直接操作当前标签页的播放倍速和音量增益，至少在b站，我把焦点移到视频外，然后快捷键进行 调速、音量变化、进度移动 依然是可以实现的，而且很轻松。

插件主页：https://github.com/polywock/globalSpeed 
再放两张插件的设置图：
![image](https://github.com/xxxily/h5player/assets/87079803/28435643-9b81-4641-9082-d5474d0c5690)

![image](https://github.com/xxxily/h5player/assets/87079803/d632e6c9-2e32-48f8-a4cc-42f628ea9c4c)

该插件应当也实现了快捷键互斥，至少我添加的快捷键num2 2倍速肯定是覆盖了b站的音量-。

总之，我不知道脚本是否能捕获选项卡，如果不能，作者或许可以考虑转而开发成一个插件了

**Comment by xxxily** [comment]
最新版本应该已修复该问题，如果还是异常建议新开issues或到群里反馈下
