### ISSUE TITLE
希望增加每个视频单独记录播放速度功能！

### ISSUE THREAD

**Issue by yigexuezha** [xxxily/h5player#562]
希望增加每个视频单独记录播放速度功能！
比如开两个网页长视频，一个想要2倍速播放，一个想要3倍速播放。
我在一个网页视频里调速度，另一个网页视频速度也会改变。
我想要两个播放速度互不影响，希望作者大大能添加，谢谢！

**Comment by xxxily** [comment]
需求太小众，暂不考虑，抱歉
