### ISSUE TITLE
[BUG]油管使用键盘空格控制时画面一直转圈

### ISSUE THREAD

**Issue by zyt0002** [xxxily/h5player#568]
rt，使用空格暂停后必须再使用鼠标左键点击播放，如果使用空格则视频画面会一直转圈（视频正常播放）
![image](https://github.com/xxxily/h5player/assets/62917168/93f35b78-6d75-4333-b904-79b802a44e5a)
此时视频还在播放，但是鼠标的逻辑无法暂停播放

**Comment by zjcxdcq** [comment]
我也是 ，一个个测试过来发现是这个的问题。

**Comment by guojinhuei** [comment]
同样的问题。Chrome Version 118.0.5993.90 (Official Build) (64-bit)

**Comment by Mithcell-Ma** [comment]
原来是这个脚本的锅啊,我一直以为是其他脚本的呢,各位有解决方法了吗?

**Comment by xxxily** [comment]
已修复，请更新到最新版本

**Comment by zwu142569** [comment]
按住Ctrl+空格键就行
