### ISSUE TITLE
用来刷在线教育课程可以吗？还有点bug

### ISSUE THREAD

**Issue by 565183649** [xxxily/h5player#57]
视频加速可以，时间到了后会显示完成，但是刷新一下网页后发现课程时间完成数据并未存储，还是正常的时间，方便看看怎么调试一下吗？这老师讲课太慢了。。。。。鼠标也有检测，如果半天鼠标不动了就先是有点像是“关灯”效果是的，然后就弹出个小提示问你还在不在，关灯效果和弹窗出现的时候视频走的时间是不计入学习时间的。
[http://jl.wlpxks.com/learning/LessonDetailAdvanced.jspx?course_id=af07255e-6c9f-4096-97d7-197f23537109&id=ee2a9140-7966-4252-af92-e0a7f5b2fa0e](url)

**Comment by xxxily** [comment]
> 视频加速可以，时间到了后会显示完成，但是刷新一下网页后发现课程时间完成数据并未存储，还是正常的时间，方便看看怎么调试一下吗？这老师讲课太慢了。。。。。鼠标也有检测，如果半天鼠标不动了就先是有点像是“关灯”效果是的，然后就弹出个小提示问你还在不在，关灯效果和弹窗出现的时候视频走的时间是不计入学习时间的。
> [http://jl.wlpxks.com/learning/LessonDetailAdvanced.jspx?course_id=af07255e-6c9f-4096-97d7-197f23537109&id=ee2a9140-7966-4252-af92-e0a7f5b2fa0e](url)

没有账号没法调试

**Comment by 565183649** [comment]
我把账号给你把，则么给？邮箱还是哪里？

**Comment by xxxily** [comment]
> 我把账号给你把，则么给？邮箱还是哪里？

ankvps#foxmail.com(把#替换成@)，纯粹是研究下检测技术，不保证兼容

**Comment by 565183649** [comment]
OKOK,感谢

**Comment by 565183649** [comment]
已发，请查收

**Comment by xxxily** [comment]
> 已发，请查收

要持续挂机自动完成并不难，懂点代码的，自己写个脚本定时运行下doActive()，或reportTime2(20)即可，要想通过这个插件加速完成进度应该是不行的，服务端有时长验证
