### ISSUE TITLE
[BUG]抖音网页版bug

### ISSUE THREAD

**Issue by Arsiendle** [xxxily/h5player#575]
抖音网页版使用zxc或者Q等快捷键时,会出现视频画面卡住但进度条继续往前走,之后便是轻微的音画不同步,以及如果用Q复位,就会导致整个视频黑的,什么都看不见但能听见声音

**Comment by xxxily** [comment]
没发现此问题，建议更新到最新版本看下是否解决了你的问题，如果还是异常可以到群里反馈下，最近有时间，可以修复下
