### ISSUE TITLE
[BUG]在B站网页播放时，双击页面任何空白处会增加视频播放倍速0.1

### ISSUE THREAD

**Issue by hrcomm-fy** [xxxily/h5player#577]
1. **问题描述**
<在B站网页播放时，双击页面任何空白处户增加视频播放倍速0.1>

2. **出现上述问题的地址**
<https://www.bilibili.com/video/BV1vw411W7tR/?spm_id_from=333.1007.tianma.1-1-1.click>

3. **你使用的浏览器与浏览器版本信息**
<Brave 
[版本 1.60.118 Chromium: 119.0.6045.163（正式版本） （64 位）]>

4. **其他附注信息**

**Comment by xxxily** [comment]
没发现此问题，请更新到最新版本再试下，看是否已经被修复了
