### ISSUE TITLE
YouTube的播放暂停按钮，bug

### ISSUE THREAD

**Issue by yangchen158158** [xxxily/h5player#578]
类似www.youtube.com/watch?v=vz8c6kKizG4
重复按空格键（播放暂停，有明显bug），他这个YouTube 播放暂停按钮 还是显示暂停状态，但是视频还在播放，这个弹框 一直下不去！只有手动按！
YouTube的播放暂停按钮， 才能正常 隐藏回去、
 这个有办法修复吗？
![image](https://github.com/xxxily/h5player/assets/62718910/7ed304de-bfa0-4f3c-9f87-524bf9db20fa)

**Comment by t344885771** [comment]
同样遇到这个问题，这样卡住之后，字幕也会卡住，导致看视频播放特别不方便，只有暂停后用鼠标点击图标才能恢复

**Comment by t344885771** [comment]
在全局设置里面把那个空格切换暂停播放给禁用就好了，设置完成的时候记得点左上角保存设置才会生效在 2023年11月27日，下午8:58，guojinhuei ***@***.***> 写道：﻿

同样遇到这个问题，这样卡住之后，字幕也会卡住，导致看视频播放特别不方便，只有暂停后用鼠标点击图标才能恢复

是的 字幕也会卡住 唉

**Comment by guojinhuei** [comment]
非常感谢您。
谢谢提醒，根据您的建议，完美解决问题了。
祝：一切都好

t344885771 ***@***.***> 於 2023年11月27日週一 下午10:01寫道：

**Comment by t344885771** [comment]
客气了发自我的 iPhone在 2023年12月2日，下午12:24，guojinhuei ***@***.***> 写道：﻿
非常感谢

**Comment by studentluo** [comment]
+1

**Comment by xiaotianxt** [comment]
> 在全局设置里面把那个

你好，请教一下这个全局设置播放暂停的按钮在哪里呢，点击脚本的 Global Settings 之后没有看到：

![CleanShot 2023-12-16 at 20 17 34@2x](https://github.com/xxxily/h5player/assets/17041194/46fd3986-b122-4437-a1f4-bf49204ebce2)

**Comment by 0Tune** [comment]
![image](https://github.com/xxxily/h5player/assets/117656686/f1161ef0-3df8-47c2-a1f8-f07a192ea0f3)
这个全局设置

**Comment by 0Tune** [comment]
> > 在全局设置里面把那个
> 
> 你好，请教一下这个全局设置播放暂停的按钮在哪里呢，点击脚本的全局设置，后面没有：
> 
> ![CleanShot 2023-12-16 at 20 17 34@2x](https://private-user-images.githubusercontent.com/17041194/290991450-46fd3986-b122-4437-a1f4-bf49204ebce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzY1MjYsIm5iZiI6MTcwMjczNjIyNiwicGF0aCI6Ii8xNzA0MTE5NC8yOTA5OTE0NTAtNDZmZDM5ODYtYjEyMi00NDM3LWExZjQtYmY0OTIwNGViY2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDlmMDQ5NWEyZjNkZjIyYmY1ZDFkYzE1YWU3NjQ0NGE0OTJkYTkyYzdiMTU2MjNlYTkyZWUwZWI1ZDhlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ChnFSGbeVELCsZZtkCHwxhnLzXvnNu5kdAFbrlWykF4)

![image](https://github.com/xxxily/h5player/assets/117656686/2dae40ad-475a-4310-b832-97a884a96a9a)
这个全局设置

**Comment by 0Tune** [comment]
> > 在全局设置里面把那个
> 
> 你好，请教一下这个全局设置播放暂停的按钮在哪里呢，点击脚本的全局设置，后面没有：
> 
> ![CleanShot 2023-12-16 at 20 17 34@2x](https://private-user-images.githubusercontent.com/17041194/290991450-46fd3986-b122-4437-a1f4-bf49204ebce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzY1MjYsIm5iZiI6MTcwMjczNjIyNiwicGF0aCI6Ii8xNzA0MTE5NC8yOTA5OTE0NTAtNDZmZDM5ODYtYjEyMi00NDM3LWExZjQtYmY0OTIwNGViY2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDlmMDQ5NWEyZjNkZjIyYmY1ZDFkYzE1YWU3NjQ0NGE0OTJkYTkyYzdiMTU2MjNlYTkyZWUwZWI1ZDhlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ChnFSGbeVELCsZZtkCHwxhnLzXvnNu5kdAFbrlWykF4)

这个是Mac吧，我是用win+油猴的，点了这个全局设置就进去一个网页

**Comment by xxxily** [comment]
最新版已修复该问题
