### ISSUE TITLE
[BUG]网页全屏播放大部分网站无效

### ISSUE THREAD

**Issue by Sostay** [xxxily/h5player#583]
视频网页全屏大部分网站无效，包括YouTube…… 少部分正常工作的也是网站自己本身就有网页全屏功能的

**Comment by xxxily** [comment]
更新到最新版本试试？

**Comment by xxxily** [comment]
> 视频网页全屏大部分网站无效，包括YouTube…… 少部分正常工作的也是网站自己本身就有网页全屏功能的

请列出具体无效的网站，以便进行问题排查
