### ISSUE TITLE
[BUG] 在部分网站中操作点击视频窗口（获得焦点）后所有快捷键无效

### ISSUE THREAD

**Issue by SineObama** [xxxily/h5player#589]
1. **问题描述**
例如鼠标点击过视频触发暂停/播放时，我的理解是视频获取了焦点，此时无法使用所有的快捷键；鼠标点击网页视频之外的位置后，快捷键可以使用。

2. **出现上述问题的地址**
https://www.nyafun.net/play/5848-1-5.html
https://www.555yy1.com/vodplay/438925-3-1.html

3. **你使用的浏览器与浏览器版本信息**
360极速浏览器X 22.1.1073.64 内核 119.0.6045.160

4. **其他附注信息**
我不清楚插件具体工作方式，但我原本用的浏览器插件 [video speed controller](https://github.com/igrigorik/videospeed) ，包括我fork的他人重构版本 [videospeed-refactoring-myfullscreen](https://github.com/SineObama/videospeed-refactoring-myfullscreen) ，虽然只能通过禁用网页快捷键`event.preventDefault();event.stopPropagation();`的方式处理快捷键冲突，但可以正常支持。

**Comment by xxxily** [comment]
查了下，底层逻辑存在一些问题，导致iframe的视频快捷键透传出现异常，该问题会在下个版本修复，感谢反馈。
