### ISSUE TITLE
请问可以关闭自动播放(B站)吗？

### ISSUE THREAD

**Issue by oatall** [xxxily/h5player#6]
b站默认是需要手动点击才播放的。
脚本开启后，b站进入视频详情页会自动播放。
习惯用手动播放。

**Comment by xxxily** [comment]
> b站默认是需要手动点击才播放的。
> 脚本开启后，b站进入视频详情页会自动播放。
> 习惯用手动播放。

尴尬，我习惯了自动播放，你可以通过注释：autoPlay: '.bilibili-player-video-btn-start' 这一句来禁止自动播放
