### ISSUE TITLE
[BUG] Youtube不显示版本4.0.0里更新的UI

### ISSUE THREAD

**Issue by zhangfangzhou01** [xxxily/h5player#604]
1. **问题描述**

Youtube不能显示该插件4.0.0版本的UI
2. **出现上述问题的地址**

任意一个youtube视频，例如
https://www.youtube.com/watch?v=p-mDQH2Rqb8
3. **你使用的浏览器与浏览器版本信息**

Chrome Stable (121.0.6167.185)
4. **其他附注信息**

任意打开一个youtube视频，第一次控制台会报
Failed to execute 'define' on 'CustomElementRegistry': the name "sl-popup" has already been used with this registry
疑似youtube也用了shoelace组件导致插件里的标签注册失败
后面有缓存后开始报
Uncaught Error: Constructing sl-menu: TypeError: Class constructors cannot be invoked without 'new'
并且由于每帧都重绘，导致控制台爆炸

**Comment by xxxily** [comment]
油管上确实很多问题，兼容起来也很费劲，如果用不到UI界面，建议油管先关闭UI界面，后面有解决方案了，会优化相关代码

**Comment by xxxily** [comment]
> > 油管上确实很多问题，兼容起来也很费劲，如果用不到UI界面，建议油管先关闭UI界面，后面有解决方案了，会优化相关代码
> 
> 好的，希望作者把“禁用图形用户页面”的选项添加到展开的registerMenu以及自定义设置界面里面。 去其他UI显示正常的界面，比如bilibili，然后在UI的设置里设置“全局禁用图形用户界面”有些反直觉了

主要是展开菜单选项太多了，有了UI界面，很多选项都放在UI里去控制了，不过图形这个兼容还很多问题，确实可以考虑放到展开菜单里

**Comment by iamqiz** [comment]
@xxxily 
这两个问题的原因貌似都是因为 youtube使用了 custom-elements-es5-adapter.js 脚本,修改了原生的window.customElements
我说说我的猜测
关于第一个问题, 这个项目的油猴脚本在页面开始就加载了,我猜测这时使用的是原生的window.customElements,后来youtube页面加载后,window.customElements被youtube修改了(修改了它的get和define方法),因此先前注册的custom Element 并没有记录在新的window.customElements里(get方法返回null), 因此重复注册
关于第二个问题, youtube的上述js脚本把window.customElements的define方法改了,第二个参数由class类型改成了函数类型,而这个项目使用的是类,所以报错

**Comment by crazy-zxx** [comment]
是啊，YouTube网站完全不显示插件
