### ISSUE TITLE
[BUG]快捷键已经接管了input框的输入了，打不了字

### ISSUE THREAD

**Issue by githubcatheaven** [xxxily/h5player#608]
当前焦点在视频下方的输入框里，但是快捷键已经接管了input框的输入了，打不了字。
一输入就会把快捷键的操作反映到视频操作上。

有点离谱，背离了这个player轻量好用的初衷。

**Comment by xxxily** [comment]
是代码就会有BUG啊，可以表达情绪，但不要情绪化表达……你不说哪个网站有问题，谁也解决不了啊，需要轻量的退回3.x版本，4.x增加了UI，我已尽可能想尽办法轻量了，但UI代码就那么多，要大力优化代码量的话得不偿失…

**Comment by xxxily** [comment]
无提供任何有用信息反馈，先关闭issues，有问题再反馈
