### ISSUE TITLE
[BUG] B 站的“特别关注” 被遮挡住了，点不了

### ISSUE THREAD

**Issue by Coldmooon** [xxxily/h5player#609]
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

![QQ截图20240219103322](https://github.com/xxxily/h5player/assets/4266166/407f4bce-650a-4b0f-b5a3-a6250f45751d)
![QQ截图20240219103302](https://github.com/xxxily/h5player/assets/4266166/32a3085e-ae61-455d-8d87-345d7d1b1367)

**Comment by xxxily** [comment]
见：https://github.com/xxxily/h5player/issues/603
