### ISSUE TITLE
[BUG]虎牙直播回放加载不出来

### ISSUE THREAD

**Issue by TPSKTP** [xxxily/h5player#618]
1. **问题描述**
虎牙直播回放有些加载不出来，有些可以，比如

2. **出现上述问题的地址**

https://www.huya.com/video/play/962639958.html    可以加载
https://www.huya.com/video/play/950176174.html    不可以加载
https://www.huya.com/video/play/966038144.html    不可以加载
3. **你使用的浏览器与浏览器版本信息** 
谷歌 Edge Firefox浏览器都是同样的情况。

5. **其他附注信息**

**Comment by xxxily** [comment]
已在群里沟通反馈过，暂无法解决，此处先关掉issues
