### ISSUE TITLE
edge浏览器中该脚本不能用

### ISSUE THREAD

**Issue by hauhs** [xxxily/h5player#62]
一但启用该脚本，会导致所有脚本不能用，且该脚本本身在edge中不能用，请检查，谢谢

**Comment by xxxily** [comment]
> 一但启用该脚本，会导致所有脚本不能用，且该脚本本身在edge中不能用，请检查，谢谢

测试过了，Microsoft Edge 最新版本下是可用的，如果你的不能用可能跟你的版本或环境有关

**Comment by hauhs** [comment]
脚本不稳定，有时可以用，有时不可以，浏览器已是最新版，如果脚本不可以用时还会发生脚本冲突，导致其他脚本不可以用，请核实，谢谢

**Comment by hauhs** [comment]
脚本不稳定，有时可以用，有时不可以，浏览器已是最新版，如果脚本不可以用时将会发生脚本冲突，导致其他脚本不可以用，请核实，谢谢

**Comment by Lidongde** [comment]
20/5/19 实测可以用，估计是楼主电脑环境问题
