### ISSUE TITLE
貌似是3.2.8版本的问题

### ISSUE THREAD

**Issue by sojey** [xxxily/h5player#63]
https://www.agefans.tv/play/20170082?playid=4_7

在播放过程中，鼠标点击任意画面的，非暂停按钮所在的区域，会自动变成全屏与默认窗口的切换，在之前版本好像没发生过这类问题。

**Comment by xxxily** [comment]
> https://www.agefans.tv/play/20170082?playid=4_7
> 
> 在播放过程中，鼠标点击任意画面的，非暂停按钮所在的区域，会自动变成全屏与默认窗口的切换，在之前版本好像没发生过这类问题。

网站本身问题吧

**Comment by sojey** [comment]
您自己安装 HTML5视频播放器增强脚本 3.2.8 。在 https://greasyfork.org/scripts/381682-html5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8%E5%A2%9E%E5%BC%BA%E8%84%9A%E6%9C%AC

然后打开，测试一下不就知道了，我肯定是测试过才会那么多。
