### ISSUE TITLE
为什么只能通过快捷键操作？

### ISSUE THREAD

**Issue by DuckDuck88** [xxxily/h5player#64]
个人觉得可以在视频边加一个操作按钮，快捷键过多，记不住鸭

**Comment by xxxily** [comment]
> 个人觉得可以在视频边加一个操作按钮，快捷键过多，记不住鸭

只有用快捷键才能获得操作快感

**Comment by luoweihua7** [comment]
> > 个人觉得可以在视频边加一个操作按钮，快捷键过多，记不住鸭
> 
> 只有用快捷键才能获得操作快感

期待后面可以加上控制界面，对用户来说，需要记住太多快捷键了。不同系统，不同app，不同插件对快捷键，比较费脑
