### ISSUE TITLE
功能请求：自定义开启或关闭某些快捷键

### ISSUE THREAD

**Issue by yinxiu1996** [xxxily/h5player#65]
希望可以自定义，哪些快捷键开启，哪些快捷键关闭。

**Comment by xxxily** [comment]
> 希望可以自定义，哪些快捷键开启，哪些快捷键关闭。

一直有这个打算，不过工作太忙没啥时间搞

**Comment by xxxily** [comment]
已支持自定义，见菜的【全局设置】或：https://h5player.anzz.top/home/customConfiguration.html
