### ISSUE TITLE
[bug] 按enter全屏导致页面错乱 | weibo twitter

### ISSUE THREAD

**Issue by willbeevil** [xxxily/h5player#66]
win10 1909
chrome 81

具体情况：
按回车键全屏，twitter&weibo网页会跳回到页面顶部（有时页面会错乱）

请求：
在twitter和weibo上按快捷键全屏后，信息流页面能保持在原位置

**Comment by xxxily** [comment]
> win10 1909
> chrome 81
> 
> 具体情况：
> 按回车键全屏，twitter&weibo网页会跳回到页面顶部（有时页面会错乱）
> 
> 请求：
> 在twitter和weibo上按快捷键全屏后，信息流页面能保持在原位置

是有这种情况，twitter兼容比较难，微博的后续再看下能不能兼容

**Comment by tea1111980** [comment]
@xxxily 我在这里也说说，我的情况跟这位题主 的问题是一样的，不过我出现问题的网站是：CSDN


相关截图：
![image](https://user-images.githubusercontent.com/16295097/85288656-aa30b880-b4c8-11ea-9b1a-0380bee96e72.png)


麻烦作者能不能兼容一下，谢谢！
