### ISSUE TITLE
只兼容 Tampermonkey？

### ISSUE THREAD

**Issue by ivysrono** [xxxily/h5player#67]
看到控制台报错，查了下，GM_getTab 系列应该只有 Tampermonkey支持，Violentmonkey 和 Greasemonkey 应该都是不支持的。

**Comment by xxxily** [comment]
> 看到控制台报错，查了下，GM_getTab 系列应该只有 Tampermonkey支持，Violentmonkey 和 Greasemonkey 应该都是不支持的。

目前只是按Tampermonkey来兼容，后续看情况要不要兼容Violentmonkey和Greasemonkey吧
