### ISSUE TITLE
enter全屏后超星网课不显示进度条

### ISSUE THREAD

**Issue by xixia479** [xxxily/h5player#68]

**Comment by xxxily** [comment]
有不需要登录就能访问的视频地址吗？要不然修复不了

**Comment by xixia479** [comment]
https://mooc1-2.chaoxing.com/nodedetailcontroller/visitnodedetail?courseId=200903896&knowledgeId=118533303

**Comment by xxxily** [comment]
> https://mooc1-2.chaoxing.com/nodedetailcontroller/visitnodedetail?courseId=200903896&knowledgeId=118533303

下个版本和增加兼容逻辑
