### ISSUE TITLE
bilibili每个新视频都精准到第4秒卡住

### ISSUE THREAD

**Issue by ArsenicX** [xxxily/h5player#69]
1. 测试环境：
系统：MacOS(10.15.4) 
浏览器：目前最新版Chrome(81.0.4044.113)
Chrome也已经关闭了所有其他拓展和其他脚本

2. 问题：
所有的视频，只要速度不是1.0，不管是大还是小都会在第4秒的时候卡住

这个是我上传到图床的一个录屏：https://streamja.com/XaqmZ
```https://streamja.com/XaqmZ```

**Comment by xxxily** [comment]
> 1. 测试环境：
>    系统：MacOS(10.15.4)
>    浏览器：目前最新版Chrome(81.0.4044.113)
>    Chrome也已经关闭了所有其他拓展和其他脚本
> 2. 问题：
>    所有的视频，只要速度不是1.0，不管是大还是小都会在第4秒的时候卡住
> 
> 这个是我上传到图床的一个录屏：https://streamja.com/XaqmZ
> `https://streamja.com/XaqmZ`

我这边没法重现，你退回到3.2.3版本看下会不会还是这样？

**Comment by ArsenicX** [comment]
> 我这边没法重现，你退回到3.2.3版本看下会不会还是这样？

还是不行，依然是会卡在4s的时候

**Comment by xxxily** [comment]
> 还是不行，依然是会卡在4s的时候

那应该不是脚本的问题，你换其他可以进行加速播放的脚本试试

**Comment by ArsenicX** [comment]
> 那应该不是脚本的问题，你换其他可以进行加速播放的脚本试试

我去查了下其他类似的问题，然后测试了今天一天，目前已经好了
解决方法是**重新开关一下Chrome的硬件加速**，虽然不清楚为啥会出现😅

还有个小的request我也顺便发了吧：
希望在网页全屏模式下，按`ESC`也能退出网页全屏，麻烦大佬了
