### ISSUE TITLE
统计访问泄露隐私

### ISSUE THREAD

**Issue by gqqnbig** [xxxily/h5player#7]
脚本里加入了以下代码

```
function statisticsInit () {
  window._hmt = window._hmt || [];
  (function () {
    var hm = document.createElement('script');
    hm.src = 'https://hm.baidu.com/hm.js?6815ad33453b781f873df096fae25ab4';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(hm, s);
  })();
}
```

本用户脚本默认在所有网页启用，意味着每个网页都会被加入上述百度统计代码，作者会获得所有用户的所有网页访问信息，具有严重的隐私泄露问题。

希望作者明确提示此统计功能，并允许用户开启。

**Comment by xxxily** [comment]
好的，下个版本加

**Comment by xxxily** [comment]
> 脚本里加入了以下代码
> 
> ```
> function statisticsInit () {
>   window._hmt = window._hmt || [];
>   (function () {
>     var hm = document.createElement('script');
>     hm.src = 'https://hm.baidu.com/hm.js?6815ad33453b781f873df096fae25ab4';
>     var s = document.getElementsByTagName('script')[0];
>     s.parentNode.insertBefore(hm, s);
>   })();
> }
> ```
> 
> 本用户脚本默认在所有网页启用，意味着每个网页都会被加入上述百度统计代码，作者会获得所有用户的所有网页访问信息，具有严重的隐私泄露问题。
> 
> 希望作者明确提示此统计功能，并允许用户开启。

脚本已移除
