### ISSUE TITLE
看知乎 pc  未登录，小窗视频不管看到第几个，小窗的都是上一个未看完的视频

### ISSUE THREAD

**Issue by likewhale** [xxxily/h5player#70]
看知乎 pc  未登录，小窗视频不管看到第几个，小窗的都不是当前的，但是倍速的快捷键控制的却是当前的视频，一小窗就是之前的未看完的视频了，没有了小窗的体验，大佬，求解决

**Comment by xxxily** [comment]
> 看知乎 pc 未登录，小窗视频不管看到第几个，小窗的都不是当前的，但是倍速的快捷键控制的却是当前的视频，一小窗就是之前的未看完的视频了，没有了小窗的体验，大佬，求解决

这个问题可能会比较棘手，后面看下怎么处理吧

**Comment by xxxily** [comment]
应该已解决，先关闭，如果还有问题再提issues吧
