### ISSUE TITLE
视频源受CORS标识限制，无法下载截图。

### ISSUE THREAD

**Issue by Leonardzhi** [xxxily/h5player#71]
求解决！

截图时提示：

视频源受CORS标识限制，无法下载截图。
您可向作者反馈信息，以便完善网站兼容逻辑。

**Comment by xxxily** [comment]
> 求解决！
> 
> 截图时提示：
> 
> 视频源受CORS标识限制，无法下载截图。
> 您可向作者反馈信息，以便完善网站兼容逻辑。

什么网址啊，有些可以支持，有些没法支持

**Comment by Leonardzhi** [comment]
> > 求解决！
> > 截图时提示：
> > 视频源受CORS标识限制，无法下载截图。
> > 您可向作者反馈信息，以便完善网站兼容逻辑。
> 
> 什么网址啊，有些可以支持，有些没法支持

视频所在的网址是：
https://n.news.naver.com/article/422/0000425065

**Comment by xxxily** [comment]
> > > 求解决！
> > > 截图时提示：
> > > 视频源受CORS标识限制，无法下载截图。
> > > 您可向作者反馈信息，以便完善网站兼容逻辑。
> > 
> > 
> > 什么网址啊，有些可以支持，有些没法支持
> 
> 视频所在的网址是：
> https://n.news.naver.com/article/422/0000425065
> 使用的是韩国门户网站Naver的播放器应该

测试了下，暂时兼容不了

**Comment by Aftermath863** [comment]
超星上面的视频也不能截图
