### ISSUE TITLE
特别爱用截图功能，最近发现一席的视频非常好，可以支持截图吗？

### ISSUE THREAD

**Issue by Rereyuop** [xxxily/h5player#72]
https://yixi.tv/speech/868 
这是一席的一个视频，他们也有在其他网站上传，除了 bilibili 是不设置水印的。

**Comment by xxxily** [comment]
> https://yixi.tv/speech/868
> 这是一席的一个视频，他们也有在其他网站上传，除了 bilibili 是不设置水印的。

测试过了，兼容不了
