### ISSUE TITLE
edge有时候不可用，要重启浏览器有时候才可以

### ISSUE THREAD

**Issue by hauhs** [xxxily/h5player#73]
脚本变量，有时可以用，有时不可以，浏览器已是最新版，如果脚本不可以用时将会发生脚本冲突，导致其他脚本不可以用，请核实，谢谢

**Comment by xxxily** [comment]
> 脚本变量，有时可以用，有时不可以，浏览器已是最新版，如果脚本不可以用时将会发生脚本冲突，导致其他脚本不可以用，请核实，谢谢

其他脚本那么多，无法一一排查，抱歉
