### ISSUE TITLE
bilibili通过shift+enter网页全屏后，焦点会自动变为弹幕框

### ISSUE THREAD

**Issue by ArsenicX** [xxxily/h5player#76]
设备：
系统：MacOS(10.15.4)
浏览器：目前最新版Chrome(81.0.4044.113)

使用场景：
进入视频页面后，先点击视频让他开始播放，然后按shift+enter进入网页全屏。
不过这时候下面的弹幕框就会被选中，底部的控制条一直是显示状态，而且这时如果想要用快捷键控制速度或者其他功能，就会变成输入文字。总要手动鼠标先点一下屏幕

我找到一个类似的可以实现的[脚本](https://greasyfork.org/en/scripts/30545-%E8%A7%86%E9%A2%91%E7%BD%91html5%E6%92%AD%E6%94%BE%E5%B0%8F%E5%B7%A5%E5%85%B7)，但是那个脚本有点其他的自己不喜欢的点，不如这个脚本好用。希望大佬可以改一下这个焦点的问题，谢谢了

**Comment by xxxily** [comment]
好的，下个版本发布的时候会修复这个问题
