### ISSUE TITLE
用网站自带的播放器调节播放速度后，再左右调节进度条后，速度又变成了1x

### ISSUE THREAD

**Issue by Tard1s** [xxxily/h5player#78]
比如：油管调自带1.25x播放。这时候用方向键控制进度条后 播放速度会复原成1x

**Comment by xxxily** [comment]
> 比如：油管调自带1.25x播放。这时候用方向键控制进度条后 播放速度会复原成1x

使用快捷键进行倍速播放就不会这样了

**Comment by chnprc** [comment]
靓仔，很多视频网站像YouTube、哔哩哔哩自带的倍速播放都和脚本有冲突，希望能修改一下

**Comment by xxxily** [comment]
已修复
