### ISSUE TITLE
youtube C倍速+0.1无效

### ISSUE THREAD

**Issue by garypang13** [xxxily/h5player#79]
youtube按C无法增加倍速,另外youtube的字幕快捷键也是C,会导致冲突,建议youtube的倍速+0.1改为其他快捷键

**Comment by xxxily** [comment]
> youtube按C无法增加倍速,另外youtube的字幕快捷键也是C,会导致冲突,建议youtube的倍速+0.1改为其他快捷键

等有自定义界面了再自己改

**Comment by garypang13** [comment]
那最好不过了,期待.

**Comment by anishmittal2020** [comment]
@xx

> > youtube按C无法增加倍速,另外youtube的字幕快捷键也是C,会导致冲突,建议youtube的倍速+0.1改为其他快捷键
> 
> 等有自定义界面了再自己改

@xxxily  Could you please tell us how can we change the shortcut key `C` to something else?
