### ISSUE TITLE
A站使用插件时暂停键不好用

### ISSUE THREAD

**Issue by saltdream** [xxxily/h5player#8]
你好，在Acfun使用插件时，点击空格暂停时会有非常短暂的暂停，此后仍然继续播放，如果您有时间的话，希望可以修复下这个问题。
此外，这个插件在我的日常学习中起到了很重要的作用，谢谢您与您的插件~祝你每天快乐~

**Comment by xxxily** [comment]
> 你好，在Acfun使用插件时，点击空格暂停时会有非常短暂的暂停，此后仍然继续播放，如果您有时间的话，希望可以修复下这个问题。
> 此外，这个插件在我的日常学习中起到了很重要的作用，谢谢您与您的插件~祝你每天快乐~

我测试了并没出现你描述的BUG，建议你升级到插件的最新版本或使用新版的chrome试试

**Comment by saltdream** [comment]
插件更新后一切正常了~谢谢~
