### ISSUE TITLE
greasyfork上面使用该脚本发现，直接按小键盘2，3调节倍速有瑕疵（腾讯视频有这个问题）

### ISSUE THREAD

**Issue by cailong-1** [xxxily/h5player#80]
如题，按数字键调整数倍功能很赞，但是用在腾讯视频上用这个方法会出现快进一大段时间线效果（倍速也实现了），作者可以试一下就知道了，b站优酷测试没有问题，出现在腾讯视频上面，版本号// @version      3.3.0

**Comment by CnNullptr** [comment]
这不是脚本的bug，腾讯视频里数字键是用于调整进度的，快捷键优先级高于脚本
