### ISSUE TITLE
网站请求加入超星学习通的网站，网课看不了小窗有点难受

### ISSUE THREAD

**Issue by Mr54233** [xxxily/h5player#82]
超星网址 http://i.mooc.chaoxing.com

**Comment by xxxily** [comment]
> 超星网址 http://i.mooc.chaoxing.com

没有账号测试，不知道是什么原因

**Comment by HydrogenDeuterium** [comment]
超星用得好像不是h5吧

**Comment by SituChengxiang** [comment]
学习通开倍速之后好像没有办法正常渲染，经常花屏（Firefox Developer Edition 134.0b10 ）不知道是不是H5的问题……，寒假期间（1月15日开始）如果有什么可以帮忙的可以联系我
