### ISSUE TITLE
Netflix冲突

### ISSUE THREAD

**Issue by GZ-Juice** [xxxily/h5player#84]
开启该脚本使用netflix时，一旦点击暂停/快进/快退等按钮，再次操作会停止播放转到netflix报错页面

**Comment by xxxily** [comment]
> 开启该脚本使用netflix时，一旦点击暂停/快进/快退等按钮，再次操作会停止播放转到netflix报错页面

没有账号测试了，要修复应该不难

**Comment by vlascik** [comment]
Can confirm, netflix breaks on pause/rewind (Error M7375, conflict with an extension), works again fine after disabling this script. 

No output in console. 

Zoom works, but contrast/brightness/saturation hotkeys turns the screen black, no video.

They have trial accounts, perhaps you could debug it that way?
