### ISSUE TITLE
Bug,稳定性问题。

### ISSUE THREAD

**Issue by FunAomi** [xxxily/h5player#85]
环境：最新版edge，谷歌内核的。
油猴：stable版.
安装后可以使用一段时间，关机开机再打开就不行，
然后卸载油猴再安装，就又可以了。

下午测试（增加）：
在edge的正常页面无法生效，但是开了隐私页面后，却是可以的。

晚上测试（增加）：
突然又好了，未作任何操作。
迷幻~

正在测试chrome浏览器的稳定性。
10小时内正常。

**Comment by xxxily** [comment]
> 环境：最新版edge，谷歌内核的。
> 油猴：stable版.
> 安装后可以使用一段时间，关机开机再打开就不行，
> 然后卸载油猴再安装，就又可以了。
> 正在测试chrome浏览器的稳定性。

是有这种情况，但似乎不是脚本本身的问题，具体原因也不是很清楚
