### ISSUE TITLE
关于快捷键反馈

### ISSUE THREAD

**Issue by DengJingheng** [xxxily/h5player#87]
希望每个快捷键在按下后能得到反馈，否则可能不清楚自己的按键到底有没有生效。尤其是倍速变化，没有反馈可能无法反应过来

**Comment by xxxily** [comment]
> 希望每个快捷键在按下后能得到反馈，否则可能不清楚自己的按键到底有没有生效。尤其是倍速变化，没有反馈可能无法反应过来

都有反馈啊，视频的左上角有操作提示

**Comment by DengJingheng** [comment]
好吧，刚刚才发现……
尴尬，( ͡°ᴥ ͡° ʋ)打扰了


| |
静恒
邮箱：17674122462@163.com
|

签名由 网易邮箱大师 定制

在2020年05月25日 15:26，xxxily 写道：

希望每个快捷键在按下后能得到反馈，否则可能不清楚自己的按键到底有没有生效。尤其是倍速变化，没有反馈可能无法反应过来

都有反馈啊，视频的左上角有操作提示
