### ISSUE TITLE
关于快捷键问题

### ISSUE THREAD

**Issue by yblysyl** [xxxily/h5player#88]
而且我这边再用b站时无法用zx键，点击x直接关闭页面，点击z开始焦点进入搜索框，我把他们改为，qwe才能实现倍速更改，另腾讯视频好像减速会出现问题

**Comment by xxxily** [comment]
> 而且我这边再用b站时无法用zx键，点击x直接关闭页面，点击z开始焦点进入搜索框，我把他们改为，qwe才能实现倍速更改，另腾讯视频好像减速会出现问题

是不是跟你安装的其它插件冲突了？我这边没发现这些现象

**Comment by passing11** [comment]
问下在哪改的

**Comment by passing11** [comment]
> 而且我这边再用b站时无法用zx键，点击x直接关闭页面，点击z开始焦点进入搜索框，我把他们改为，qwe才能实现倍速更改，另腾讯视频好像减速会出现问题

问下在哪改的，的确是插件冲突了
