### ISSUE TITLE
请问可以添加像ckplayer一样拉伸画面铺满屏幕以消除视频黑边的功能么，谢谢

### ISSUE THREAD

**Issue by 3322964** [xxxily/h5player#89]
请问可以添加像ckplayer一样拉伸画面铺满屏幕以消除视频黑边的功能么，谢谢

**Comment by xxxily** [comment]
> 请问可以添加像ckplayer一样拉伸画面铺满屏幕以消除视频黑边的功能么，谢谢

暂时没打算加入这个功能，画面拉伸后也不好看吧

**Comment by 3322964** [comment]
主要是以前普屏方屏时代的老电视剧电影都是4比3的，现在宽屏播放器下普遍都有很大的黑边相当有碍观瞻，pc播放器都有消除黑边的功能〜就是网页h5 flash播放器没有，全屏拉伸消除黑边还是不错的〜 对于整体观感不会有粗糙不适反而提升了美观不少〜
