### ISSUE TITLE
请问一下，插件能否增加定义快进为10秒回退为5秒？

### ISSUE THREAD

**Issue by sojey** [xxxily/h5player#90]
如果能设置成这样，对快跳时的补足会很有帮助。而不是去10秒回10秒还要多等几秒才能到比较合适的时间点。

**Comment by xxxily** [comment]
> 如果能设置成这样，对快跳时的补足会很有帮助。而不是去10秒回10秒还要多等几秒才能到比较合适的时间点。

这需求比较特殊，暂时不会这样添加

**Comment by HydrogenDeuterium** [comment]
2167行左右 skipstep=5 可以自己改
