### ISSUE TITLE
[功能请求]请问能否兼容本地网页和data uri网页

### ISSUE THREAD

**Issue by hallnorthncov** [xxxily/h5player#91]
我在新edge浏览器地址栏通过 data:text/html, 写的播放本地视频的网页在播放视频时无法使用本脚本，油猴脚本扩展的 允许访问文件URL 复选项已经选上了。请问有没有什么方法可以让本地网页和data uri网页可以使用本脚本？或者修改哪部分可以增加兼容？
在网页源码之前加上 data:text/html, 输入到浏览器地址栏可以打开一个本地网页，这是我写的网页：
data:text/html,<script> function onUpload (file) { var blob = new Blob([file]), url = URL.createObjectURL(blob); var x = document.createElement("VIDEO"); x.setAttribute("controls", "controls"); x.setAttribute("src", url); document.body.appendChild(x); } </script> <input type="file" onchange=onUpload(this.files[0])  /  >

**Comment by xxxily** [comment]
> 我在新edge浏览器地址栏通过 data:text/html, 写的播放本地视频的网页在播放视频时无法使用本脚本，油猴脚本扩展的 允许访问文件URL 复选项已经选上了。请问有没有什么方法可以让本地网页和data uri网页可以使用本脚本？或者修改哪部分可以增加兼容？
> 在网页源码之前加上 data:text/html, 输入到浏览器地址栏可以打开一个本地网页，这是我写的网页：
> data:text/html,<script> function onUpload (file) { var blob = new Blob([file]), url = URL.createObjectURL(blob); var x = document.createElement("VIDEO"); x.setAttribute("controls", "controls"); x.setAttribute("src", url); document.body.appendChild(x); } </script> <input type="file" onchange=onUpload(this.files[0]) / >

开启允许访问文件网址，然后再将规则匹配模式修改成匹配全部试试，
`// @match        *://*/*`

**Comment by hallnorthncov** [comment]
开启允许访问文件网址，再将规则匹配模式修改成匹配全部后，file://的本地网页可以使用脚本了。
但是使用data uri的网页还是不能使用脚本， `// @match *://*/*`   `// @match *`   `// @match data:text/html,*`    `// @match data:*` 也试过了，都不行

**Comment by xxxily** [comment]
> > > 我在新edge浏览器地址栏通过 data:text/html, 写的播放本地视频的网页在播放视频时无法使用本脚本，油猴脚本扩展的 允许访问文件URL 复选项已经选上了。请问有没有什么方法可以让本地网页和data uri网页可以使用本脚本？或者修改哪部分可以增加兼容？
> > > 在网页源码之前加上 data:text/html, 输入到浏览器地址栏可以打开一个本地网页，这是我写的网页：
> > > data:text/html,<script> function onUpload (file) { var blob = new Blob([file]), url = URL.createObjectURL(blob); var x = document.createElement("VIDEO"); x.setAttribute("controls", "controls"); x.setAttribute("src", url); document.body.appendChild(x); } </script> <input type="file" onchange=onUpload(this.files[0]) / >
> > 
> > 
> > 开启允许访问文件网址，然后再将规则匹配模式修改成匹配全部试试，
> > `// @match *://*/*`
> 
> 谢谢。开启允许访问文件网址，再将规则匹配模式修改成匹配全部后，file://的本地网页可以使用了。
> 但是使用data uri的网页还是不能使用脚本， `// @match *://*/*` `// @match *` `// @match data:text/html,*` `// @match data:*` 也试过了，都不行

这个应该跟插件的匹配规则有关，如果无法匹配上则无法运行对应脚本，那就是没办法的了

**Comment by hallnorthncov** [comment]
> > > > 我在新edge浏览器地址栏通过 data:text/html, 写的播放本地视频的网页在播放视频时无法使用本脚本，油猴脚本扩展的 允许访问文件URL 复选项已经选上了。请问有没有什么方法可以让本地网页和data uri网页可以使用本脚本？或者修改哪部分可以增加兼容？
> > > > 在网页源码之前加上 data:text/html, 输入到浏览器地址栏可以打开一个本地网页，这是我写的网页：
> > > > data:text/html,<script> function onUpload (file) { var blob = new Blob([file]), url = URL.createObjectURL(blob); var x = document.createElement("VIDEO"); x.setAttribute("controls", "controls"); x.setAttribute("src", url); document.body.appendChild(x); } </script> <input type="file" onchange=onUpload(this.files[0]) / >
> > > 
> > > 
> > > 开启允许访问文件网址，然后再将规则匹配模式修改成匹配全部试试，
> > > `// @match *://*/*`
> > 
> > 
> > 谢谢。开启允许访问文件网址，再将规则匹配模式修改成匹配全部后，file://的本地网页可以使用了。
> > 但是使用data uri的网页还是不能使用脚本， `// @match *://*/*` `// @match *` `// @match data:text/html,*` `// @match data:*` 也试过了，都不行
> 
> 这个应该跟插件的匹配规则有关，如果无法匹配上则无法运行对应脚本，那就是没办法的了

好吧，谢谢
