### ISSUE TITLE
百度网盘web端快进问题

### ISSUE THREAD

**Issue by yikuaibro** [xxxily/h5player#92]
前进键后退键有时无反应，空格键也是，需要再次点击屏幕才可以。

**Comment by xxxily** [comment]
> 前进键后退键有时无反应，空格键也是，需要再次点击屏幕才可以。

我这边测试没发现有这种情况，估计跟你浏览器版本或其它插件冲突等因素有关

**Comment by HydrogenDeuterium** [comment]
我猜问题是你焦点不在视频上。
