### ISSUE TITLE
能不能加入锁定网站视频倍速

### ISSUE THREAD

**Issue by BaiBuCYBGT** [xxxily/h5player#93]
刷视频需要用到倍速播放，发现脚本好像有做，只不过前一个视频16倍速，放完之后下一个视频，前几秒是16倍，然后就恢复1倍了。不知道能不能加入锁定网站固定倍速播放。
或者有没有大佬能指点一下怎么把默认设置成16倍

**Comment by xxxily** [comment]
> 刷视频需要用到倍速播放，发现脚本好像有做，只不过前一个视频16倍速，放完之后下一个视频，前几秒是16倍，然后就恢复1倍了。不知道能不能加入锁定网站固定倍速播放。
> 或者有没有大佬能指点一下怎么把默认设置成16倍

16倍这还是看视频吗？默认已经有记录播放速度功能，至于你看的网站为什么不能保持倍速，需要提供网站调试下才知道
