### ISSUE TITLE
画中画问题

### ISSUE THREAD

**Issue by FLYFIR** [xxxily/h5player#95]
画中画的应用场景一般是要干别的事情，比如学习做笔记、看其他资料，往往会需要暂停，这点很多画中画的脚本和扩展都有考虑到，但是都没有进度条，用来回看一些重要的片段。如果要倒退的话则必须回到网页才可以拖动。

这似乎是一个很难的问题，很多画中画都没有欸。

**Comment by xxxily** [comment]
最新版已解决该问题
